Repository RediSearch/RediSearch, pull requests merged in 2020-08, with the labels that each got.

#1435 Add NOINITIALINDEX flag
  docs/Commands.md
  src/pytest/test_followhashes.py
  src/spec.c
  src/spec.h
Labels: 2.0 feature

#1221 Synonyms with lower case
  src/pytest/test_synonyms.py
  src/synonym_map.c
  src/synonym_map.h
  src/tag_index.c
  src/util/strconv.h
Labels: 2.0 feature

#1246 Distance function for aggregation APPLY
  docs/Aggregations.md
  src/aggregate/functions/function.c
  src/aggregate/functions/function.h
  src/aggregate/functions/geo.c
  src/pytest/test_geo.py
Labels: New Functionality, aggregations, enhancement

#1470 Fix endless loop when reaching internal docid above uint32_max (#1469)
  src/index.c
Labels: bug

#1468 fix geo doc
  docs/Aggregations.md
Labels: docs

#1474 support redis unlink cmd
  src/notifications.c
  src/pytest/test_followhashes.py
Labels: bug
