Repository RediSearch/RediSearch, pull requests merged in 2020-07, with the labels that each got.

#1286 check docId vs lastDocId
  src/id_list.c
  src/index.c
  src/index_iterator.h
  src/pytest/test_issues.py
  src/pytest/test_tags.py
Labels: bug

#1083 Update Commands.md
  docs/Commands.md
Labels: docs

#1364 RoF - fix rdb load + benchmark
  src/pytest/test_rof.py
Labels: 2.0 feature
