Repository RediSearch/RediSearch, pull requests merged in 2021-06, with the labels that each got.

#1957 LOCAL/CI automated benchmarks kickoff
  .circleci/config.yml
  Makefile
  tests/ci.benchmarks/.gitignore
  tests/ci.benchmarks/requirements.txt
  tests/ci.benchmarks/ycsb-commerce-hashes-load.yml
  tests/ci.benchmarks/ycsb-commerce-hashes-run-40.yml
Labels: x:quality

#2012 TIMEOUT 0 set timeout to INT32_MAX
  src/aggregate/aggregate_request.c
  src/result_processor.h
  tests/pytests/CMakeLists.txt
  tests/pytests/test_config.py
Labels: c:bug

#2064 [MOD] hash index should not index json and the contrary.
  src/document.c
  src/info_command.c
  src/rules.c
  src/rules.h
  src/spec.c
  tests/pytests/test_json.py
Labels: c:bug

#2033 GEO can now be SORTABLE
  src/document.c
  src/field_spec.c
  tests/pytests/test_geo.py
Labels: c:enhancement
