Repository RediSearch/RediSearch, pull requests merged in 2021-07, with the labels that each got.

#2132 [2.0] [MOD-1266] delete document if failed to update. #2113
  src/document.c
  src/spec.c
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#2137 FT.INFO has identifier and attribute for fields
  src/info_command.c
  tests/pytests/test.py
  tests/pytests/test_aof.py
  tests/pytests/test_json.py
Labels: pr:break

#2083 Release drafter
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog
