Repository RediSearch/RediSearch, pull requests merged in 2021-12, with the labels that each got.

#2408 [LLAPI] Add RediSearch_IndexInfo
  src/redisearch_api.c
  src/redisearch_api.h
  tests/cpptests/test_cpp_llapi.cpp
Labels: x:api

#2392 [BUG] remove limit on geo percision
  src/rs_geo.c
  tests/pytests/test_geo.py
Labels: c:bug

#2407 [BUG] return error for spec w/o fields parameters
  src/spec.c
  tests/pytests/test_issues.py
Labels: c:bug

#2424 [PERF] On trie, check char on local node array
  deps/triemap/triemap.c
Labels: x:perf

#2425 PERF triemap: using memchr() to locate character in block of memory instead of our looped implementation
  deps/triemap/triemap.c
Labels: x:perf

#2427 [2.2] trie fix - use memchr
  deps/triemap/triemap.c
Labels: pr:cherrypick

#2426 [2.0] trie fix - use memchr
  src/dep/triemap/triemap.c
Labels: pr:cherrypick

#2440 [BUG] Fix NOT iterator
  src/index.c
  tests/pytests/test.py
Labels: c:bug

#2386 [BUG] NUMERIC index leak fix
  src/config.c
  src/config.h
  src/debug_commads.c
  src/fork_gc.c
  src/numeric_index.c
  src/numeric_index.h
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_numbers.py
Labels: c:bug

#2442 [2.2] CP #2440 Not iterator fix
  src/index.c
  tests/pytests/test.py
Labels: pr:cherrypick

#2444 [2.2] CP Timeout freeze while sorting fix #2414
  src/aggregate/aggregate_exec.c
  tests/pytests/test.py
Labels: pr:cherrypick

#2448 [LLAPI] add setLang and setScore
  src/language.c
  src/language.h
  src/redisearch_api.c
  src/redisearch_api.h
  src/stemmer.c
  src/stemmer.h
  tests/cpptests/test_cpp_llapi.cpp
Labels: x:llapi

#2445 [2.2] NUMERIC index leak fix (#2386)
  src/config.c
  src/config.h
  src/debug_commads.c
  src/fork_gc.c
  src/numeric_index.c
  src/numeric_index.h
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_numbers.py
Labels: pr:cherrypick

#2443 [2.0] CP #2440 Not iterator fix
  src/index.c
  tests/pytests/test.py
Labels: pr:cherrypick

#2456 [2.2] [LLAPI] add setLang and setScore (#2448)
  src/language.c
  src/language.h
  src/redisearch_api.c
  src/redisearch_api.h
  src/stemmer.c
  src/stemmer.h
  tests/cpptests/test_cpp_llapi.cpp
Labels: pr:cherrypick
