Repository RediSearch/RediSearch, pull requests merged in 2021-01, with the labels that each got.

#1689 [BUG] Stabilize results for FT.SUGGET
  src/trie/trie_type.c
  tests/pytests/test_suggest.py
Labels: bug

#1776 Implements contains for APPLY/FILTER on FT.AGGREGATE
  docs/Aggregations.md
  src/aggregate/functions/string.c
  tests/pytests/test_aggregate.py
Labels: aggregations, enhancement

#1767 FT.PROFILE command
  docs/Commands.md
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/aggregate/expr/expression.c
  src/aggregate/expr/expression.h
  src/commands.h
  src/config.c
  src/config.h
  src/debug_commads.c
  src/geo_index.c
  src/highlight_processor.c
  src/index.c
  src/index.h
  src/inverted_index.c
  src/inverted_index.h
  src/module.c
  src/numeric_index.c
  src/profile.c
  src/profile.h
  src/query.c
  src/redisearch.h
  src/result_processor.c
  src/result_processor.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_geo.py
  tests/pytests/test_profile.py
Labels: enhancement
