Repository RediSearch/RediSearch, pull requests merged in 2021-03, with the labels that each got.

#1879 Improved RLookup_HGETALL() by using RM_ScanKey instead of RM_Call( HGETALL... ) on Redis version 6.0.6 and above
  src/config.h
  src/rlookup.c
Labels: x:perf

#1807 Php redis
  README.md
  docs/Clients.md
Labels: x:docs

#1902 Fix: using old RLookup_HGETALL() logic on enterprise-crdt
  src/rlookup.c
Labels: c:bug

#1910 Fixed RLTest invocations with multiple sets of module args
  .circleci/ci_diag_san12.sh
  Makefile
  system-setup.py
  tests/pytests/CMakeLists.txt
  tests/pytests/runtests.sh
  tests/pytests/test_rdb_compatibility.py
Labels: x:build

#1908 Fix test to new FT.PROFILE format
  tests/pytests/test_profile.py
Labels: x:tests

#1886 [LL API] Add a test for scoring
  src/redisearch_api.c
  tests/cpptests/test_cpp_llapi.cpp
Labels: x:tests

#1875 Return fast on empty stopword list
  src/stopwords.c
Labels: c:enhancement

#1891 Add a counter ResultProcessor
  src/aggregate/aggregate.h
  src/aggregate/aggregate_plan.h
  src/aggregate/aggregate_request.c
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/test_profile.py
Labels: c:enhancement

#1913 Avoid expensive unecessary strlen within RLookup_GetKeyEx()
  src/rlookup.c
  src/rlookup.h
Labels: x:perf
