Repository RediSearch/RediSearch, pull requests merged in 2021-08, with the labels that each got.

#2156 [2.0] TAG fields CASESENSITIVE flag
  docs/Commands.md
  docs/Tags.md
  src/ext/default.c
  src/info_command.c
  src/query.c
  src/query_node.h
  src/query_parser/parser.c
  src/query_parser/parser.y
  src/spec.c
  src/spec.h
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test_fuzzy.py
  tests/pytests/test_tags.py
Labels: pr:cherrypick

#2163 Enable ftsb_redisearch related benchmarks on CI benchmarks
  Makefile
  cmake/redisearch_cflags.cmake
  cmake/redisearch_debug.cmake
  tests/ci.benchmarks/.gitignore
  tests/ci.benchmarks/defaults.yml
  tests/ci.benchmarks/ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/ci.benchmarks/ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/ci.benchmarks/ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/ci.benchmarks/ftsb-1M-enwiki_abstract-hashes-load.yml
  tests/ci.benchmarks/ftsb-1M-nyc_taxis-ftadd-load.yml
  tests/ci.benchmarks/ftsb-1M-nyc_taxis-hashes-load.yml
  tests/ci.benchmarks/requirements.txt
Labels: x:quality, skip-changelog

#2190 Avoid unneeded code (small performance fix)
  src/doc_types.h
  src/notifications.c
Labels: x:perf

#2186 [2.0] LLAPI getter functions for score, language and stopwords list (#2184)
  src/document_basic.c
  src/redisearch_api.c
  src/redisearch_api.h
  src/rules.c
  src/spec.c
  src/spec.h
  src/stopwords.c
  src/stopwords.h
  tests/cpptests/test_cpp_llapi.cpp
Labels: pr:cherrypick

#2188 Add UNF flag for SORTABLE fields
  src/document.c
  src/field_spec.h
  src/sortable.c
  src/sortable.h
  src/spec.c
  src/spec.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test.py
  tests/pytests/test_issues.py
Labels: c:feature

#2205 [2.0] fix RSValue_Hash with null value #2203
  src/value.h
  tests/pytests/test_issues.py
Labels: c:bug, pr:cherrypick

#2206 MOD-1549 return RM_OK if field does not exist
  src/json.c
  src/rlookup.c
  tests/pytests/test_json.py
Labels: c:bug

#2224 [BUG] fix FIELDS for highlight
  src/aggregate/aggregate_request.c
  tests/pytests/test_issues.py
Labels: c:bug

#2223 [BUG] Replace NULL with empty iterator for child of negative iterator
  src/index.c
  tests/pytests/test_profile.py
Labels: c:bug
