Repository RediSearch/RediSearch, pull requests merged in 2022-01, with the labels that each got.

#2466 Fix FT.PROFILE for FT.AGGREGATE
  coord/src/dist_aggregate.c
Labels: c:bug

#2467 Fix FT.PROFILE for FT.AGGREGATE (#2466)
  coord/src/dist_aggregate.c
Labels: pr:cherrypick

#2410 Adding Redis om clients to list of available RediSearch clients
  README.md
  docs/Clients.md
Labels: x:docs

#2469 [LLAPI] add API for TAG children query nodes
  src/redisearch_api.c
  src/redisearch_api.h
  tests/cpptests/test_cpp_llapi.cpp
Labels: x:llapi

#2470 [2.2] add LLAPI for TAG children query nodes (#2469)
  src/redisearch_api.c
  src/redisearch_api.h
  tests/cpptests/test_cpp_llapi.cpp
Labels: pr:cherrypick

#2471 [2.0] add LLAPI for TAG children query nodes (#2469)
  src/query.c
  src/query_node.h
  src/redisearch_api.c
  src/redisearch_api.h
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_query.cpp
Labels: pr:cherrypick

#2474 [2.2] Fix FT.PROFILE no result processor is peresent (#2473)
  coord/src/dist_aggregate.c
Labels: pr:cherrypick

#2490 [BUG] Lower case with default separator
  src/tag_index.c
  tests/pytests/test_json.py
Labels: c:bug

#2494 [2.2] Lower case with default separator (#2490)
  src/tag_index.c
  tests/pytests/test_json.py
Labels: pr:cherrypick

#2495 Add rdb support to vecsim type
  src/spec.c
  src/spec.h
  src/vector_index.c
  src/vector_index.h
  tests/pytests/test_vecsim.py
Labels: x:rdb

#2537 Fix intersect iterator
  src/index.c
  tests/cpptests/test_cpp_index.cpp
Labels: c:bug

#2506 Test for issue 436 result count for ft.aggregare
  tests/pytests/test_aggregate.py
Labels: x:tests

#2507 [BUG] quantile position is enflated
  src/util/quantile.c
  tests/pytests/test_aggregate.py
Labels: c:bug

#2541 [BUG] fix doubles for FT.INFO on COORD
  coord/src/info_command.c
  tests/pytests/common.py
  tests/pytests/test_coordinator.py
Labels: c:bug
