Repository RediSearch/RediSearch, pull requests merged in 2022-03, with the labels that each got.

#2581 Vecsim parser fix
  src/hybrid_reader.c
  src/hybrid_reader.h
  src/query.c
  src/query_parser/lexer.c
  src/query_parser/lexer.rl
  src/query_parser/parser.c
  src/query_parser/parser.h
  src/query_parser/parser.y
  src/vector_index.c
  src/vector_index.h
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test.py
  tests/pytests/test_profile.py
  tests/pytests/test_search_params.py
  tests/pytests/test_vecsim.py
Labels: pr:break

#2613 [TEST] fix flaky test_free_resources_on_thread
  tests/pytests/test.py
Labels: x:tests

#2596 Parser upgrade
  docs/Query_Syntax.md
  src/query_parser/parser.c
  src/query_parser/parser.h
  src/query_parser/parser.y
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test.py
  tests/pytests/test_parser.py
Labels: pr:break

#2551 [DOC] timeout
  docs/Commands.md
Labels: x:docs

#2641 [BUG] Memory leak in the coordinator
  coord/src/rmr/rmr.c
Labels: c:bug

#2651 [BUG] fix client freeze on docs expire during query
  src/aggregate/aggregate_exec.c
  src/result_processor.c
  src/spec.c
  tests/pytests/test_followhashes.py
Labels: c:bug

#2678 [DOC] Add docs for SORTABLE
  docs/commands/ft.aggregate.md
  docs/commands/ft.create.md
  docs/commands/ft.search.md
Labels: x:docs
