Repository RediSearch/RediSearch, pull requests merged in 2022-11, with the labels that each got.

#3198 [2.4] release failed-to-create temporary index on the main thread (#3…
  src/spec.c
  tests/pytests/test.py
Labels: pr:cherrypick

#3168 [2.4] MOD-4252: Coordinator leak fix (#3143)
  coord/src/module.c
  src/util/heap.c
  src/util/heap.h
Labels: pr:cherrypick

#3187 [2.4] MOD-4411: Fixing double freeing in hybrid iterator
  src/hybrid_reader.c
Labels: c:bug, pr:cherrypick

#3193 [TEST] fix testRedisCommands
  sbin/get-redisjson
  tests/pytests/common.py
  tests/pytests/includes.py
  tests/pytests/runtests.sh
  tests/pytests/test_json.py
Labels: x:tests

#3188 [2.4] Implement NumericRangeIterator_OnReopen
  src/numeric_index.c
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#3210 [2.6] release failed-to-create temporary index on the main thread (#3197)
  src/spec.c
  tests/pytests/test.py
Labels: pr:cherrypick

#3195 Add doc for multi value GEO
  docs/docs/Indexing_JSON.md
Labels: x:docs

#3220 Document dialect 3 and multi projection
  docs/commands/ft.aggregate.md
  docs/commands/ft.search.md
  docs/docs/Configuring.md
  docs/docs/reference/Vectors.md
Labels: x:docs

#3138 Update ft.cursor-read.md
  docs/commands/ft.cursor-read.md
Labels: x:docs

#3140 Update ft.dictdump.md
  docs/commands/ft.dictdump.md
Labels: x:docs

#3216 [FIX] MOD-4265: fix flakiness of vector similarity timeout test
  tests/pytests/test_vecsim.py
Labels: x:tests

#3203 Update vecsim examples and docs
  docs/docs/Indexing_JSON.md
  docs/docs/Vector-Similarity-Hybrid-Queries.ipynb
  docs/docs/reference/Query_Syntax.md
  docs/docs/reference/Vectors.md
  docs/docs/vecsim-hybrid_queries_examples.ipynb
  docs/docs/vecsim-range_queries_examples.ipynb
Labels: x:docs

#3171 [BUG] `NumericRangeIterator_OnReopen` is not implemented
  src/numeric_index.c
  tests/pytests/test_issues.py
Labels: c:bug

#3233 [2.6] `NumericRangeIterator_OnReopen` is not implemented (#3171)
  src/numeric_index.c
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#3235 [2.6] MOD-4480: Differentiate between JSON API version 2 and 3
  src/json.c
  src/rejson_api.h
  src/rlookup.c
Labels: pr:cherrypick

#3240 [2.6] Fix #3230, use the correct max results value
  src/aggregate/aggregate_request.c
  src/result_processor.c
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#3255 Fix NOFIELDS typo
  docs/commands/ft.create.md
Labels: x:docs
