Repository RediSearch/RediSearch, pull requests merged in 2022-08, with the labels that each got.

#2876 [DOC] add comments about expired keys content as s null-array
  docs/commands/ft.aggregate.md
  docs/commands/ft.search.md
Labels: x:docs

#2946 On TrieMap, move qsort to insert
  deps/triemap/triemap.c
  deps/triemap/triemap.h
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_triemap.cpp
  tests/pytests/test_contains.py
  tests/pytests/test_tags.py
Labels: x:perf

#2962 [BUG] Use local GC ctx in periodic callback
  src/gc.c
  src/spec.c
  tests/pytests/test_gc.py
Labels: c:bug

#2937 [BUG] On slave, expiref docs do not return NULL
  src/result_processor.c
  src/rlookup.c
  src/spec.c
  tests/pytests/test_expire.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_issues.py
  tests/pytests/test_replicate.py
Labels: x:tests

#2932 Wildcard query support with suffix trie
  deps/wildcard/wildcard.c
  deps/wildcard/wildcard.h
  src/query.c
  src/suffix.c
  src/suffix.h
  src/trie/rune_util.c
  src/trie/trie.c
  src/trie/trie.h
  tests/cpptests/test_cpp_trie.cpp
  tests/ctests/test_wildcard.c
  tests/pytests/test_wildcard.py
Labels: c:feature

#2986 [BUG] clear SchemaPrefixNode if all related indexes were deleted
  src/rules.c
  tests/pytests/test_issues.py
Labels: c:bug

#2990 [PERF] Add child to TrieMap without using qsort
  deps/triemap/triemap.c
  tests/cpptests/CMakeLists.txt
  tests/cpptests/test_cpp_triemap.cpp
Labels: x:perf

#2999 [TEST] Change total_indexing_time print to float
  src/info_command.c
Labels: x:tests

#3000 Cherry pick for 2.4 - DO NOT SQUASH
  deps/triemap/triemap.c
  deps/triemap/triemap.h
  src/result_processor.c
  src/rlookup.c
  src/rules.c
  tests/pytests/test_expire.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_issues.py
  tests/pytests/test_replicate.py
Labels: pr:cherrypick

#2931 [DOC] FT command edit
  docs/commands/ft.aggregate.md
  docs/commands/ft.aliasadd.md
  docs/commands/ft.aliasdel.md
  docs/commands/ft.aliasupdate.md
  docs/commands/ft.alter.md
  docs/commands/ft.config-get.md
  docs/commands/ft.config-help.md
  docs/commands/ft.config-set.md
  docs/commands/ft.create.md
  docs/commands/ft.cursor-del.md
  docs/commands/ft.cursor-read.md
  docs/commands/ft.dictadd.md
  docs/commands/ft.dictdel.md
  docs/commands/ft.dictdump.md
  docs/commands/ft.dropindex.md
  docs/commands/ft.explain.md
  docs/commands/ft.explaincli.md
  docs/commands/ft.info.md
  docs/commands/ft.profile.md
  docs/commands/ft.search.md
  docs/commands/ft.spellcheck.md
  docs/commands/ft.sugadd.md
  docs/commands/ft.sugdel.md
  docs/commands/ft.sugget.md
  docs/commands/ft.suglen.md
  docs/commands/ft.syndump.md
  docs/commands/ft.synupdate.md
  docs/commands/ft.tagvals.md
Labels: x:docs

#3017 [BUG] fix forkGC null cardVals pointer
  src/fork_gc.c
  tests/pytests/test_numbers.py
Labels: bug

#3040 [BUG] Fix SORTBY numeric field for Non-Sortable on the coordinator
  src/aggregate/aggregate_exec.c
  tests/pytests/test.py
  tests/pytests/test_sortby.py
Labels: c:bug

#2979 [BUG] docs that miss the sortby field may aappear before docs that has it
  coord/src/module.c
  src/result_processor.c
  tests/pytests/test.py
  tests/pytests/test_issues.py
Labels: c:bug

#3049 [2.4] Fix SORTBY numeric field for Non-Sortable on the coordinator (#…
  src/aggregate/aggregate_exec.c
  tests/pytests/test.py
  tests/pytests/test_sortby.py
Labels: pr:cherrypick
