Repository RediSearch/RediSearch, pull requests merged in 2022-10, with the labels that each got.

#3125 Added term-level queries benchmark (suffix,prefix,contains,wildcard)
  tests/benchmarks/defaults.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-ftadd-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-hashes-load.yml
Labels: x:quality

#3169 [BUG] redirect prefix query from suffixtrie
  src/query.c
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/pytests/test_contains.py
Labels: c:bug

#3170 Added suffix search benchmark variation that uses the new WITHSUFFIXTRIE feature
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml
Labels: x:quality

#3182 MOD-4345: Make SORTABLE field always UNF on JSON
  src/field_spec.h
  src/info_command.c
  src/spec.c
  tests/pytests/test_json.py
Labels: pr:break, breakingchange
