Repository RediSearch/RediSearch, pull requests merged in 2022-09, with the labels that each got.

#3047 Support StrLen in FT.AGGREGATE
  docs/docs/reference/Aggregations.md
  src/aggregate/functions/string.c
  tests/pytests/test_aggregate.py
Labels: c:enhancement

#3052 [2.2] Fix SORTBY numeric field for Non-Sortable on the coordinator #3040
  src/aggregate/aggregate_exec.c
  tests/pytests/test.py
  tests/pytests/test_sortby.py
Labels: pr:cherrypick

#3050 [2.4] docs that miss the sortby field may aappear before docs that ha…
  coord/src/module.c
  src/result_processor.c
  tests/pytests/test.py
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#2939 [BUG] fix Heap-Union iterator
  src/index.c
Labels: c:bug

#3048 [PERF] update the term-trie only if term does not exist in term-dictionary
  src/debug_commads.c
  src/fork_gc.c
  src/indexer.c
  src/inverted_index.c
  src/legacy_gc.c
  src/redis_index.c
  src/redis_index.h
  src/spell_check.c
Labels: c:enhancement, x:perf

#3065 [PERF] use kk >name_len instead of strlen
  src/aggregate/aggregate_exec.c
Labels: x:perf

#3071 [2.6] Cherry pick latest PRs - DO NOT SQUASH
  coord/src/module.c
  coord/src/rmr/redis_cluster.c
  coord/src/rmr/rmr.c
  deps/triemap/triemap.c
  docs/docs/Quick_Start.md
  docs/docs/reference/Vectors.md
  src/aggregate/aggregate_exec.c
  src/concurrent_ctx.c
  src/debug_commads.c
  src/dictionary.c
  src/fork_gc.c
  src/hybrid_reader.c
  src/index.c
  src/indexer.c
  src/info_command.c
  src/inverted_index.c
  src/legacy_gc.c
  src/module.c
  src/module.h
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/redis_index.c
  src/redis_index.h
  src/result_processor.c
  src/spell_check.c
  src/suggest.c
  src/trie/trie.c
  src/trie/trie.h
  src/trie/trie_type.c
  src/trie/trie_type.h
  tests/cpptests/test_cpp_trie.cpp
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_issues.py
  tests/pytests/test_numbers.py
  tests/pytests/test_search_params.py
  tests/pytests/test_sortby.py
Labels: pr:cherrypick

#3067 Add documentation on indexing and searching multi numeric
  docs/docs/Indexing_JSON.md
Labels: x:docs

#2729 Unify repeated Lettuce/Spring clients and remove JRediSearch
  docs/docs/Clients.md
Labels: x:docs

#3019 [2.4] Include wildcard search queries in oss-standalone and oss-cluster CI benchmarks #2917
  .circleci/config.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-ftadd-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-hashes-load.yml
  tests/benchmarks/search-geo.yml
  tests/benchmarks/search-numeric-sortby-desc.yml
  tests/benchmarks/search-numeric-sortby.yml
  tests/benchmarks/search-numeric.yml
Labels: x:quality

#3077 [BUG] fix ft.profile. add RPs after pipeline creation
  src/aggregate/aggregate_request.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/test_profile.py
Labels: c:bug

#3066 [PERF] Add nameLen to index spec instead of using strlen
  src/document.c
  src/redis_index.c
  src/spec.c
  src/spec.h
Labels: x:perf

#3112 Numeric benchmarks changes
  tests/benchmarks/search-numeric-sortby-desc.yml
  tests/benchmarks/search-numeric-sortby.yml
  tests/benchmarks/search-numeric.yml
Labels: x:quality

#3119 Fix MOD-4200, crash on intersect iterator GetCriteriaTester.
  src/index.c
  tests/pytests/test.py
Labels: c:bug
