Repository RediSearch/RediSearch, pull requests merged in 2022-07, with the labels that each got.

#2571 Add rueidis to Clients.md
  README.md
  docs/docs/Clients.md
Labels: x:docs

#2871 Removed YCSB (java) benchmark variations from 2.2
  tests/benchmarks/ycsb-commerce-hashes-load.yml
  tests/benchmarks/ycsb-commerce-hashes-run-0.yml
  tests/benchmarks/ycsb-commerce-hashes-run-10.yml
  tests/benchmarks/ycsb-commerce-hashes-run-20.yml
  tests/benchmarks/ycsb-commerce-hashes-run-30.yml
  tests/benchmarks/ycsb-commerce-hashes-run-40.yml
  tests/benchmarks/ycsb-commerce-hashes-run-50.yml
  tests/benchmarks/ycsb-commerce-json-load.yml
  tests/benchmarks/ycsb-commerce-json-run-0.yml
  tests/benchmarks/ycsb-commerce-json-run-10.yml
  tests/benchmarks/ycsb-commerce-json-run-20.yml
  tests/benchmarks/ycsb-commerce-json-run-30.yml
  tests/benchmarks/ycsb-commerce-json-run-40.yml
  tests/benchmarks/ycsb-commerce-json-run-50.yml
Labels: x:quality

#2872 Removed YCSB (java) benchmark variations from 2.4
  tests/benchmarks/ycsb-commerce-hashes-load.yml
  tests/benchmarks/ycsb-commerce-hashes-run-0.yml
  tests/benchmarks/ycsb-commerce-hashes-run-10.yml
  tests/benchmarks/ycsb-commerce-hashes-run-20.yml
  tests/benchmarks/ycsb-commerce-hashes-run-30.yml
  tests/benchmarks/ycsb-commerce-hashes-run-40.yml
  tests/benchmarks/ycsb-commerce-hashes-run-50.yml
  tests/benchmarks/ycsb-commerce-json-load.yml
  tests/benchmarks/ycsb-commerce-json-run-0.yml
  tests/benchmarks/ycsb-commerce-json-run-10.yml
  tests/benchmarks/ycsb-commerce-json-run-20.yml
  tests/benchmarks/ycsb-commerce-json-run-30.yml
  tests/benchmarks/ycsb-commerce-json-run-40.yml
  tests/benchmarks/ycsb-commerce-json-run-50.yml
Labels: x:quality

#2870 Removed YCSB (java) benchmark variations from 2.0
  tests/benchmarks/ycsb-commerce-hashes-load.yml
  tests/benchmarks/ycsb-commerce-hashes-run-40.yml
Labels: x:quality

#2873 Removed YCSB (java) benchmark variations from master
  tests/benchmarks/ycsb-commerce-hashes-load.yml
  tests/benchmarks/ycsb-commerce-hashes-run-0.yml
  tests/benchmarks/ycsb-commerce-hashes-run-10.yml
  tests/benchmarks/ycsb-commerce-hashes-run-20.yml
  tests/benchmarks/ycsb-commerce-hashes-run-30.yml
  tests/benchmarks/ycsb-commerce-hashes-run-40.yml
  tests/benchmarks/ycsb-commerce-hashes-run-50.yml
  tests/benchmarks/ycsb-commerce-json-load.yml
  tests/benchmarks/ycsb-commerce-json-run-0.yml
  tests/benchmarks/ycsb-commerce-json-run-10.yml
  tests/benchmarks/ycsb-commerce-json-run-20.yml
  tests/benchmarks/ycsb-commerce-json-run-30.yml
  tests/benchmarks/ycsb-commerce-json-run-40.yml
  tests/benchmarks/ycsb-commerce-json-run-50.yml
Labels: x:quality

#2877 [TEST] fix testRedisCommands
  tests/pytests/test_json.py
Labels: x:tests

#2875 [BUG] open RM_Key before calling getDocType on it
  src/doc_types.h
  src/spec.c
Labels: c:bug

#2846 adding enterprise memory limit to vecsim index build
  src/spec.c
Labels: c:bug

#2863 [BUG] Change MAX_LEV_DISTANCE to 4
  src/module.c
  tests/pytests/test_spell_check.py
Labels: c:bug

#2885 [2.4] Change MAX_LEV_DISTANCE to 4 (#2863)
  src/module.c
  tests/pytests/test_spell_check.py
Labels: pr:cherrypick

#2884 [LLVM] fix compilation on macOS
  src/trie/trie.c
  src/trie/trie.h
Labels: MacOS

#2893 [2.4] SORTBY with MAX corrupt reply (#2892)
  src/aggregate/aggregate_request.c
  tests/pytests/test_coordinator.py
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#2915 Fix doc links from redis.com to redis.io
  README.md
Labels: x:docs

#2924 [2.4] disable SORTBY MAX with FT.SEARCH (#2900)
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  tests/pytests/test_issues.py
Labels: pr:cherrypick

#2865 [BUG] set limit on lat lon radius for GEO
  deps/geohash/geohash_helper.c
  src/geo_index.c
  src/query.c
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test_geo.py
Labels: c:bug

#2933 [2.2] set limit on lat lon radius for GEO (#2865)
  deps/geohash/geohash_helper.c
  src/geo_index.c
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test_geo.py
Labels: pr:cherrypick

#2906 [PERF] Add factor to union and intersect iterators
  src/index.c
Labels: x:perf

#2917 Include wildcard search queries in oss-standalone and oss-cluster CI benchmarks
  .circleci/config.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-ftadd-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-hashes-load.yml
  tests/benchmarks/search-geo.yml
  tests/benchmarks/search-numeric-sortby-desc.yml
  tests/benchmarks/search-numeric-sortby.yml
  tests/benchmarks/search-numeric.yml
Labels: x:quality

#2624 Introduce nearest neighbors benchmarks using ann-benchmarks
  .circleci/config.yml
  tests/benchmarks/.gitignore
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
Labels: x:quality
