Repository RediSearch/RediSearch, pull requests merged in 2023-12, with the labels that each got.

#4152 Fix install scripts
  .install/install_script.sh
  .install/rocky_linux_8.sh
  .install/rocky_linux_9.sh
  sbin/setup
Labels: backport 2.8, backport 2.6

#4150 Test oss global password - [MOD-6117]
  coord/src/rmr/conn.c
  coord/src/rmr/endpoint.h
  tests/pytests/runtests.sh
  tests/pytests/test.py
Labels: c:bug, backport 2.8, backport 2.6

#4147 MOD-6232 Incorrect initialization of numeric range maximum value
  src/numeric_index.c
  tests/pytests/test_numbers.py
  tests/pytests/test_profile.py
Labels: backport 2.8, backport 2.6

#4149 MOD-5990: Return timeout error from cursor on strict timeout policy
  src/aggregate/aggregate_exec.c
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
Labels: backport 2.8

#4168 Fix flaky test_mod5778_add_new_shard_to_cluster - take2
  tests/pytests/common.py
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6

#4148 MOD-6035: Respect timeout policy P2 (coordinator)
  coord/src/dist_aggregate.c
  coord/src/module.c
  coord/src/rmr/redis_cluster.c
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
Labels: backport 2.8

#4169 Fix Coordinator Shutdown flakiness - [MOD-6073]
  coord/src/module.c
  coord/src/rmr/redis_cluster.c
  coord/src/rmr/redis_cluster.h
  coord/src/rmr/rq.c
Labels: backport 2.8, backport 2.6

#4165 MOD-6184: Return timeout errors from `FT.PROFILE`
  coord/src/dist_aggregate.c
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/numeric_index.h
  src/profile.c
  src/profile.h
  src/result_processor.c
  tests/pytests/test.py
  tests/pytests/test_geo.py
  tests/pytests/test_issues.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
  tests/pytests/test_wildcard.py
Labels: backport 2.8

#4164 MOD-6234: Report warnings in Resp3
  coord/src/dist_aggregate.c
  coord/src/module.c
  src/aggregate/aggregate_exec.c
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
Labels: backport 2.8

#4191 Set a timeout for tests using RLTest - [MOD-6023]
  Makefile
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6

#4180 Test TLS password - [MOD-6119]
  sbin/gen-test-certs
  tests/pytests/common.py
  tests/pytests/includes.py
  tests/pytests/runtests.sh
  tests/pytests/test.py
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6

#4189 MOD-6019 fix flaky test_followhashes:testManyPrefixes
  src/debug_commads.c
  tests/pytests/test_debug_commands.py
  tests/pytests/test_followhashes.py
Labels: backport 2.8, backport 2.6

#4209 Test fix for backport
  .github/workflows/task-backport_pr.yml
Labels: backport 2.8, backport 2.6

#4211 Test
  .github/workflows/flow-macos.yml
Labels: backport 2.8, backport 2.6

#4200 Fix wildcard and contains tests - [MOD-5807]
  tests/pytests/test_contains.py
  tests/pytests/test_issues.py
  tests/pytests/test_wildcard.py
Labels: backport 2.8, backport 2.6

#4221 Stabalize CI
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  tests/pytests/test_scorers.py
Labels: backport 2.8, backport master

#4142 Disable unnecessary Circle flows - [MOD-6176]
  .circleci/config.yml
Labels: backport 2.8, backport 2.6

#4190 MOD-6250: Fix crash on `FT.PROFILE .. AGGREGATE ..` commands
  coord/src/dist_aggregate.c
  coord/src/module.c
  src/aggregate/aggregate_exec.c
  tests/pytests/test_profile.py
Labels: backport 2.8

#4161 Fix test_invalid_mt_config_combinations
  tests/pytests/test_multithread.py
Labels: backport 2.8

#4235 Deleting term from trie - fix bug in memcpy upon merging nodes [MOD-5880, MOD-5952]
  src/fork_gc.c
  src/trie/trie.c
  src/trie/trie_type.c
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6

#4236 MOD-6198 add vecsim info to ft.info
  src/info_command.c
  tests/pytests/common.py
  tests/pytests/test_info.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8

#4220 Fix Freeing flow - GC and timers - [MOD-6276]
  src/debug_commads.c
  src/fields_global_stats.c
  src/fork_gc.c
  src/fork_gc.h
  src/gc.c
  src/gc.h
  src/module.c
  src/spec.c
  src/vector_index.c
  src/vector_index.h
  tests/pytests/test_debug_commands.py
  tests/pytests/test_issues.py
  tests/pytests/test_vecsim.py
Labels: c:bug, backport 2.8

#4246 [2.8] Fix Freeing flow - GC and timers - [MOD-6276]
  src/debug_commads.c
  src/fields_global_stats.c
  src/fork_gc.c
  src/fork_gc.h
  src/gc.c
  src/gc.h
  src/module.c
  src/spec.c
  src/vector_index.c
  src/vector_index.h
  tests/pytests/test_debug_commands.py
  tests/pytests/test_issues.py
  tests/pytests/test_vecsim.py
Labels: c:bug

#4242 Improved getting tags workflow
  .github/workflows/task-get-latest-tag.yml
Labels: backport 2.8, backport 2.6

#3916 MOD-5769: open json key with flags
  src/rejson_api.h
  src/rlookup.c
  tests/pytests/test_expire.py
Labels: backport 2.8

#4244 MOD-5512: Add timeout check in NOT iterator
  src/index.c
  src/index.h
  src/inverted_index.h
  src/query.c
  src/util/timeout.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test.py
Labels: backport 2.8, backport 2.6

#4257 MOD-6252: Remove multi-threading timeout flakiness
  src/aggregate/aggregate_exec.c
  tests/pytests/test_async.py
Labels: backport 2.8

#4239 Refactor test add new shard to cluster
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6

#4271 [MOD-6022] fix flakyness of test_expire:testExpireDocs
  tests/pytests/test_expire.py
Labels: backport 2.8, backport 2.6

#4279 Enabled SPOT Instance deployments on CI benchmarks
  tests/benchmarks/defaults.yml
  tests/benchmarks/search-aggregate-post-filter-simple.yml
  tests/benchmarks/search-filtering-tag-numeric-filter-pipeline.yml
  tests/benchmarks/search-filtering-tag-numeric.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-fulltext-sortby.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-load.yml
  tests/benchmarks/search-ftsb-10K-multivalue-numeric-json.yml
  tests/benchmarks/search-ftsb-10K-singlevalue-numeric-json.yml
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable@50_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-ftadd-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-hashes-load.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
  tests/benchmarks/search-geo.yml
  tests/benchmarks/search-high-cardinality-negation-term-baseline.yml
  tests/benchmarks/search-high-cardinality-negation-term-comparison_union_all_other_terms.yml
  tests/benchmarks/search-numeric-optimize.yml
  tests/benchmarks/search-numeric-sortby-desc-optimized.yml
  tests/benchmarks/search-numeric-sortby-desc.yml
  tests/benchmarks/search-numeric-sortby-optimized.yml
  tests/benchmarks/search-numeric-sortby.yml
  tests/benchmarks/search-numeric.yml
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-arxiv-titles-384-angular-filters-m16-ef-128-fulltext-filter.yml
  tests/benchmarks/vecsim-arxiv-titles-384-angular-filters-m16-ef-128-numeric-filter.yml
  tests/benchmarks/vecsim-arxiv-titles-384-angular-filters-m16-ef-128-tag-filter.yml
Labels: action:run-benchmark, backport 2.8, backport 2.6

#4277 MOD-6292 fix flaky CI - test_rdb_compatibility:testRDBCompatibility
  tests/pytests/test_rdb_compatibility.py
Labels: backport 2.8, backport 2.6

#4288 [2.8] Fix NULL related bugs [MOD-6337, MOD-6336]
  coord/src/dist_aggregate.c
  src/spec.c
Labels: c:bug

#4287 Fix NULL related bugs [MOD-6337, MOD-6336]
  coord/src/dist_aggregate.c
  src/spec.c
Labels: c:bug, backport 2.8
