Repository RediSearch/RediSearch, pull requests merged in 2023-10, with the labels that each got.

#3874 MOD-5757 fix inverted index GC related bugs and numeric index root max depth
  src/debug_commads.c
  src/doc_table.c
  src/fork_gc.c
  src/fork_gc.h
  src/inverted_index.c
  src/numeric_index.c
  tests/cpptests/test_cpp_forkgc.cpp
  tests/pytests/common.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_numbers.py
Labels: backport 2.8, backport 2.10, backport 2.6

#3913 MOD-5875 - fix upload artifacts to s3
  .circleci/config.yml
Labels: backport 2.8, backport 2.10, backport 2.6

#3853 Make users' cursors trigger cursor read at the shards when needed - [MOD-5580]
  coord/src/config.c
  coord/src/config.h
  coord/src/dist_aggregate.c
  coord/src/module.c
  coord/src/rmr/command.c
  coord/src/rmr/command.h
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  src/aggregate/aggregate_exec.c
  src/resp3.h
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.10, backport 2.6

#3784 Fix sanitizer warning about "global-buffer-overflow"
  src/index.c
Labels: backport 2.8, backport 2.10

#3947 Fix flakiness of `testCursorOnCoordinator`
  tests/pytests/common.py
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.10, backport 2.6

#3954 Fix macos build
  .circleci/config.yml
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.10

#3953 Added q1, q2, q3, and q4 large union iterator benchmarks
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
Labels: action:run-benchmark

#3960 [2.6] Added q1, q2, q3, and q4 large union iterator benchmarks (#3953)
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
Labels: action:run-benchmark

#3966 initialize MRCommand.depleted - MOD-5937
  coord/src/rmr/command.c
Labels: backport 2.8, backport 2.10, backport 2.6

#3934 Rename arm arch in pack filename
  sbin/pack.sh
Labels: backport 2.8, backport 2.10

#3961 [2.8] Added q1, q2, q3, and q4 large union iterator benchmarks (#3953)
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
Labels: action:run-benchmark

#3967 MT resharding fix [MOD-5874]
  deps/thpool/thpool.c
  deps/thpool/thpool.h
  src/concurrent_ctx.c
  src/gc.c
  src/notifications.c
  src/spec.c
  src/util/logging.c
  src/util/logging.h
  src/util/workers.c
  tests/cpptests/test_cpp_thpool.cpp
  tests/pytests/common.py
  tests/pytests/includes.py
  tests/pytests/test_short_read.py
Labels: backport 2.8, backport 2.10

#3978 Rename zip filename for macos build
  sbin/pack.sh
Labels: backport 2.8, backport 2.10, backport 2.6

#3914 Enable geo queries to register to "On Reopen" - [MOD-5646]
  src/geo_index.c
  src/geo_index.h
  src/query.c
  tests/pytests/common.py
  tests/pytests/test_geo.py
Labels: backport 2.8, backport 2.10, backport 2.6

#3931 Code cleanup for future events - [MOD-5646]
  src/index.c
  src/index.h
  src/inverted_index.c
  src/inverted_index.h
  src/numeric_index.c
  src/redis_index.c
  src/tag_index.c
Labels: backport 2.8, backport 2.10
