Repository RediSearch/RediSearch, pull requests merged in 2023-11, with the labels that each got.

#3920 MOD-5209 - Coordinator timeout fix for `FT.AGGREGATE`
  coord/src/dist_aggregate.c
  coord/src/partition.h
  coord/src/rmr/cluster.c
  coord/src/rmr/cluster.h
  coord/src/rmr/command.c
  coord/src/rmr/command.h
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  src/aggregate/aggregate_exec.c
  src/redis_index.c
  src/result_processor.c
  src/result_processor.h
  src/search_ctx.h
  tests/pytests/test_aggregate.py
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.10

#3988 MOD-5945: Fix bad comparison
  coord/src/search_cluster.c
  tests/pytests/test.py
Labels: backport 2.8, backport 2.10, backport 2.6

#3987 MOD-5965: Return error upon timeout
  src/aggregate/aggregate_exec.c
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_resp3.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.10

#3749 Run flow tests with log-level Debug
  Makefile
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.10, backport 2.6

#3870 Minor improvement to serializing numeric value
  src/value.c
Labels: backport 2.8, backport 2.10, backport 2.6

#3908 GHA refactor - moved benchmark CI to GHA - [MOD-5733]
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  .github/workflows/benchmark-trigger.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/event-weekly.yml
  .github/workflows/trigger-benchmark.yml
Labels: action:run-benchmark

#4023 Fix log level for mac
  tests/pytests/requirements.txt
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.10, backport 2.6

#4022 Improvement for PR 3853 (cursor on coordinator) - [MOD-6089]
  coord/src/dist_aggregate.c
  coord/src/rmr/chan.c
  coord/src/rmr/chan.h
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  src/cursor.c
  src/cursor.h
  src/spec.c
  tests/pytests/test_aggregate.py
  tests/pytests/test_cursors.py
  tests/pytests/test_json.py
Labels: backport 2.8, backport 2.10, backport 2.6

#4029 fix thpool size format print in redisearch_thpool_init
  deps/thpool/thpool.c
  src/util/logging.c
Labels: backport 2.8, backport 2.10

#4041 Align os name for macos
  sbin/get-redisjson
  sbin/upload-artifacts
Labels: backport 2.8, backport 2.6

#4036 Add log messages when fork GC fails
  src/fork_gc.c
Labels: backport 2.8, backport 2.10, backport 2.6

#4058 run platforms flows
  sbin/get-redisjson
Labels: backport 2.8, backport 2.10, backport master

#4063 Get right artifacts for testing redisjson
  sbin/get-redisjson
Labels: backport 2.8

#4057 MOD-5849 - fix coordinator request leak
  coord/src/module.c
  coord/src/rmr/rmr.c
  coord/src/rmr/rq.c
  coord/src/rmr/rq.h
Labels: backport 2.8, backport 2.10, backport 2.6

#4076 Fix macos setup
  tests/pytests/requirements.macos.txt
  tests/pytests/requirements.txt
Labels: backport 2.8, backport 2.10, backport 2.6

#3932 MOD-5868: Support Mariner2 OS using github actions
  .github/workflows/mariner2.yml
  .install/mariner2.sh
  sbin/get-redisjson
  sbin/upload-artifacts
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.10

#4059 MOD-5966: Return cursor-id for non-depleted cursor in non-strict timeout policy
  src/aggregate/aggregate_exec.c
  tests/pytests/test_cursors.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.10

#4096 Improve Benchmark triggering
  .github/workflows/benchmark-trigger.yml
Labels: action:run-benchmark

#3940 Partially reverting optimization of intersection iterator [MOD-5910] [PERF]
  src/config.c
  src/config.h
  src/index.c
  tests/pytests/test_config.py
  tests/pytests/test_issues.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_scorers.py
Labels: x:perf, bug, action:run-benchmark, backport 2.8, backport 2.10

#4077 [Feature] Moving to GitHub Actions
  .circleci/config.yml
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  .github/workflows/benchmark-trigger.yml
  .github/workflows/build-linux-platforms.yml
  .github/workflows/build-macos.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/event-release.yml
  .github/workflows/event-weekly.yml
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-coverage.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/flow-macos.yml
  .github/workflows/flow-sanitizer.yml
  .github/workflows/flow-self-hosted-arm.yml
  .github/workflows/flow-temp.yml
  .github/workflows/sanitizer.yml
  .github/workflows/self-hosted.yml.TEMPLATE
  .github/workflows/task-backport_pr.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-docs-approval.yml
  .github/workflows/task-get-linux-configurations.yml
  .github/workflows/task-release-drafter.yml
  .github/workflows/task-stale.yml
  .github/workflows/task-test.yml
  .github/workflows/task-website-deploy.yml
  .github/workflows/trigger-benchmark.yml
  .install/amazon_linux_2.sh
  .install/centos_linux_7.sh
  .install/debian_gnu_linux_11.sh
  .install/install_cmake.sh
  .install/install_script.sh
  .install/macos.sh
  .install/rocky_linux_8.8.sh
  .install/rocky_linux_9.2.sh
  .install/ubuntu_18.04.sh
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  sbin/pack.sh
  sbin/upload-artifacts
  src/version.h
  tests/pytests/runtests.sh
Labels: x:build

#4095 GHA refactor - assign to issue
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/task-assign-for-issue.yml
Labels: x:build

#4094 GHA refactor - skip CI on docs-only PRs - [MOD-6101]
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-temp.yml
  .github/workflows/task-check-docs.yml
  .github/workflows/task-docs-approval.yml
Labels: x:build

#4103 Fix flaky invalid MT configs tests [MOD-6020]
  src/dictionary.c
  src/module-init/module-init.c
  tests/pytests/runtests.sh
  tests/pytests/test_multithread.py
Labels: backport 2.8, backport 2.10

#4120 GHA refactor - fix dispatch
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/flow-macos.yml
  .github/workflows/flow-sanitizer.yml
  .github/workflows/task-test.yml
Labels: backport 2.8, backport 2.10, backport 2.6

#4119 GHA - Skip running benchmarks on unrelated PRs
  .github/workflows/event-push-to-integ.yml
Labels: backport 2.8, backport 2.10, backport 2.6

#4038 MOD-5948: Respect timeout policy P1 (single shard)
  coord/src/dist_aggregate.c
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/info_command.c
  src/query_error.h
  src/result_processor.c
  src/result_processor.h
  src/util/timeout.h
  src/vector_index.c
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_coordinator.py
Labels: backport 2.8, backport 2.10

#4118 Avoid Busy Loop on thpool Initialization
  deps/thpool/thpool.c
Labels: backport 2.8, backport 2.10, backport 2.6

#4122 GHA - improve benchmark rules
  .github/workflows/benchmark-trigger.yml
Labels: backport 2.8, backport 2.10, backport 2.6
