Repository RediSearch/RediSearch, pull requests merged in 2023-09, with the labels that each got.

#3818 Include a lightweight FILTER with implicit load benchmark
  tests/benchmarks/search-aggregate-post-filter-simple.yml
Labels: action:run-benchmark

#3823 [FIX] leak in `APPLY/FILTER` parser
  src/aggregate/expr/parser.c
  src/aggregate/expr/parser.y
Labels: c:bug, bug

#3827 [CP] [FIX] leak in `APPLY/FILTER` parser (#3823)
  src/aggregate/expr/parser.c
  src/aggregate/expr/parser.y
Labels: c:bug, pr:cherrypick, bug

#3826 [2.4] [FIX] leak in `APPLY/FILTER` parser (#3823)
  src/aggregate/expr/parser.c
  src/aggregate/expr/parser.y
Labels: c:bug, pr:cherrypick, bug

#3824 [2.8] [FIX] leak in `APPLY/FILTER` parser (#3823)
  src/aggregate/expr/parser.c
  src/aggregate/expr/parser.y
Labels: c:bug, pr:cherrypick, bug

#3809 [FIX] filter on coordinator - non-breaking
  coord/src/dist_plan.cpp
  coord/src/dist_plan.h
  src/aggregate/aggregate_plan.h
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
Labels: c:bug, bug

#3828 [2.10] [FIX] filter on coordinator - non-breaking (#3809)
  coord/src/dist_plan.cpp
  coord/src/dist_plan.h
  src/aggregate/aggregate_plan.h
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
Labels: pr:cherrypick

#3838 remove quick
  .circleci/config.yml
Labels: backport 2.8, backport 2.10

#3856 Fix crash upon adding new nodes to OSS cluster [MOD-5778]
  coord/src/rmr/cluster.c
  coord/src/rmr/rmr.c
  tests/pytests/test_issues.py
  tests/pytests/test_multithread.py
Labels: backport 2.8, backport 2.10

#3868 Fix trying to unlock an uninitialized spec in FGC_parentHandleNumeric
  src/fork_gc.c
Labels: backport 2.8, backport 2.10

#3875 MOD-5816: Fix macos build
  .circleci/config.yml
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.10

#3887 MOD-5600: Avoid conflicts in CircleCI persist workspace
  .circleci/config.yml
Labels: x:build, backport 2.8, backport 2.10

#3895 remove docker and dead automation
  .circleci/config.yml
Labels: backport 2.8, backport 2.10, backport 2.6
