Repository RediSearch/RediSearch, pull requests merged in 2024-09, with the labels that each got.

#4975 MOD-7695: Decide Ubuntu Runner Using Variable
  .github/workflows/benchmark-flow.yml
  .github/workflows/event-deploy-snapshots.yml
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-mirror.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/event-release.yml
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-coverage.yml
  .github/workflows/flow-self-hosted-arm.yml
  .github/workflows/self-hosted.yml.TEMPLATE
  .github/workflows/task-assign-for-issue.yml
  .github/workflows/task-backport_pr.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-check-docs.yml
  .github/workflows/task-get-latest-tag.yml
  .github/workflows/task-get-linux-configurations.yml
  .github/workflows/task-release-drafter.yml
  .github/workflows/task-stale.yml
  .github/workflows/task-take-shift.yml
  .github/workflows/task-test.yml
  .github/workflows/task-website-deploy.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4980 MOD-7706 fix ramp-packer version
  .install/build_package_requirments.txt
Labels: backport 2.10

#4989 MOD-7737: Add relaxation flags to Rocky9 installations
  .install/rocky_linux_8.sh
  .install/rocky_linux_9.sh
Labels: backport 2.8, backport 2.6, backport 2.10

#4984 MOD-7646 cmake fetch boost if not exists
  src/geometry/CMakeLists.txt
Labels: backport 2.8, backport 2.10

#4985 Fail to load a schema rule from RDB without asserting - [MOD-7587]
  src/rules.c
  src/rules.h
  src/spec.c
  tests/pytests/test_json.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4869 MOD-7253: Fix wildcard latency
  src/ext/default.c
  src/fork_gc.c
  src/index.c
  src/index.h
  src/indexer.c
  src/info_command.c
  src/inverted_index.c
  src/inverted_index.h
  src/profile.c
  src/query.c
  src/redis_index.c
  src/redis_index.h
  src/result_processor.c
  src/rules.c
  src/rules.h
  src/spec.c
  src/spec.h
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test_existing.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_missing.py
  tests/pytests/test_not.py
  tests/pytests/test_rdb_compatibility.py
  tests/pytests/test_resp3.py
  tests/pytests/test_short_read.py
Labels: backport 2.8, backport 2.10

#5025 MOD-7863: Add HPEXPIRETIME Mock Support
  tests/cpptests/redismock/redismock.cpp
Labels: backport 2.10

#5026 Fix benchmark to use new build path
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  tests/benchmarks/requirements.txt
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_glove-200-angular_M-4.yml
Labels: action:run-benchmark

#5053 MOD-7912: Constrain Redis Python Package
  tests/pytests/requirements.txt
Labels: backport 2.8, backport 2.6, backport 2.10

#5055 Update artifact name to upload after renaming oss to community
  sbin/upload-artifacts
Labels: backport 8.0
