Repository RediSearch/RediSearch, pull requests merged in 2024-08, with the labels that each got.

#4897 [2.6] VERBATIM is not passed to the shards on FT.AGGREGATE - [MOD-7463]
  coord/src/dist_aggregate.c
  tests/pytests/test_issues.py
Labels: bug

#4896 [2.8] VERBATIM is not passed to the shards on FT.AGGREGATE - [MOD-7463]
  coord/src/dist_aggregate.c
  tests/pytests/test_issues.py
Labels: bug

#4904 Fix flakiness in test:test_cluster_set - [MOD-7228]
  tests/pytests/test.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4903 MOD-7162: Fix info response format discrepency in coordinator
  src/coord/info_command.c
Labels: backport 2.10

#4909 Fix union of stopwords - [MOD-7495]
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4911 Support the deprecated MT configs again - [MOD-7519]
  src/config.c
  src/config.h
  src/module-init/module-init.c
  tests/pytests/test_config.py
Labels: bug, backport 2.10

#4919 MOD-7339: Fix field statistics counting bug
  src/spec.c
Labels: backport 2.8, backport 2.6, backport 2.10

#4918 [2.6] Fix union of stopwords - [MOD-7495]
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
Labels: bug

#4917 [2.8] Fix union of stopwords - [MOD-7495]
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
Labels: bug

#4916 [2.10] Fix union of stopwords - [MOD-7495]
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
Labels: bug

#4923 [2.10] Support the deprecated MT configs again - [MOD-7519]
  src/config.c
  src/config.h
  src/module-init/module-init.c
  tests/pytests/test_config.py
Labels: bug

#4920 Fix flakiness - [MOD-7228]
  src/coord/debug_command_names.h
  src/coord/debug_commands.c
  src/coord/rmr/redis_cluster.c
  src/coord/rmr/redis_cluster.h
  tests/pytests/test.py
  tests/pytests/test_debug_commands.py
Labels: backport 2.10

#4933 MOD-7588: Add warning for reaching `MAXPREFIXEXPANSIONS`
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/coord/dist_aggregate.c
  src/index.c
  src/profile.c
  src/profile.h
  src/query.c
  src/query_error.h
  src/suggest.c
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
Labels: backport 2.8, backport 2.10

#4941 MOD-7505 override ft.search on ramp
  src/coord/pack/ramp.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4942 MOD-7614: Remove redundant `MAXPREFIXEXPANSIONS` warning
  src/index.c
  tests/pytests/test_profile.py
Labels: pr:break, breakingchange

#4946 Small completion for TAG wildcard fix
  src/query.c
  tests/pytests/test_resp3.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4950 Fix numeric union reopen on profile [MOD-7454]
  src/index.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4954 [2.6] Fix numeric union reopen on profile [MOD-7454]
  src/index.c
  tests/pytests/test_issues.py
Labels: bug

#4960 Fix coordinator pending count - [MOD-7632]
  src/coord/rmr/rmr.c
  src/coord/rmr/rq.c
  tests/pytests/test_coordinator.py
Labels: bug

#4965 Conditionally Use AWS Role To Upload Artifacts
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/event-release.yml
  .github/workflows/task-build-artifacts.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4937 MOD-7596: Add mirroring support
  .github/workflows/event-mirror.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4961 [2.10] Fix coordinator pending count - [MOD-7632]
  coord/src/rmr/rmr.c
  coord/src/rmr/rq.c
  tests/pytests/test_coordinator.py
Labels: bug

#4963 [2.6] Fix coordinator pending count - [MOD-7632]
  coord/src/rmr/rmr.c
  coord/src/rmr/rq.c
  tests/pytests/test_coordinator.py
Labels: bug

#4972 Change maxPending requests when changing the number of connections
  src/coord/rmr/rmr.c
  src/coord/rmr/rq.c
  src/coord/rmr/rq.h
Labels: bug, backport 2.10
