Repository RediSearch/RediSearch, pull requests merged in 2024-10, with the labels that each got.

#5068 Test #4
  .github/workflows/task-backport_pr.yml
Labels: backport 2.10_jk_test

#5069 Backport Test #5
  README.md
Labels: backport 2.10_jk_test

#5077 build with macos-13
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-macos.yml
Labels: backport 8.0

#5079 Fix flaky test
  tests/pytests/test_json.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5075 MOD-7551: Return error on json limitations
  src/aggregate/aggregate_request.c
  tests/pytests/test_issues.py
  tests/pytests/test_json.py
Labels: backport 8.0, breaking change

#5041 MOD-7932: Use Github App Token For Backporting
  .github/workflows/task-backport_pr.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5061 MOD-7926: Fix Redis Package Tests
  .install/amazon_linux_2.sh
  tests/pytests/requirements.txt
  tests/pytests/test_issues.py
  tests/pytests/test_resp3.py
Labels: backport 8.0

#5051 MOD-7905: Fix test_not:test_not_optimized
  tests/pytests/test_not.py
Labels: backport 8.0

#5101 Improve Error Message on VecSim Syntax Error - [MOD-7887]
  src/query.c
  src/spec.c
  tests/pytests/test_vecsim.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5107 [2.6] Improve Error Message on VecSim Syntax Error - [MOD-7887]
  src/query.c
  src/spec.c
  tests/pytests/test_vecsim.py
Labels: bug

#5109 [2.10] Improve Error Message on VecSim Syntax Error - [MOD-7887]
  src/query.c
  src/spec.c
  tests/pytests/test_vecsim.py
Labels: bug

#5110 MOD-7965: Check Comment Author Association To Filter Github Apps From Triggering Workflow
  .github/workflows/task-backport_pr.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5120 Skip test_multithread:test_async_updates_sanity with sanitizer
  tests/pytests/test_multithread.py
Labels: backport 2.8, backport 2.10, backport 8.0

#5138 Remove an unnecessary assertion - [MOD-8008]
  src/coord/debug_command_names.h
  src/coord/debug_commands.c
  src/coord/rmr/rq.c
  src/coord/rmr/rq.h
  tests/pytests/test.py
  tests/pytests/test_debug_commands.py
Labels: bug, backport 2.10, backport 8.0

#5142 [2.10] Remove an unnecessary assertion - [MOD-8008]
  coord/src/debug_command_names.h
  coord/src/debug_commands.c
  coord/src/rmr/rq.c
  coord/src/rmr/rq.h
  tests/pytests/test.py
Labels: bug

#5141 [8.0] Remove an unnecessary assertion - [MOD-8008]
  src/coord/debug_command_names.h
  src/coord/debug_commands.c
  src/coord/rmr/rq.c
  src/coord/rmr/rq.h
  tests/pytests/test.py
  tests/pytests/test_debug_commands.py
Labels: bug

#5143 Add metrics of min and max memory consumption of indexes - [MOD-7584]
  src/info_command.h
  src/module-init/module-init.c
  src/redisearch_api.c
  tests/pytests/test_info_modules.py
Labels: backport 8.0
