Repository RediSearch/RediSearch, pull requests merged in 2024-06, with the labels that each got.

#4689 Fix ft.info ordering in the coordinator environment
  coord/src/info_command.c
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4446 MOD-6572 replace semaphore with wait in jobq
  deps/thpool/pthread_barrier.h
  deps/thpool/thpool.c
  deps/thpool/thpool.h
  src/concurrent_ctx.c
  src/gc.c
  src/spec.c
  src/util/workers.c
  tests/cpptests/test_cpp_thpool.cpp
  tests/pytests/test_multithread.py
Labels: backport 2.10

#4696 MOD-7126: Fix GEOSHAPE DISJOINT for intersecting MBRs
  src/geometry/rtree.cpp
  src/geometry/rtree.hpp
  tests/pytests/test_geometry_flat.py
  tests/pytests/test_geometry_sphere.py
Labels: backport 2.10

#4701 Fix privileged mechanism - [MOD-6838]
  deps/thpool/thpool.c
  tests/cpptests/test_cpp_thpool.cpp
Labels: backport 2.10

#4706 Removing an old warning-level log message - [MOD-7181]
  src/notifications.c
  src/spec.c
  src/spec.h
Labels: backport 2.8, backport 2.10

#4705 Privilege cleanup - [MOD-7187]
  deps/thpool/thpool.c
  deps/thpool/thpool.h
  src/concurrent_ctx.c
  src/config.c
  src/config.h
  src/gc.c
  src/module-init/module-init.c
  src/spec.c
  src/util/workers.c
  tests/cpptests/test_cpp_thpool.cpp
  tests/pytests/test_config.py
Labels: backport 2.10

#4716 redis 7.4
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
Labels: backport 2.10

#4717 Fix sorting multiple fields
  src/result_processor.c
Labels: bug

#4710 MOD-7200: Update empty indexing
  commands.json
  src/query.c
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.h
  src/query_parser/v2/parser.y
  src/query_parser/v3/lexer.c
  src/query_parser/v3/lexer.rl
  src/query_parser/v3/parser.c
  src/query_parser/v3/parser.h
  src/query_parser/v3/parser.y
  src/spec.h
  tests/pytests/test_empty.py
  tests/pytests/test_info_modules.py
  tests/pytests/test_short_read.py
Labels: backport 2.10

#4730 MOD-7203: Throw error upon NOINDEX and INDEXMISSING options for field creation
  src/spec.c
  tests/pytests/test_missing.py
Labels: backport 2.10

#4733 MOD-7240: Detect escape state when tokenizing
  src/toksep.h
  tests/cpptests/test_cpp_tokenizer.cpp
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4612 RSValue array cleanup - [MOD-7145]
  coord/src/dist_aggregate.c
  src/aggregate/functions/string.c
  src/aggregate/reducers/random_sample.c
  src/aggregate/reducers/to_list.c
  src/rlookup.c
  src/value.c
  src/value.h
Labels: backport 2.8, backport 2.10

#4598 Groupby recursion cleanup - [MOD-7245]
  src/aggregate/group_by.c
  tests/pytests/test_aggregate.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4748 Revert "remove ubuntu 18.04"
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/task-get-linux-configurations.yml
  .install/ubuntu_18.04.sh
Labels: backport 2.10

#4735 MOD-7212: Fix empty string parsing
  src/query.c
  src/query_node.h
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.h
  src/query_parser/v2/parser.y
  src/query_parser/v3/lexer.c
  src/query_parser/v3/lexer.rl
  src/query_parser/v3/parser.c
  src/query_parser/v3/parser.h
  src/query_parser/v3/parser.y
  src/redisearch.h
  tests/pytests/common.py
  tests/pytests/test_empty.py
  tests/pytests/test_search_params.py
Labels: backport 2.10

#4753 Fix MAX reducer for negative values [MOD-7252]
  src/aggregate/reducers/minmax.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4729 MOD-7214: Avoid using redis to retrieve a value of sortable field if value should be in cache and is not(i.e missing)
  src/aggregate/aggregate_request.c
  src/result_processor.c
  src/result_processor.h
  src/rlookup.c
  src/rlookup.h
Labels: action:run-benchmark

#4764 disable temp flow
  .github/workflows/flow-temp.yml
Labels: backport 2.10

#4740 MOD-7201: Improve error message for missing property value
  src/aggregate/expr/expression.c
  tests/pytests/test_aggregate.py
  tests/pytests/test_missing.py
Labels: backport 2.10

#4751 Cleaning reducers - [MOD-7251]
  coord/src/dist_aggregate.c
  src/aggregate/group_by.c
  src/aggregate/reducer.h
  src/aggregate/reducers/count_distinct.c
  src/aggregate/reducers/deviation.c
  src/aggregate/reducers/first_value.c
  src/aggregate/reducers/minmax.c
  src/aggregate/reducers/random_sample.c
  src/aggregate/reducers/sum.c
  src/aggregate/reducers/to_list.c
  src/value.c
  src/value.h
  tests/cpptests/test_cpp_rlookup.cpp
Labels: backport 2.8, backport 2.10

#4776 Release flow improvement - [MOD-7287]
  .github/workflows/event-deploy-snapshots.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/event-release.yml
  .github/workflows/task-check-docs.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4785 Fix M1 artifact name
  sbin/pack.sh
Labels: backport 2.6

#4784 Fix fail fast on snapshot build workflow
  .github/workflows/flow-build-artifacts.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4771 Fix crucial simple string misuse - [MOD-7258]
  coord/src/rmr/rmr.c
  src/aggregate/aggregate_exec.c
  src/aggregate/expr/expression.c
  src/debug_commands.c
  src/index.c
  src/info/field_spec_info.c
  src/info/index_error.c
  src/info_command.c
  src/module.c
  src/module.h
  src/profile.c
  src/reply.c
  src/reply.h
  src/reply_macros.h
  tests/pytests/common.py
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4778 MOD-7241: Support empty string in fuzzy search
  src/geo_index.c
  src/index.c
  src/index.h
  src/numeric_index.c
  src/query.c
  src/rs_geo.c
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_empty.py
Labels: backport 2.10

#4624 [Feature] Runtime MT Configurations
  coord/src/config.c
  coord/src/config.h
  coord/src/debug_command_names.h
  coord/src/debug_commands.c
  coord/src/debug_commands.h
  coord/src/module.c
  coord/src/rmr/cluster.c
  coord/src/rmr/cluster.h
  coord/src/rmr/conn.c
  coord/src/rmr/conn.h
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/config.c
  src/config.h
  src/cursor.c
  src/cursor.h
  src/debug_commands.c
  src/debug_commands.h
  src/module-init/module-init.c
  src/module.c
  src/notifications.c
  src/result_processor.c
  src/result_processor.h
  src/rlookup.h
  src/spec.c
  src/util/config_macros.h
  src/util/workers.c
  src/util/workers.h
  tests/cpptests/redismock/internal.h
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/test_cpp_config.cpp
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_async.py
  tests/pytests/test_config.py
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_multithread.py
  tests/pytests/test_rdb_compatibility.py
  tests/pytests/test_short_read.py
  tests/pytests/test_vecsim.py
Labels: backport 2.10

#4792 [2.8] Fix crucial simple string misuse - [MOD-7258]
  coord/src/rmr/rmr.c
  src/aggregate/aggregate_exec.c
  src/aggregate/expr/expression.c
  src/debug_commands.c
  src/index.c
  src/info/field_spec_info.c
  src/info/index_error.c
  src/info_command.c
  src/module.c
  src/module.h
  src/profile.c
  src/reply.c
  src/reply.h
  src/reply_macros.h
  tests/pytests/common.py
  tests/pytests/test_issues.py
Labels: bug

#4793 [2.6] Fix crucial simple string misuse - [MOD-7258]
  coord/src/rmr/rmr.c
  src/aggregate/expr/expression.c
  src/debug_commads.c
  src/info_command.c
  src/module.c
  src/profile.c
  src/reply_macros.h
  tests/pytests/common.py
  tests/pytests/test_issues.py
Labels: bug

#4798 Fix test flakiness testRDBCompatibility_vecsim
  tests/pytests/test_rdb_compatibility.py
Labels: backport 2.10

#4777 [MOD-7010] Return None when key epires during query
  src/aggregate/aggregate_exec.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/test_expire.py
  tests/pytests/test_replicate.py
Labels: breakingchange, backport 2.8, backport 2.10

#4728 MOD-7302: Fix numeric range syntax parser/v2
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test.py
  tests/pytests/test_dialect.py
Labels: backport 2.10

#4772 MOD-7299: Exact TAG using double quotes
  CMakeLists.txt
  Makefile
  coord/src/info_command.c
  src/config.h
  src/query.c
  src/query.h
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.h
  src/query_parser/v2/parser.y
  src/query_parser/v3/Makefile
  src/query_parser/v3/lexer.c
  src/query_parser/v3/lexer.rl
  src/query_parser/v3/parser.c
  src/query_parser/v3/parser.h
  src/query_parser/v3/parser.y
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_aggregate_params.py
  tests/pytests/test_dialect.py
  tests/pytests/test_json.py
  tests/pytests/test_numbers.py
  tests/pytests/test_parser.py
  tests/pytests/test_resp3.py
  tests/pytests/test_search_params.py
  tests/pytests/test_tags.py
Labels: backport 2.10

#4797 MOD-7307: Add empty indexing validation
  src/query.c
  src/query.h
  src/query_node.h
  src/search_options.h
  src/spec.c
  src/spec.h
  tests/pytests/test_debug_commands.py
  tests/pytests/test_empty.py
Labels: backport 2.10

#4806 Fix workers debug command
  src/debug_commands.c
Labels: backport 2.10

#4811 dummy change
  .github/workflows/event-merge-to-queue.yml
Labels: backport guyav-target_2.10, backport guyav-target_2.4

#4817 attempt PAT
  .github/workflows/task-backport_pr.yml
Labels: backport guyav-target_2.10, backport guyav-target_2.4

#4820 Remove lexer debug printf
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
Labels: backport 2.10

#4823 Clear flags of SearchResult
  src/result_processor.c
  tests/pytests/test_expire.py
Labels: backport 2.8, backport 2.10

#4825 [2.8] Clear flags of SearchResult
  src/result_processor.c
  tests/pytests/test_expire.py
Labels: bug
