Repository RediSearch/RediSearch, pull requests merged in 2024-11, with the labels that each got.

#5145 Add a counter of total query execution time - [MOD-7961]
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/coord/dist_aggregate.c
  src/default_gc.h
  src/global_stats.c
  src/global_stats.h
  src/module-init/module-init.c
  src/module.c
  src/spec.h
  tests/pytests/common.py
  tests/pytests/test_info_modules.py
Labels: backport 2.10, backport 8.0

#5139 [MOD-8034] expose indexing failures to INFO modules
  src/document.c
  src/field_spec.c
  src/field_spec.h
  src/global_stats.c
  src/global_stats.h
  src/indexer.c
  src/info_command.h
  src/module-init/module-init.c
  src/redisearch_api.c
  src/spec.c
  src/spec.h
  tests/pytests/test_index_error.py
  tests/pytests/test_info_modules.py
Labels: backport 2.10, backport 8.0

#5154 Update Macos runners to 13
  .github/workflows/flow-macos.yml
Labels: backport 2.8, backport 2.6

#5162 Send `SCORER` to the shards with `FT.AGGREGATE` on cluster mode - [MOD-8060]
  src/coord/dist_aggregate.c
  tests/pytests/test_scorers.py
Labels: bug, backport 2.10, backport 8.0

#5137 MOD-8009: Allow Users To Configure Cursor Index Limitation Through Global Config
  src/config.c
  src/config.h
  src/coord/dist_aggregate.c
  src/coord/rmr/chan.c
  src/coord/rmr/chan.h
  src/coord/rmr/rmr.c
  src/coord/rmr/rmr.h
  src/cursor.c
  src/cursor.h
  src/spec.c
  src/spec.h
  src/util/misc.c
  src/util/misc.h
  tests/ctests/coord_tests/test_chan.c
  tests/ctests/test_error_parsing.c
  tests/pytests/test_config.py
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5151 Add VecSim related metrics - [MOD-7967]
  src/global_stats.c
  src/global_stats.h
  src/info_command.h
  src/module-init/module-init.c
  src/redisearch_api.c
  src/spec.c
  src/spec.h
  tests/pytests/test_info_modules.py
Labels: backport 2.10, backport 8.0

#5134 MOD-8010: Print Step Summary In Workflow On Failure
  .github/workflows/task-test.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5178 Improve usage of RedisModuleCtx
  src/fork_gc.c
  src/indexer.c
  src/module.c
  src/rules.c
  src/spec.c
  src/vector_index.c
Labels: backport 2.10, backport 8.0

#5186 Performance improvement in indexBulkFields - [MOD-8093]
  src/debug_commands.c
  src/document.c
  src/fork_gc.c
  src/geometry_index.c
  src/geometry_index.h
  src/indexer.c
  src/indexer.h
  src/info_command.c
  src/inverted_index.c
  src/module.c
  src/numeric_index.c
  src/numeric_index.h
  src/query.c
  src/redis_index.c
  src/redis_index.h
  src/spec.c
  src/spell_check.c
  src/tag_index.c
  src/tag_index.h
  tests/cpptests/test_cpp_forkgc.cpp
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5171 MOD-8050 MOD-8052: Add ACL username config param
  src/config.h
  src/coord/config.c
  src/coord/config.h
  src/coord/rmr/conn.c
  src/coord/rmr/endpoint.c
  src/coord/rmr/endpoint.h
  src/coord/rmr/redis_cluster.c
  src/module.c
  tests/ctests/coord_tests/test_cluster.c
  tests/pytests/test_config.py
Labels: backport 8.0

#5184 MOD-8080, MOD-8055: Fix crash on error handling, Add OSS ACL validation for FT.SUG* commands
  src/commands.h
  src/module.c
  tests/pytests/test_acl.py
  tests/pytests/test_issues.py
  tests/pytests/test_suggest.py
Labels: backport 8.0

#5193 [2.6] Performance improvement in indexBulkFields - [MOD-8093]
  src/debug_commads.c
  src/document.c
  src/fork_gc.c
  src/indexer.c
  src/indexer.h
  src/inverted_index.c
  src/module.c
  src/numeric_index.c
  src/numeric_index.h
  src/query.c
  src/redis_index.c
  src/redis_index.h
  src/spec.c
  src/spell_check.c
  src/tag_index.c
  src/tag_index.h
  tests/cpptests/test_cpp_forkgc.cpp
Labels: bug

#5123 MOD-7872: Add Types To Hide User Input
  src/obfuscation/hidden.c
  src/obfuscation/hidden.h
  tests/cpptests/redismock/internal.h
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/test_cpp_hidden.cpp
Labels: backport 8.0

#5185 Fix Numeric Tree Balance - [MOD-8081, MOD-8082]
  src/debug_commands.c
  src/numeric_index.c
  src/numeric_index.h
  tests/pytests/test_numbers.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5190 [8.0] Performance improvement in indexBulkFields - [MOD-8093]
  src/debug_commands.c
  src/document.c
  src/fork_gc.c
  src/geometry_index.c
  src/geometry_index.h
  src/indexer.c
  src/indexer.h
  src/info_command.c
  src/inverted_index.c
  src/module.c
  src/numeric_index.c
  src/numeric_index.h
  src/query.c
  src/redis_index.c
  src/redis_index.h
  src/spec.c
  src/spell_check.c
  src/tag_index.c
  src/tag_index.h
  tests/cpptests/test_cpp_forkgc.cpp
Labels: bug

#5200 [2.8] Fix Numeric Tree Balance - [MOD-8081, MOD-8082]
  src/debug_commands.c
  src/numeric_index.c
  src/numeric_index.h
  tests/pytests/test_numbers.py
Labels: bug

#5199 [2.10] Fix Numeric Tree Balance - [MOD-8081, MOD-8082]
  src/debug_commands.c
  src/numeric_index.c
  src/numeric_index.h
  tests/pytests/test_numbers.py
Labels: bug

#5150 [MOD-8035] Add field index error for JSON field indexing failures
  src/document_basic.c
  tests/pytests/test_index_error.py
  tests/pytests/test_info_modules.py
Labels: backport 2.8, backport 2.10, backport 8.0

#5183 Add global marked deleted to stats [MOD-6053]
  src/fork_gc.c
  src/global_stats.c
  src/global_stats.h
  src/module-init/module-init.c
  tests/cpptests/test_cpp_forkgc.cpp
  tests/pytests/test_info_modules.py
Labels: backport 2.10, backport 8.0

#5206 MOD-8102: Fix CMake setting of cluster build type
  CMakeLists.txt
  src/commands.h
  src/module.c
Labels: backport 8.0

#5218 Disable RLTest progress bar
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5224 Cleanup for the trimming tree logic
  src/numeric_index.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5204 MOD-8097, MOD-8114 Fix memory counting
  src/debug_commands.c
  src/document.c
  src/fork_gc.c
  src/inverted_index.h
  src/numeric_index.c
  src/numeric_index.h
  src/redis_index.h
  src/redisearch_api.c
  src/spec.c
  src/spec.h
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/index_utils.cpp
  tests/cpptests/index_utils.h
  tests/cpptests/test_cpp_extensions.cpp
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_query.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_stats.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5223 MOD-8062: Hide internal commands in new ACL category for RediSearch internal commands
  src/module.c
  src/module.h
  tests/pytests/test_acl.py
Labels: backport 8.0

#5216 Improve query parsing - [MOD-7794, MOD-7764]
  src/aggregate/aggregate_request.c
  src/debug_commands.c
  src/document.c
  src/fork_gc.c
  src/geo_index.c
  src/geo_index.h
  src/geometry_index.c
  src/geometry_index.h
  src/module.c
  src/numeric_filter.c
  src/numeric_filter.h
  src/numeric_index.c
  src/optimizer_reader.c
  src/query.c
  src/query.h
  src/query_internal.h
  src/query_node.h
  src/query_optimizer.c
  src/query_param.c
  src/query_parser/tokenizer.h
  src/query_parser/v1/lexer.c
  src/query_parser/v1/lexer.rl
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/redisearch_api.c
  src/rs_geo.c
  src/search_options.h
  src/spec.c
  src/spec.h
  src/vector_index.c
  src/vector_index.h
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test.py
  tests/pytests/test_config.py
  tests/pytests/test_dialect.py
  tests/pytests/test_empty.py
  tests/pytests/test_issues.py
  tests/pytests/test_json_multi_text.py
  tests/pytests/test_missing.py
  tests/pytests/test_search_params.py
  tests/pytests/test_tags.py
  tests/pytests/test_vecsim.py
Labels: backport 8.0, breaking change

#5229 [MOD-8125] Create inverted index in write operations only
  src/debug_commands.c
  src/document.c
  src/fork_gc.c
  src/geometry_index.c
  src/geometry_index.h
  src/indexer.c
  src/info_command.c
  src/module.c
  src/query.c
  src/spec.c
  src/tag_index.c
  src/tag_index.h
  src/vector_index.c
  src/vector_index.h
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_tagindex.cpp
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_common.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_index.py
  tests/pytests/test_json_multi_numeric.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5251 [8.0] Improve query parsing - [MOD-7794, MOD-7764] (#5216)
  src/aggregate/aggregate_request.c
  src/debug_commands.c
  src/document.c
  src/fork_gc.c
  src/geo_index.c
  src/geo_index.h
  src/geometry_index.c
  src/geometry_index.h
  src/module.c
  src/numeric_filter.c
  src/numeric_filter.h
  src/numeric_index.c
  src/optimizer_reader.c
  src/query.c
  src/query.h
  src/query_internal.h
  src/query_node.h
  src/query_optimizer.c
  src/query_param.c
  src/query_parser/tokenizer.h
  src/query_parser/v1/lexer.c
  src/query_parser/v1/lexer.rl
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/redisearch_api.c
  src/rs_geo.c
  src/search_options.h
  src/spec.c
  src/spec.h
  src/vector_index.c
  src/vector_index.h
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test.py
  tests/pytests/test_config.py
  tests/pytests/test_dialect.py
  tests/pytests/test_empty.py
  tests/pytests/test_issues.py
  tests/pytests/test_json_multi_text.py
  tests/pytests/test_missing.py
  tests/pytests/test_search_params.py
  tests/pytests/test_tags.py
  tests/pytests/test_vecsim.py
Labels: breaking change

#5231 MOD-7915: Delete empty spellcheck dictionaries
  src/dictionary.c
  src/dictionary.h
  tests/pytests/test_spell_check.py
Labels: breakingchange, backport 8.0

#5253 [MOD-8152] rename and move new metrics
  src/global_stats.c
  src/global_stats.h
  src/module-init/module-init.c
  tests/pytests/test_info_modules.py
Labels: backport 2.10, backport 8.0

#5239 MOD-8054: Validate index prefixes
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/concurrent_ctx.c
  src/concurrent_ctx.h
  src/coord/dist_aggregate.c
  src/coord/rmr/command.c
  src/debug_commands.c
  src/document_add.c
  src/info_command.c
  src/module.c
  src/query_error.h
  src/redis_index.c
  src/spec.c
  src/spec.h
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_config.py
  tests/pytests/test_issues.py
Labels: backport 8.0

#5270 [2.6] Fix MRIterator ownership mechanism - [MOD-8108]
  coord/src/dist_aggregate.c
  coord/src/rmr/chan.c
  coord/src/rmr/chan.h
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  coord/src/rmr/rq.c
  coord/src/rmr/test/test_chan.c
  src/cursor.c
  src/cursor.h
  src/spec.c
  tests/pytests/test_cursors.py
Labels: bug

#5269 [2.8] Fix MRIterator ownership mechanism - [MOD-8108]
  coord/src/dist_aggregate.c
  coord/src/rmr/chan.c
  coord/src/rmr/chan.h
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  coord/src/rmr/rq.c
  coord/src/rmr/test/test_chan.c
  src/cursor.c
  src/cursor.h
  src/spec.c
  tests/pytests/test_cursors.py
Labels: bug
