Repository RediSearch/RediSearch, pull requests merged in 2024-12, with the labels that each got.

#5277 Fix Tag OnReopen Callback - [MOD-8011]
  src/tag_index.c
  tests/pytests/test_tags.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5276 Fix missing expansions in text queries - [MOD-8142]
  src/query.c
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
  tests/pytests/test_scorers.py
  tests/pytests/test_vecsim.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5287 [2.8] Fix missing expansions in text queries - [MOD-8142]
  src/query.c
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
  tests/pytests/test_scorers.py
  tests/pytests/test_vecsim.py
Labels: bug

#5278 MOD-8188: Fix OnReopen Comments
  src/inverted_index.c
  src/tag_index.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5274 [MOD-7949] Avoid lazy expire upon scan keys in background
  src/document_basic.c
  src/spec.c
  tests/pytests/test_expire.py
Labels: backport 2.8, backport 2.10, backport 8.0

#5273 Remove assertion in optimizer
  src/optimizer_reader.c
Labels: bug, backport 2.8, backport 2.10, backport 8.0

#5286 [2.6] Fix missing expansions in text queries - [MOD-8142]
  src/index.c
  src/query.c
  tests/pytests/test.py
  tests/pytests/test_issues.py
  tests/pytests/test_parser.py
  tests/pytests/test_tags.py
  tests/pytests/test_vecsim.py
Labels: bug

#5296 [2.8] Remove assertion in optimizer
  src/optimizer_reader.c
Labels: bug

#5295 Fix long PREFIX/SUFFIX/INFIX/WILDCARD queries - [MOD-7882]
  src/query.c
  src/trie/rune_util.c
  src/trie/rune_util.h
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5302 [2.6] Fix long PREFIX/SUFFIX/INFIX/WILDCARD queries - [MOD-7882]
  src/query.c
  src/trie/rune_util.c
  src/trie/rune_util.h
  tests/pytests/test_issues.py
Labels: bug

#5304 Fix a flakiness in testCursorOnCoordinator - [MOD-8016]
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5310 MOD-8172: Fix CI for platforms that don't support Node.js > 16
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-get-linux-configurations.yml
  .github/workflows/task-test.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5316 [2.8] Fix Sorting Vector - [MOD-6783]
  src/doc_table.c
  src/document.c
  src/field_spec.c
  src/field_spec.h
  src/redisearch_api.c
  src/sortable.c
  src/sortable.h
  src/spec.c
  src/spec.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_issues.py
Labels: bug

#5313 [8.0] Fix Sorting Vector - [MOD-6783]
  src/doc_table.c
  src/document.c
  src/field_spec.c
  src/field_spec.h
  src/redisearch_api.c
  src/sortable.c
  src/sortable.h
  src/spec.c
  src/spec.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_issues.py
Labels: bug

#5315 [2.6] Fix Sorting Vector - [MOD-6783]
  src/doc_table.c
  src/document.c
  src/field_spec.c
  src/field_spec.h
  src/redisearch_api.c
  src/sortable.c
  src/sortable.h
  src/spec.c
  src/spec.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/common.py
  tests/pytests/test_issues.py
Labels: bug

#5325 Fix redis checkout
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
Labels: backport 8.0

#5324 [MOD-8115] Free spec resources in the main thread
  tests/cpptests/common.cpp
  tests/cpptests/index_utils.cpp
  tests/cpptests/test_cpp_forkgc.cpp
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5332 MOD-8172: Fix CI checkout
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
Labels: backport 2.10, backport 8.0

#5319 MOD-8053: Validate ACL key permissions for RediSearch commands
  src/module.c
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_acl.py
  tests/pytests/test_async.py
  tests/pytests/test_cursors.py
  tests/pytests/test_issues.py
  tests/pytests/test_profile.py
  tests/pytests/test_spell_check.py
  tests/pytests/test_synonyms.py
Labels: backport 8.0, breaking change

#5342 MOD-8172: Fix redis ref in CI
  .github/workflows/task-test.yml
Labels: backport 2.6, backport 8.0

#5329 [MOD-8039] Reorganize stats files
  src/aggregate/aggregate_exec.c
  src/config.c
  src/field_spec.c
  src/fork_gc.c
  src/global_stats.c
  src/index.c
  src/info/global_stats.c
  src/info/global_stats.h
  src/info/indexes_info.c
  src/info/indexes_info.h
  src/info/info_command.c
  src/info/info_command.h
  src/info/info_redis.c
  src/info/info_redis.h
  src/module-init/module-init.c
  src/module.c
  src/profile.c
  src/profile.h
  src/redisearch_api.c
  src/redisearch_api.h
  src/spec.c
  src/util/units.h
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_llapi.cpp
Labels: backport 2.10, backport 8.0

#5348 Improve text indexing performance - [MOD-8249]
  src/buffer.c
  src/document.c
  src/tokenize.c
  src/tokenize.h
  src/tokenize_cn.c
  src/varint.c
Labels: bug, action:run-benchmark, backport 2.10, backport 8.0

#5354 Improve counting active writes - [MOD-8151]
  src/info/indexes_info.c
  src/info/indexes_info.h
  tests/pytests/test_info_modules.py
Labels: bug, backport 2.10, backport 8.0

#5350 Improve SkipToBlock logic - [MOD-8255]
  src/inverted_index.c
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5369 [2.8] Improve SkipToBlock logic - [MOD-8255]
  src/inverted_index.c
Labels: bug

#5370 [2.10] Improve SkipToBlock logic - [MOD-8255]
  src/inverted_index.c
Labels: bug

#5368 [2.6] Improve SkipToBlock logic - [MOD-8255]
  src/inverted_index.c
Labels: bug

#5364 Improve "Raw doc id" encoding - [MOD-8255]
  src/inverted_index.c
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5376 Fix macos artifact build
  .github/workflows/flow-build-artifacts.yml
Labels: backport 2.8, backport 2.6

#5049 Refactor the Numeric Tree to use HyperLogLogs - [MOD-7966, MOD-8116]
  src/aggregate/reducers/count_distinct.c
  src/debug_commands.c
  src/fork_gc.c
  src/hll/hll.c
  src/hll/hll.h
  src/inverted_index.c
  src/inverted_index.h
  src/numeric_filter.c
  src/numeric_filter.h
  src/numeric_index.c
  src/numeric_index.h
  src/optimizer_reader.c
  src/query_param.c
  src/util/heap_doubles.c
  src/util/heap_doubles.h
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/cpptests/test_cpp_utils.cpp
  tests/pytests/test_debug_commands.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_numbers.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_stats.py
Labels: backport 8.0

#5297 MOD-6058: Circular Buffer
  src/util/circular_buffer.c
  src/util/circular_buffer.h
  src/util/likely.h
  tests/cpptests/test_cpp_arr.cpp
  tests/cpptests/test_cpp_circularBuffer.cpp
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5390 [2.6] Fixes for inverted indexes encoding - [MOD-8248]
  src/doc_table.c
  src/doc_table.h
  src/fork_gc.c
  src/forward_index.c
  src/index_iterator.h
  src/inverted_index.c
  src/inverted_index.h
  src/numeric_index.c
  src/profile.c
  src/qint.c
  src/qint.h
  src/redisearch.h
  src/spec.c
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/ctests/test_qint.c
Labels: bug

#5389 [2.8] Fixes for inverted indexes encoding - [MOD-8248]
  src/doc_table.c
  src/doc_table.h
  src/fork_gc.c
  src/forward_index.c
  src/index_iterator.h
  src/inverted_index.c
  src/inverted_index.h
  src/numeric_index.c
  src/profile.c
  src/qint.c
  src/qint.h
  src/redisearch.h
  src/spec.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/ctests/test_qint.c
  tests/pytests/common.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_stats.py
Labels: bug

#5388 [2.10] Fixes for inverted indexes encoding - [MOD-8248]
  src/doc_table.c
  src/doc_table.h
  src/fork_gc.c
  src/forward_index.c
  src/index_iterator.h
  src/inverted_index.c
  src/inverted_index.h
  src/numeric_index.c
  src/profile.c
  src/qint.c
  src/qint.h
  src/redisearch.h
  src/spec.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/ctests/test_qint.c
  tests/pytests/common.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_stats.py
Labels: bug

#5122 MOD-7915: Implement aux_save2
  src/dictionary.c
  src/spec.c
  tests/pytests/common.py
  tests/pytests/test_aux_save2.py
  tests/pytests/test_rdb_compatibility.py
Labels: backport 8.0

#5398 MOD-8053: Fix leak
  src/module.c
Labels: backport 8.0

#5386 MOD-8192: Optimize OPTIONAL iterator with existing-index
  src/index.c
  src/index.h
  src/inverted_index.c
  src/query.c
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test.py
  tests/pytests/test_existing.py
  tests/pytests/test_issues.py
  tests/pytests/test_scorers.py
Labels: backport 8.0

#5396 MOD-8393: Refactor python test to use fstring
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_aof.py
  tests/pytests/test_cursors.py
  tests/pytests/test_dialect.py
  tests/pytests/test_ext.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_fuzz.py
  tests/pytests/test_fuzzy.py
  tests/pytests/test_geo.py
  tests/pytests/test_issues.py
  tests/pytests/test_json.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_json_multi_tag.py
  tests/pytests/test_json_multi_text.py
  tests/pytests/test_numbers.py
  tests/pytests/test_rof.py
  tests/pytests/test_scorers.py
  tests/pytests/test_short_read.py
  tests/pytests/test_sortby.py
  tests/pytests/test_stats.py
  tests/pytests/test_tags.py
  tests/pytests/test_vecsim.py
Labels: backport 8.0
