Repository RediSearch/RediSearch, pull requests merged in 2024-04, with the labels that each got.

#4562 Fix flaky test (timeout)
  src/aggregate/aggregate_exec.c
  tests/pytests/test.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4561 MOD-6846: Enhance INFO response
  src/aggregate/aggregate_exec.c
  src/cursor.c
  src/cursor.h
  src/fork_gc.h
  src/info_command.c
  src/info_command.h
  src/module-init/module-init.c
  src/redisearch_api.c
  src/redisearch_api.h
  src/spec.c
  tests/pytests/test_info.py
  tests/pytests/test_info_modules.py
Labels: backport 2.10

#4576 Validate version branch upon release
  .github/workflows/event-release.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4573 fix runtests.sh
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6, backport 2.10

#4572 Align FT.PROFILE response - [MOD-6816]
  coord/src/dist_aggregate.c
  coord/src/dist_profile.h
  coord/src/module.c
  coord/src/rmr/command.c
  coord/src/rmr/command.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/index.c
  src/profile.c
  src/profile.h
  src/reply.c
  src/reply.h
  tests/pytests/test.py
  tests/pytests/test_geo.py
  tests/pytests/test_issues.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
  tests/pytests/test_wildcard.py
Labels: breakingchange

#4590 MOD-6846: Replace average cycle time with total time in Redis `INFO`
  src/fork_gc.h
  src/module-init/module-init.c
  src/redisearch_api.c
  tests/pytests/test_info_modules.py
Labels: backport 2.10

#4554 MOD-5902: Report memory of the TAG TrieMaps and TEXT Tries
  coord/src/info_command.c
  src/info_command.c
  src/query.c
  src/redisearch_api.c
  src/reply.c
  src/spec.c
  src/spec.h
  src/suffix.c
  src/suffix.h
  src/tag_index.c
  src/tag_index.h
  src/trie/trie.h
  src/trie/trie_type.h
  tests/cpptests/json.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test_info.py
  tests/pytests/test_resp3.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4510 MOD-6761: Add validation for cursor read `COUNT` argument
  src/aggregate/aggregate_exec.c
  tests/pytests/test_cursors.py
Labels: pr:break, breakingchange

#4589 MOD-6873: Support new EMPTY syntax for TAG
  src/query.c
  src/query_node.h
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.h
  src/query_parser/v2/parser.y
  src/spec.h
  tests/pytests/test_short_read.py
  tests/pytests/test_tags.py
Labels: backport 2.10

#4587 MOD-5739: Configurable minimum length of word to stem
  src/config.c
  src/config.h
  src/module-init/module-init.c
  src/tokenize.c
  tests/pytests/test_config.py
  tests/pytests/test_stemmer.py
Labels: backport 2.10

#4455 MOD-5740: Default querying language
  src/aggregate/aggregate_request.c
  src/language.h
  src/redisearch_api.c
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test_json.py
  tests/pytests/test_language.py
Labels: backport 2.10

#4567 Add 'compatible redis version' field to module.json [MOD-6943]
  coord/pack/ramp.yml
  pack/ramp-light.yml
  pack/ramp.yml
Labels: backport 2.10

#4605 MOD-6960: Get right RedisJSON artifact for macOS Sonoma
  sbin/get-redisjson
Labels: backport 2.8, backport 2.6, backport 2.10

#4610 MOD-6975: Remove test flakiness
  tests/pytests/test_info_modules.py
Labels: backport 2.10
