Repository RediSearch/RediSearch, pull requests merged in 2024-07, with the labels that each got.

#4832 Fix amazonlinux CI installation
  .install/amazon_linux_2.sh
Labels: backport 2.8, backport 2.6, backport 2.10

#4831 Backport - assign the PR owner to review the backport PRs
  .github/workflows/task-backport_pr.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4843 GHA better node16/20 handle
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4842 Fix ARM macOS version to 13
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-macos.yml
Labels: backport 2.8, backport 2.6

#4636 MOD-7025: Avoid expansion/stemming from numeric values
  src/query.c
  src/query_param.c
  src/query_param.h
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_dialect.py
  tests/pytests/test_fuzzy.py
  tests/pytests/test_search_params.py
  tests/pytests/test_synonyms.py
Labels: backport 2.8, backport 2.10

#4853 [MOD-7341] Upgrade gcc
  .install/rocky_linux_8.sh
  .install/ubuntu_22.04.sh
Labels: backport 2.10

#4827 Expose scores to pipeline - [MOD-7190]
  coord/src/dist_aggregate.c
  src/aggregate/aggregate.h
  src/aggregate/aggregate_request.c
  src/result_processor.c
  src/result_processor.h
  src/rlookup.h
  src/search_options.h
  tests/pytests/test_scorers.py
Labels: backport 2.10

#4856 MOD-7355: Remove unnecessary assignments
  coord/src/cluster_spell_check.c
  coord/src/dist_aggregate.c
  coord/src/dist_plan.cpp
  coord/src/info_command.c
  coord/src/module.c
  deps/triemap/triemap.c
  src/aggregate/aggregate_plan.c
  src/aggregate/aggregate_request.c
  src/aggregate/expr/exprast.c
  src/concurrent_ctx.c
  src/document_basic.c
  src/fork_gc.c
  src/hybrid_reader.c
  src/module.c
  src/numeric_index.c
  src/query.c
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/rules.c
  src/rwlock.c
  src/spec.c
  src/spell_check.c
  src/synonym_map.c
  src/tag_index.c
  src/util/arr.h
  src/value.c
  src/vector_index.c
  tests/cpptests/test_cpp_arr.cpp
Labels: backport 2.8, backport 2.10

#4860 MOD-7415: Add coverage for missing indexing GC
  tests/pytests/requirements.txt
  tests/pytests/test_missing.py
Labels: backport 2.10

#4871 Fix flaky test
  tests/pytests/test_missing.py
Labels: backport 2.10

#4873 Fix env overriding
  tests/pytests/test_missing.py
Labels: backport 2.10

#4864 Build oss with coordinator - [MOD-7159]
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
  Makefile
  coord/CMakeLists.txt
  coord/src/module.c
  coord/src/rmr/rmr.c
  pack/ramp.yml
  sbin/unit-tests
  tests/pytests/common.py
  tests/pytests/includes.py
  tests/pytests/runtests.sh
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_config.py
  tests/pytests/test_contains.py
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_dialect.py
  tests/pytests/test_expire.py
  tests/pytests/test_ext.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_gc.py
  tests/pytests/test_geo.py
  tests/pytests/test_geometry_flat.py
  tests/pytests/test_geometry_sphere.py
  tests/pytests/test_issues.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_json_multi_text.py
  tests/pytests/test_missing.py
  tests/pytests/test_multithread.py
  tests/pytests/test_numbers.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_rdb_compatibility.py
  tests/pytests/test_resp3.py
  tests/pytests/test_short_read.py
  tests/pytests/test_stats.py
  tests/pytests/test_tags.py
  tests/pytests/test_vecsim.py
  tests/pytests/test_wildcard.py
Labels: breakingchange

#4877 Add team leaders to review auto version bump PRs
  .github/workflows/event-release.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4889 MOD-7459 skip json tests when no json module is found
  tests/pytests/common.py
  tests/pytests/includes.py
  tests/pytests/test.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_empty.py
  tests/pytests/test_expire.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_geometry_flat.py
  tests/pytests/test_geometry_sphere.py
  tests/pytests/test_index_error.py
  tests/pytests/test_issues.py
  tests/pytests/test_json.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_json_multi_tag.py
  tests/pytests/test_json_multi_text.py
  tests/pytests/test_language.py
  tests/pytests/test_missing.py
  tests/pytests/test_resp3.py
  tests/pytests/test_stemmer.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4894 VERBATIM is not passed to the shards on FT.AGGREGATE - [MOD-7463]
  coord/src/dist_aggregate.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10
