Repository RediSearch/RediSearch, pull requests merged in 2024-01, with the labels that each got.

#4289 Fix flakiness in testIndexDropWhileIdle - [MOD-5882]
  tests/pytests/test_cursors.py
Labels: backport 2.8

#4295 Fix timeout flakiness of `testCursorOnCoordinator` - [MOD-6253]
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.6

#4294 Fix migrating slot in test
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6

#4280 [CP 2.8] Enabled SPOT Instance deployments on CI benchmarks
  tests/benchmarks/defaults.yml
  tests/benchmarks/search-aggregate-post-filter-simple.yml
  tests/benchmarks/search-filtering-tag-numeric-filter-pipeline.yml
  tests/benchmarks/search-filtering-tag-numeric.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-fulltext-sortby.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-load.yml
  tests/benchmarks/search-ftsb-10K-multivalue-numeric-json.yml
  tests/benchmarks/search-ftsb-10K-singlevalue-numeric-json.yml
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable@50_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-ftadd-load.yml
  tests/benchmarks/search-ftsb-1M-nyc_taxis-hashes-load.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
  tests/benchmarks/search-geo.yml
  tests/benchmarks/search-high-cardinality-negation-term-baseline.yml
  tests/benchmarks/search-high-cardinality-negation-term-comparison_union_all_other_terms.yml
  tests/benchmarks/search-numeric-optimize.yml
  tests/benchmarks/search-numeric-sortby-desc-optimized.yml
  tests/benchmarks/search-numeric-sortby-desc.yml
  tests/benchmarks/search-numeric-sortby-optimized.yml
  tests/benchmarks/search-numeric-sortby.yml
  tests/benchmarks/search-numeric.yml
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_glove-200-angular_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-arxiv-titles-384-angular-filters-m16-ef-128-fulltext-filter.yml
  tests/benchmarks/vecsim-arxiv-titles-384-angular-filters-m16-ef-128-numeric-filter.yml
  tests/benchmarks/vecsim-arxiv-titles-384-angular-filters-m16-ef-128-tag-filter.yml
Labels: action:run-benchmark

#4297 Fix safe loader limit - [MOD-6385]
  src/result_processor.c
  tests/pytests/test_multithread.py
Labels: c:bug, backport 2.8

#4307 Ephraim unflake clusterset memtracking
  coord/src/search_cluster.c
  tests/pytests/test.py
Labels: backport 2.8, backport 2.6

#4312 Fix `testIndexDropWhileIdleBG` premature drop flakiness - [MOD-6318]
  tests/pytests/test_cursors.py
Labels: backport 2.8

#4264 MOD-6002: Fixes for `FT.PROFILE`'s time reporting
  CMakeLists.txt
  coord/CMakeLists.txt
  deps/rmutil/cxx/CMakeLists.txt
  deps/rmutil/cxx/chrono-clock.cc
  deps/rmutil/cxx/chrono-clock.h
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/index.c
  src/info_command.c
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  src/spec.c
  src/spec.h
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_profile.py
  tests/pytests/test_stats.py
Labels: backport 2.8, backport 2.6

#4306 Remove `union_iterator_heap` test configuration - [MOD-6114]
  tests/pytests/CMakeLists.txt
  tests/pytests/runtests.sh
  tests/pytests/test_issues.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.6

#4253 improve GHA workflows - [MOD-6404]
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/event-release.yml
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/flow-temp.yml
  .github/workflows/task-assign-for-issue.yml
  .github/workflows/task-backport_pr.yml
  .github/workflows/task-check-docs.yml
  .github/workflows/task-get-latest-tag.yml
  .github/workflows/task-test.yml
  .github/workflows/task-website-deploy.yml
  sbin/unit-tests
  tests/pytests/requirements.txt
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6

#4324 MOD-6287: Fix Coordinator folding mechanism
  coord/src/rmr/command.c
  coord/src/rmr/rmr.c
Labels: backport 2.8

#4327 Fix sanitizer warning false leak in vecsim tests [MOD-6229]
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.6

#4330 Skip flaky test
  tests/pytests/test_profile.py
Labels: backport 2.8

#4266 Fix flaky tests of tiered HNSW MT [MOD-6020, MOD-5863]
  deps/thpool/thpool.c
  deps/thpool/thpool.h
  src/debug_commands.c
  src/debug_commands.h
  src/module.c
  src/util/workers.c
  src/util/workers.h
  tests/pytests/common.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_multithread.py
  tests/pytests/test_resp3.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8

#4337 MOD-6420 remove Coordinator_CleanupModule
  coord/CMakeLists.txt
  coord/src/module.c
  coord/src/rmr/redis_cluster.c
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  coord/src/rmr/rq.c
  coord/src/rmr/rq.h
  coord/src/search_cluster.c
  coord/src/search_cluster.h
  src/module.c
  tests/memcheck/asan.supp
  tests/pytests/runtests.sh
  tests/pytests/test_aggregate.py
  tests/pytests/test_cursors.py
  tests/pytests/test_json.py
Labels: backport 2.8, backport 2.6

#4348 Fix TLS test certification generation flakiness - [MOD-6412]
  sbin/gen-test-certs
  tests/pytests/common.py
Labels: backport 2.8, backport 2.6

#4353 MOD-6449 - replace NodeMap internals tries with dictionaries
  coord/src/rmr/cluster.c
  coord/src/rmr/cluster.h
  coord/src/rmr/node.c
  coord/src/rmr/node.h
  coord/src/rmr/node_map.c
  coord/src/rmr/node_map.h
Labels: backport 2.8, backport 2.6

#4355 Fix a Leak in Synonym - [MOD-6490]
  src/synonym_map.c
  tests/pytests/test_synonyms.py
Labels: bug, backport 2.8, backport 2.6

#4354 Reenable replication tests - [MOD-6181]
  src/debug_commands.c
  tests/pytests/common.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_replicate.py
Labels: backport 2.8, backport 2.6

#4359 [2.6] Fix a Leak in Synonym - [MOD-6490]
  src/synonym_map.c
  tests/pytests/test_synonyms.py
Labels: bug

#4360 [2.8] Fix a Leak in Synonym - [MOD-6490]
  src/synonym_map.c
  tests/pytests/test_synonyms.py
Labels: bug

#4356 MOD-6489 replace MRConnManager map trie with dict
  coord/src/rmr/cluster.c
  coord/src/rmr/conn.c
  coord/src/rmr/conn.h
  src/util/dict.c
  src/util/dict.h
  tests/memcheck/asan.supp
Labels: backport 2.8, backport 2.6

#4368 MOD-6382: Fix supposedly flaky test
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
Labels: backport 2.8

#4384 Fix non-existing log levels
  coord/src/rmr/redis_cluster.c
  src/json.c
  src/redis_index.c
  src/spec.c
  src/tag_index.c
Labels: backport 2.8, backport 2.6

#4377 MOD-6438: Add test for coord fix
  coord/src/dist_aggregate.c
  src/debug_commands.c
  tests/pytests/common.py
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
  tests/pytests/test_debug_commands.py
Labels: backport 2.8

#4313 MOD 6431: [GeoShape] memory allocation patterns
  src/geometry/geometry_api.cpp
  src/geometry/query_iterator.cpp
  src/geometry/query_iterator.hpp
  src/geometry/rtree.cpp
  src/geometry/rtree.hpp
  tests/pytests/test_geometry_sphere.py
Labels: backport 2.8

#4388 Tidying up
  src/debug_commands.c
  src/document.c
  src/gc.c
  src/inverted_index.h
  src/module.c
  src/query.c
  src/rdb.c
  src/rules.c
  src/rules.h
  src/spec.c
  src/tag_index.c
  src/tag_index.h
  src/util/references.c
Labels: backport 2.8

#4390 Fix Coordinator's topology parser - [MOD-6543]
  Makefile
  coord/src/rmr/redise.c
  coord/src/rmr/redise_parser/Makefile
  coord/src/rmr/redise_parser/grammar.c
  coord/src/rmr/redise_parser/grammar.h
  coord/src/rmr/redise_parser/grammar.y
  coord/src/rmr/redise_parser/lex.yy.c
  coord/src/rmr/redise_parser/lexer.h
  coord/src/rmr/redise_parser/lexer.l
  coord/src/rmr/redise_parser/template.c.tpl
  src/aggregate/expr/lexer.c
  src/aggregate/expr/parser.c
  src/query_parser/template.c.tpl
  src/query_parser/v1/lexer.c
  src/query_parser/v1/parser.c
  src/query_parser/v2/parser.c
  srcutil/lemon.c
  tests/pytests/test.py
Labels: bug, backport 2.8, backport 2.6

#4392 [2.6] Fix Coordinator's topology parser - [MOD-6543]
  Makefile
  coord/src/rmr/redise.c
  coord/src/rmr/redise_parser/Makefile
  coord/src/rmr/redise_parser/grammar.c
  coord/src/rmr/redise_parser/grammar.h
  coord/src/rmr/redise_parser/grammar.y
  coord/src/rmr/redise_parser/lex.yy.c
  coord/src/rmr/redise_parser/lexer.h
  coord/src/rmr/redise_parser/lexer.l
  coord/src/rmr/redise_parser/template.c.tpl
  src/aggregate/expr/lexer.c
  src/aggregate/expr/parser.c
  src/query_parser/template.c.tpl
  src/query_parser/v1/lexer.c
  src/query_parser/v1/parser.c
  src/query_parser/v2/parser.c
  srcutil/lemon.c
  tests/pytests/test.py
Labels: bug

#4394 Fix `fast_timegm` implementation - [MOD-6549]
  src/aggregate/functions/date.c
  tests/pytests/test_aggregate.py
Labels: bug, backport 2.8, backport 2.6

#4396 [2.6] Fix `fast_timegm` implementation - [MOD-6549]
  src/aggregate/functions/date.c
  tests/pytests/test_aggregate.py
Labels: bug

#4397 [2.8] Fix `fast_timegm` implementation - [MOD-6549]
  src/aggregate/functions/date.c
  tests/pytests/test_aggregate.py
Labels: bug

#4403 Fix unblocking client with no reply on SEARCH cluster mode - [MOD-6557]
  coord/src/module.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6

#4406 [2.8] Fix unblocking client with no reply on SEARCH cluster mode - [MOD-6557]
  coord/src/module.c
  tests/pytests/test_issues.py
Labels: bug

#4407 [2.6] Fix unblocking client with no reply on SEARCH cluster mode - [MOD-6557]
  coord/src/module.c
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
  tests/pytests/test_issues.py
Labels: bug

#4382 [2.8] move ClusterInfoCommand to UV thread - [MOD-6504]
  coord/src/module.c
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
Labels: bug

#4409 Fix topology parser syntax error handling - [MOD-6552, MOD-6543]
  coord/src/rmr/endpoint.c
  coord/src/rmr/redise.c
  coord/src/rmr/redise_parser/grammar.c
  coord/src/rmr/redise_parser/grammar.y
  tests/pytests/test.py
Labels: bug, backport 2.8, backport 2.6

#4383 [2.6] move ClusterInfoCommand to UV thread - [MOD-6504]
  coord/src/module.c
  coord/src/rmr/rmr.c
  coord/src/rmr/rmr.h
Labels: bug
