Repository RediSearch/RediSearch, pull requests merged in 2024-03, with the labels that each got.

#4502 [2.6] Handle MULTI / EXEC and LUA properly - [MOD-6541]
  coord/src/module.c
  tests/pytests/test_issues.py
Labels: bug

#4501 [2.8] Handle MULTI / EXEC and LUA properly - [MOD-6541]
  coord/src/module.c
  tests/pytests/test_issues.py
Labels: bug

#4475 Support empty values indexing for TAGs
  src/doc_table.h
  src/document.c
  src/field_spec.c
  src/field_spec.h
  src/index.c
  src/info_command.c
  src/inverted_index.c
  src/json.c
  src/query.c
  src/spec.c
  src/spec.h
  src/tag_index.c
  src/tag_index.h
  tests/cpptests/test_cpp_tagindex.cpp
  tests/pytests/common.py
  tests/pytests/test_rdb_compatibility.py
  tests/pytests/test_short_read.py
  tests/pytests/test_tags.py
Labels: backport 2.10

#4513 MOD-6597: Fix numeric index deletion
  src/config.c
  src/debug_commands.c
  src/fork_gc.c
  src/inverted_index.c
  src/numeric_index.c
  tests/pytests/test_cursors.py
  tests/pytests/test_numbers.py
Labels: backport 2.8, backport 2.6, backport 2.10

#4490 Fix all `strncmp` unintentional usage - [MOD-6709]
  coord/src/module.c
  coord/src/rmr/redis_cluster.c
  src/aggregate/functions/function.c
  src/aggregate/functions/string.c
  src/config.c
  src/dictionary.c
  src/document_add.c
  src/info/index_error.c
  src/language.c
  src/notifications.c
  src/rlookup.c
  src/rules.c
  src/spec.c
  src/suffix.c
  tests/pytests/test.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4511 MOD-6768: Fix FT.EXPLAIN - it returns additional `}`
  src/query.c
  tests/pytests/test.py
Labels: backport 2.10

#4529 MOD-6831 unintlized memory in RSAddDocumentCtx can cause crash while ingest/load
  src/document.c
Labels: backport 2.8, backport 2.6, backport 2.10

#4542 MOD-6833 Fix timeout in test_short_reads
  tests/pytests/common.py
  tests/pytests/test_short_read.py
Labels: backport 2.8, backport 2.10

#4548 Fix boost installation
  .circleci/config.yml
  .github/workflows/benchmark-flow.yml
  .github/workflows/flow-coverage.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
  .gitignore
  .install/install_boost.sh
  Makefile
Labels: backport 2.8, backport 2.10

#4547 MOD-6768: Fix FT.EXPLAIN - Add GEO test
  src/query.c
  tests/pytests/test.py
Labels: backport 2.10

#4559 MOD-6075 try to build on apple silicon
  .circleci/config.yml
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-macos.yml
  tests/c_utils/CMakeLists.txt
Labels: backport 2.8, backport 2.6, backport 2.10
