Repository RediSearch/RediSearch, pull requests merged in 2024-02, with the labels that each got.

#4416 Replace topology parser - [MOD-6587]
  Makefile
  coord/src/module.c
  coord/src/rmr/cluster.c
  coord/src/rmr/cluster.h
  coord/src/rmr/endpoint.c
  coord/src/rmr/node.h
  coord/src/rmr/redis_cluster.c
  coord/src/rmr/redise.c
  coord/src/rmr/redise_parser/Makefile
  coord/src/rmr/redise_parser/grammar.c
  coord/src/rmr/redise_parser/grammar.h
  coord/src/rmr/redise_parser/grammar.y
  coord/src/rmr/redise_parser/lex.yy.c
  coord/src/rmr/redise_parser/lexer.h
  coord/src/rmr/redise_parser/lexer.l
  coord/src/rmr/redise_parser/parse.c
  coord/src/rmr/redise_parser/parse.h
  coord/src/rmr/redise_parser/parser_ctx.h
  coord/src/rmr/redise_parser/token.h
  coord/src/rmr/test/test_parser.c
  tests/pytests/test.py
Labels: bug, backport 2.8, backport 2.6

#4423 [2.8] Replace topology parser - [MOD-6587]
  Makefile
  coord/src/module.c
  coord/src/rmr/cluster.c
  coord/src/rmr/cluster.h
  coord/src/rmr/endpoint.c
  coord/src/rmr/node.h
  coord/src/rmr/redis_cluster.c
  coord/src/rmr/redise.c
  coord/src/rmr/redise_parser/Makefile
  coord/src/rmr/redise_parser/grammar.c
  coord/src/rmr/redise_parser/grammar.h
  coord/src/rmr/redise_parser/grammar.y
  coord/src/rmr/redise_parser/lex.yy.c
  coord/src/rmr/redise_parser/lexer.h
  coord/src/rmr/redise_parser/lexer.l
  coord/src/rmr/redise_parser/parse.c
  coord/src/rmr/redise_parser/parse.h
  coord/src/rmr/redise_parser/parser_ctx.h
  coord/src/rmr/redise_parser/token.h
  coord/src/rmr/test/test_parser.c
  tests/pytests/test.py
Labels: bug

#4426 MOD-6150 build ci without readies
  .github/workflows/flow-coverage.yml
  .github/workflows/flow-temp.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
  .install/amazon_linux_2.sh
  .install/centos_linux_7.sh
  .install/common_base_linux_mariner_2.0.sh
  .install/common_installations.sh
  .install/debian_gnu_linux_11.sh
  .install/macos.sh
  .install/rocky_linux_8.sh
  .install/rocky_linux_9.sh
  .install/ubuntu_18.04.sh
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  sbin/gen-test-certs
  tests/pytests/requirements.linux.txt
  tests/pytests/requirements.macos.txt
  tests/pytests/requirements.txt
Labels: backport 2.8, backport 2.6

#4424 [2.6] Replace topology parser - [MOD-6587]
  Makefile
  coord/src/module.c
  coord/src/rmr/cluster.c
  coord/src/rmr/cluster.h
  coord/src/rmr/endpoint.c
  coord/src/rmr/node.h
  coord/src/rmr/redis_cluster.c
  coord/src/rmr/redise.c
  coord/src/rmr/redise_parser/Makefile
  coord/src/rmr/redise_parser/grammar.c
  coord/src/rmr/redise_parser/grammar.h
  coord/src/rmr/redise_parser/grammar.y
  coord/src/rmr/redise_parser/lex.yy.c
  coord/src/rmr/redise_parser/lexer.h
  coord/src/rmr/redise_parser/lexer.l
  coord/src/rmr/redise_parser/parse.c
  coord/src/rmr/redise_parser/parse.h
  coord/src/rmr/redise_parser/parser_ctx.h
  coord/src/rmr/redise_parser/token.h
  coord/src/rmr/test/test_parser.c
  tests/pytests/test.py
Labels: bug

#4434 Update common_installations.sh
  .install/common_installations.sh
Labels: backport 2.8

#4438 test_vecsim: higher epsilon for distance calculation error
  tests/pytests/test_vecsim.py
Labels: backport 2.8

#4441 Add tags to EC2 instances - [RED-120031]
  .github/workflows/flow-self-hosted-arm.yml
  .github/workflows/self-hosted.yml.TEMPLATE
Labels: backport 2.8, backport 2.6

#4447 remove macos requirments from system setup as it no longer exists
  sbin/system-setup.py
Labels: backport 2.8, backport 2.6

#4452 Code cleanup
  src/debug_commands.c
  src/document_add.c
  src/info_command.c
  src/module.c
  src/redis_index.c
  src/spec.c
  src/spec.h
Labels: backport 2.8

#4454 split req installation in build atrifcats and insall aws
  .github/workflows/task-build-artifacts.yml
  .install/install_aws.sh
  sbin/upload-artifacts
Labels: backport 2.8, backport 2.6

#4463 Fix `testDelReplicate` flakiness
  tests/pytests/test_replicate.py
Labels: backport 2.8, backport 2.6

#4457 MOD-6644: Fix leak in tag prefix node evaluation
  src/query.c
  tests/pytests/test_tags.py
Labels: backport 2.8, backport 2.6

#4431 Reset sameId variable on rewind
  src/inverted_index.c
Labels: bug, backport 2.8

#3740 added debug logging for freeing and creating a ref manager
  src/util/references.c
Labels: backport 2.8

#4483 Fix bad usage of strncmp
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_vecsim.py
Labels: bug, backport 2.8, backport 2.6

#4482 MOD-6701: Passing more descriptive error messages
  src/geometry/rtree.cpp
  tests/pytests/test_geometry_flat.py
Labels: backport 2.8, backport 2.6

#4496 Fix deadlock in vecsim hybrid query with timeout [MOD-6510, MOD-6244]
  src/hybrid_reader.c
  tests/pytests/test_issues.py
Labels: backport 2.8
