Repository RediSearch/RediSearch, pull requests merged in 2024-05, with the labels that each got.

#4616 [2.6] Fix MOD-6759
  src/aggregate/functions/string.c
Labels: bug

#4630 MOD-6580: Update short-read test to use rdb with EMPTY TEXT\TAG fields
  tests/pytests/test_short_read.py
Labels: backport 2.10

#4604 MOD-6933 MOD-6750 MOD-6749: Lexer consumes some punctuation characters
  CMakeLists.txt
  Makefile
  coord/src/info_command.c
  src/config.h
  src/numeric_filter.c
  src/numeric_filter.h
  src/param.h
  src/query.c
  src/query.h
  src/query_param.c
  src/query_parser/tokenizer.h
  src/query_parser/v3/Makefile
  src/query_parser/v3/lexer.c
  src/query_parser/v3/lexer.rl
  src/query_parser/v3/parser.c
  src/query_parser/v3/parser.h
  src/query_parser/v3/parser.y
  srcutil/make-parser.mk
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_aggregate_params.py
  tests/pytests/test_dialect.py
  tests/pytests/test_numbers.py
  tests/pytests/test_resp3.py
  tests/pytests/test_search_params.py
  tests/pytests/test_tags.py
Labels: backport 2.10

#4218 MOD-5977 MOD-5866: Fix inverted index memory counting
  src/buffer.c
  src/buffer.h
  src/fork_gc.c
  src/inverted_index.c
  src/inverted_index.h
  src/numeric_index.c
  src/numeric_index.h
  src/qint.c
  src/redis_index.c
  src/redisearch.h
  src/spec.h
  src/tag_index.c
  src/tag_index.h
  src/varint.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_tagindex.cpp
  tests/ctests/bench-decoder.c
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
  tests/pytests/test_numbers.py
  tests/pytests/test_stats.py
Labels: action:run-benchmark, backport 2.8, backport 2.10

#4642 Limit the number of worker threads - [MOD-7011]
  src/config.c
  tests/pytests/test_multithread.py
Labels: bug, backport 2.8, backport 2.10

#4629 MOD-1855: Send del command to replicas
  .install/.gitignore
  src/redis_index.c
Labels: bug, backport 2.8, backport 2.6, backport 2.10

#4640 MOD-6846: Fix geoshape stat
  src/fields_global_stats.c
Labels: backport 2.8, backport 2.6, backport 2.10

#4637 MOD-6540: Support EMPTY indexing for TEXT fields (#4622)
  commands.json
  src/doc_table.c
  src/doc_table.h
  src/document.c
  src/document_basic.c
  src/forward_index.c
  src/forward_index.h
  src/fragmenter.c
  src/highlight_processor.c
  src/index.c
  src/index.h
  src/indexer.c
  src/inverted_index.c
  src/json.c
  src/numeric_index.c
  src/numeric_index.h
  src/query.c
  src/query_node.h
  src/query_optimizer.c
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/query_parser/v3/parser.c
  src/query_parser/v3/parser.y
  src/redis_index.c
  src/redisearch.h
  src/rlookup.h
  src/rules.c
  src/spec.c
  src/spec.h
  src/suffix.c
  src/tag_index.c
  src/tokenize.c
  src/tokenize.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_empty.py
  tests/pytests/test_short_read.py
  tests/pytests/test_summarize.py
  tests/pytests/test_tags.py
Labels: action:run-benchmark, backport 2.10

#4433 MOD-5756: Modify FT.SEARCH to avoid unnecessary escaping
  src/query_parser/v3/lexer.c
  src/query_parser/v3/lexer.rl
  src/query_parser/v3/parser.c
  src/query_parser/v3/parser.h
  src/query_parser/v3/parser.y
  tests/cpptests/test_cpp_query.cpp
  tests/pytests/test_aggregate_params.py
  tests/pytests/test_json.py
  tests/pytests/test_tags.py
Labels: backport 2.10

#4675 remove centos7 and ubuntu 18.04
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/task-get-linux-configurations.yml
  .install/centos_linux_7.sh
  .install/ubuntu_18.04.sh
Labels: backport 2.10

#4678 Improve backport flow
  .github/workflows/task-backport_pr.yml
Labels: backport 2.8, backport 2.6, backport 2.10

#4667 Add a retry mechanism to verify_shard_init - [MOD-7139]
  tests/pytests/common.py
  tests/pytests/test_issues.py
Labels: backport 2.10

#4679 MOD-6920: add missing ft.info fields when used inside of a cluster
  coord/src/info_command.c
  tests/pytests/common.py
  tests/pytests/test.py
  tests/pytests/test_resp3.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10
