Repository RediSearch/RediSearch, pull requests merged in 2025-07, with the labels that each got.

#6407 change to redis 8.0
  pack/ramp-community.yml
  pack/ramp-enterprise.yml
  pack/ramp-light.yml
Labels: size:S

#6409 add more specific labels for microbenchmarks
  .github/workflows/benchmark-trigger.yml
Labels: size:S, action:run-rust-micro-benchmark

#6390 MOD-10299: Wrap Common AREQ Members Usage With Functions
  src/aggregate/aggregate.h
  src/aggregate/aggregate_debug.c
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/coord/dist_aggregate.c
  src/coord/dist_plan.cpp
  src/profile.c
  src/query_optimizer.c
  src/result_processor.c
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_distagg.cpp
Labels: size:M, size:L

#6420 inverted_index_bencher: fix test of C version
  src/inverted_index/inverted_index.c
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:S

#6374 Fix lints that will be introduced in Rust 1.88.0
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/buffer/tests/tests.rs
  src/redisearch_rs/c_entrypoint/triemap_ffi/tests/trie.rs
  src/redisearch_rs/ffi/build.rs
  src/redisearch_rs/low_memory_thin_vec/tests/tests.rs
  src/redisearch_rs/qint/tests/qint.rs
  src/redisearch_rs/trie_rs/src/iter/contains.rs
  src/redisearch_rs/trie_rs/src/iter/iter_.rs
  src/redisearch_rs/trie_rs/src/iter/range.rs
  src/redisearch_rs/trie_rs/src/node/metadata.rs
  src/redisearch_rs/varint/tests/varint.rs
  src/redisearch_rs/varint/tests/vector_writer.rs
  src/redisearch_rs/wildcard/src/lib.rs
  src/redisearch_rs/wildcard/tests/integration/fmt.rs
Labels: size:S, size:M

#6413 MOD-10301: Add index locking/freeing mechanism for index-space consistency
  src/aggregate/aggregate_request.c
  src/result_processor.c
  src/result_processor.h
  src/spec.c
  tests/cpptests/test_cpp_rpdepleter.cpp
Labels: size:S, size:M

#6411 Fix missing profile info - [MOD-6327]
  src/coord/dist_aggregate.c
  src/coord/rmr/reply.c
  src/coord/rmr/reply.h
  src/module.c
  tests/pytests/test_issues.py
  tests/pytests/test_profile.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M, backport 8.2

#6417 [2.10] Fix FieldSpec Cleanup on failed RDB load - [MOD-10307]
  .gitignore
  build.sh
  src/spec.c
  tests/pytests/test_short_read.py
Labels: bug

#6438 Simplify legacy RDB support - [MOD-10352]
  src/legacy_types.c
  src/legacy_types.h
  src/module.c
  src/numeric_index.c
  src/numeric_index.h
  src/redis_index.c
  src/redis_index.h
  src/spec.c
  src/tag_index.c
  src/tag_index.h
  src/trie/trie_type.c
  src/trie/trie_type.h
Labels: size:L

#6419 [2.6] Fix FieldSpec Cleanup on failed RDB load - [MOD-10307]
  .gitignore
  build.sh
  src/spec.c
Labels: bug

#6445 [CI] Fix Nightly
  .github/workflows/flow-micro-benchmarks-runner.yml
  .github/workflows/flow-micro-benchmarks.yml
Labels: size:XS, action:run-micro-benchmark

#6450 [2.10] [CI] install python 3.12 on focal
  .install/ubuntu_20.04.sh
Labels: backport 2.8, backport 2.6

#6449 [CI] install python 3.12 on focal
  .install/ubuntu_20.04.sh
Labels: backport 8.0, size:XS, backport 8.2

#6378 [MOD-10286] Implement frequency only encoder/decoder in Rust
  CMakeLists.txt
  src/buffer/CMakeLists.txt
  src/buffer/buffer.c
  src/buffer/buffer.h
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/buffer/src/lib.rs
  src/redisearch_rs/ffi/build.rs
  src/redisearch_rs/inverted_index/Cargo.toml
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
  src/redisearch_rs/inverted_index_bencher/build.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/ctests/test_cntokenize.c
  tests/ctests/test_quantile.c
Labels: size:M, size:L, action:run-rust-micro-benchmark

#6377 Hadle JSON.DEL logs [MOD-10266]
  src/document_basic.c
  src/info/index_error.c
  src/json.c
  tests/pytests/test_json_error_handling.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M, backport 8.2

#6460 add assert when adding to dict on ft.create
  src/spec.c
  tests/pytests/test_multithread.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S, backport 8.2

#6487 [feature-RRF] MOD-10224: Add vector filter validation
  src/query.c
  src/query.h
  src/query_error.h
  src/query_node.h
  tests/cpptests/query_test_utils.h
  tests/cpptests/test_cpp_query.cpp
  tests/cpptests/test_cpp_query_validation.cpp
Labels: size:M

#6469 RLookupRow - Refactor C-Code - MOD-10394
  src/aggregate/aggregate_exec.c
  src/result_processor.c
  src/rlookup.c
  src/rlookup.h
Labels: action:run-benchmark, size:S

#6431 `RLookupKey` transliteration
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/rlookup/Cargo.toml
  src/redisearch_rs/rlookup/src/lib.rs
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:M

#6433 RLookup: KeyList linked-list implementation
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:L

#6491 redisearch_rs: add valgrind suppression file for tests
  src/redisearch_rs/valgrind.supp
Labels: size:S

#6429 [MOD-10326] Rust InvertedIndex - Writing only
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
Labels: size:L

#6459 FFI Layer: Implement RSValueTrait for FFI and implement the C entry point - MOD-9985
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/c_entrypoint/sorting_vector_ffi/Cargo.toml
  src/redisearch_rs/c_entrypoint/sorting_vector_ffi/build.rs
  src/redisearch_rs/c_entrypoint/sorting_vector_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/sorting_vector_ffi/src/lib.rs
  src/redisearch_rs/headers/sorting_vector_rs.h
  src/redisearch_rs/value/src/lib.rs
Labels: size:L

#6514 refactor pending queues
  src/coord/rmr/io_runtime_ctx.c
  src/coord/rmr/io_runtime_ctx.h
  tests/cpptests/coord_tests/test_cpp_io_runtime_ctx.cpp
Labels: size:S

#6517 remove unneeded RQ_Done call in rqAsyncCb
  src/coord/rmr/io_runtime_ctx.c
Labels: size:XS

#6519 fix: redisbench admin install in flow microbenchmarks
  .github/workflows/flow-micro-benchmarks-runner.yml
  .github/workflows/flow-micro-benchmarks.yml
Labels: size:XS, action:run-micro-benchmark

#6495 [MOD-10446] Have Rust constructors for all the index types
  src/redisearch_rs/ffi/src/lib.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:M

#6493 [MOD-10379] Implement the encodeFreqsFields and encodeFreqsFieldsWide encoder/decoder in Rust
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/buffer/src/reader.rs
  src/redisearch_rs/buffer/src/writer.rs
  src/redisearch_rs/inverted_index/Cargo.toml
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/tests/freqs_fields.rs
  src/redisearch_rs/inverted_index_bencher/Cargo.toml
  src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:L, size:XL, action:run-rust-micro-benchmark

#6516 [MOD-10431] accumulate conn state from different IO Runtimes
  src/coord/rmr/conn.c
  src/coord/rmr/conn.h
  src/coord/rmr/rmr.c
  src/util/dict.c
  src/util/dict.h
  tests/pytests/test.py
  tests/pytests/test_multithread.py
Labels: enforce:coverage, enforce:sanitize, size:S, size:M

#6383 MOD-10359 Implement shard window ratio optimization
  src/config.h
  src/coord/dist_aggregate.c
  src/coord/rmr/command.c
  src/coord/rmr/command.h
  src/coord/special_case_ctx.h
  src/module.c
  src/module.h
  src/query.c
  src/query_node.h
  src/shard_window_ratio.c
  src/shard_window_ratio.h
  src/vector_index.h
  tests/ctests/coord_tests/test_command.c
  tests/ctests/coord_tests/test_shard_window_ratio.c
  tests/pytests/common.py
  tests/pytests/test_shard_window_ratio.py
Labels: backport 2.10, size:L, size:XL, backport 8.2

#6492 [MOD-10485] Guard access to `RSAggregateResult` internals
  src/ext/default.c
  src/geo_index.c
  src/hybrid_reader.c
  src/index.c
  src/index_result.c
  src/index_result.h
  src/iterators/intersection_iterator.c
  src/iterators/union_iterator.c
  src/offset_vector.c
  src/optimizer_reader.c
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/lib.rs
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_range.cpp
Labels: size:L

#6470 add `CursorMut::override_current` - MOD-10391
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:M

#6481 [MOD-9680] - Adapt OnReopen mechanism to new LEAF iterators
  src/iterators/empty_iterator.c
  src/iterators/idlist_iterator.c
  src/iterators/intersection_iterator.c
  src/iterators/inverted_index_iterator.c
  src/iterators/inverted_index_iterator.h
  src/iterators/iterator_api.h
  src/iterators/not_iterator.c
  src/iterators/optional_iterator.c
  src/iterators/union_iterator.c
  src/iterators/wildcard_iterator.c
  src/result_processor.c
  tests/cpptests/test_cpp_iterator_empty.cpp
  tests/cpptests/test_cpp_iterator_idlist.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_metric.cpp
  tests/cpptests/test_cpp_iterator_wildcard.cpp
Labels: enforce:sanitize, size:M, size:L, size:XL

#6510 [MOD-10327] Rust inverted index reader
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/fields_only.rs
  src/redisearch_rs/inverted_index/tests/freqs_fields.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
Labels: size:M

#6528 Add missing compilation flag for debug symbols
  CMakeLists.txt
Labels: backport 8.0, size:XS, backport 8.2

#6547 Fix build error in nightly
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:XS

#6548 fix microbenchmark segFault in inverted_index_iterator
  build.sh
  tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
Labels: size:S, size:XS, action:run-micro-benchmark

#6524 [MOD-10544] Make a reader which filters based on the field mask
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
Labels: size:S

#6537 Refactor "on reopen" logic - implement Revalidate for the internal iterators - [MOD-10534]
  src/iterators/empty_iterator.c
  src/iterators/idlist_iterator.c
  src/iterators/intersection_iterator.c
  src/iterators/inverted_index_iterator.c
  src/iterators/inverted_index_iterator.h
  src/iterators/iterator_api.h
  src/iterators/not_iterator.c
  src/iterators/optional_iterator.c
  src/iterators/union_iterator.c
  src/iterators/wildcard_iterator.c
  tests/cpptests/iterator_util.cpp
  tests/cpptests/iterator_util.h
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
  tests/cpptests/test_cpp_iterator_not.cpp
  tests/cpptests/test_cpp_iterator_optional.cpp
  tests/cpptests/test_cpp_iterator_union.cpp
Labels: size:XL

#6523 [MOD-10543] Make a reader which can skip duplicates
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
Labels: size:S

#6494 [MOD-10486] Have Rust manage a `RSAggregateResult`
  src/hybrid_reader.c
  src/index_result.c
  src/index_result.h
  src/optimizer_reader.c
  src/redisearch.h
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/Cargo.toml
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/tests/inverted_index.rs
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_range.cpp
Labels: action:run-benchmark, size:M

#6534 [MOD-10629] Guard direct access to the `IndexBlock` internals
  src/debug_commands.c
  src/fork_gc.c
  src/forward_index.c
  src/indexer.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/iterators/inverted_index_iterator.c
  src/redis_index.c
  src/tag_index.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/index_utils.h
  tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
  tests/cpptests/test_cpp_iterator_not.cpp
  tests/cpptests/test_cpp_iterator_optional.cpp
  tests/cpptests/test_cpp_iterator_union.cpp
Labels: action:run-benchmark, size:M, action:run-micro-benchmark

#6565 Fix an edge case in INKEYS deduplecation
  src/query.c
  tests/pytests/test.py
Labels: bug, size:S, backport 8.2

#6556 [MOD-10627] Various test, debug and doc II encoder/decoder improvements
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
Labels: size:S

#6561 ci: lint: check git diff
  .github/workflows/task-lint.yml
Labels: size:S, size:XS

#6557 version bump
  src/version.h
Labels: size:XS

#6552 MOD-10549 Hybrid implicit SORTBY
  src/aggregate/aggregate.h
  src/aggregate/aggregate_plan.h
  src/aggregate/aggregate_request.c
  src/hybrid/hybrid_request.c
  src/hybrid/parse_hybrid.c
  src/pipeline/pipeline_construction.c
  tests/cpptests/test_cpp_hybrid.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
Labels: size:M

#6436 add `RLookup::get_key_write` - MOD-10396
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:S, size:M

#6571 [MOD-10530] Redesign Decoder API to allow borrowing from the II
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/fields_only.rs
  src/redisearch_rs/inverted_index/tests/freqs_fields.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/fields_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
Labels: size:M

#6540 [MOD-10384] Implement the encodeDocIdsOnly encoder/decoder in Rust
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/inverted_index/src/doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/tests/doc_ids_only.rs
  src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/doc_ids_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:M

#6482 MOD-10226: Implement parser for Hybrid Query VECTOR query params
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/hybrid/parse_hybrid.c
  src/hybrid/vector_query_utils.c
  src/hybrid/vector_query_utils.h
  src/query.c
  src/query.h
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/vector_index.c
  src/vector_index.h
  tests/cpptests/test_cpp_parse_hybrid.cpp
Labels: size:XL
