Repository RediSearch/RediSearch, pull requests merged in 2025-10, with the labels that each got.

#6942 MOD-11660: Limit the size of the heap in search subquery SORTER
  src/hybrid/parse_hybrid.c
  tests/cpptests/test_cpp_parsed_hybrid_pipeline.cpp
  tests/pytests/utils/hybrid.py
Labels: size:S, size:M

#6956 [MOD-11587] (1/2) Refactor API of `value` C module
  src/aggregate/aggregate_exec.c
  src/aggregate/expr/exprast.c
  src/aggregate/expr/expression.c
  src/aggregate/functions/function.h
  src/aggregate/functions/geo.c
  src/aggregate/functions/string.c
  src/aggregate/group_by.c
  src/aggregate/reducers/count_distinct.c
  src/aggregate/reducers/deviation.c
  src/aggregate/reducers/first_value.c
  src/aggregate/reducers/quantile.c
  src/aggregate/reducers/random_sample.c
  src/aggregate/reducers/to_list.c
  src/coord/dist_aggregate.c
  src/document.c
  src/highlight_processor.c
  src/hybrid/hybrid_exec.c
  src/index_result.c
  src/index_result.h
  src/redisearch_rs/value/src/lib.rs
  src/reply.c
  src/rlookup.c
  src/search_ctx.h
  src/sortable.c
  src/value.c
  src/value.h
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_expr.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_iterator_metric.cpp
  tests/cpptests/test_cpp_resultprocessor.cpp
  tests/cpptests/test_cpp_rlookup.cpp
  tests/cpptests/test_cpp_value.cpp
Labels: action:run-benchmark, size:XL

#6934 [MOD-11610] tests: test total_results and results count when LIMIT applied with and without FILTER for FT.HYBRID
  tests/pytests/test_hybrid_mod_11610.py
Labels: size:M

#6963 MOD-11645: Support _NUM_SSTRING as arg of _FT.HYBRID
  src/hybrid/parse/hybrid_callbacks.c
  src/hybrid/parse/hybrid_callbacks.h
  src/hybrid/parse/hybrid_optional_args.c
  src/hybrid/parse/hybrid_optional_args.h
  tests/cpptests/test_cpp_parse_hybrid.cpp
Labels: size:S

#6968 MOD-11654: Deserialize Score If It Exists
  src/coord/rpnet.c
Labels: size:S, size:XS

#6941 MOD-11654: FT.HYBRID - Merging Requires __key To Exists
  src/hybrid/hybrid_request.c
  src/hybrid/parse_hybrid.c
  src/result_processor.c
  src/result_processor.h
  src/util/arg_parser.c
  tests/cpptests/test_cpp_hybridmerger.cpp
Labels: size:S, size:M

#6965 test: test hybrid filter additions
  tests/pytests/test_hybrid_filter.py
Labels: size:S

#6809 MOD-10398 rlookup: port SearchResult
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/ffi/build.rs
  src/redisearch_rs/rlookup/src/row.rs
  src/redisearch_rs/search_result/Cargo.toml
  src/redisearch_rs/search_result/src/bindings.rs
  src/redisearch_rs/search_result/src/lib.rs
Labels: size:M

#6839 MOD-11277 implement `RLookupRow::write_key_by_name` porting C `RLookup_WriteKeyByName` function
  src/redisearch_rs/rlookup/src/lib.rs
  src/redisearch_rs/rlookup/src/lookup.rs
  src/redisearch_rs/rlookup/src/row.rs
  src/redisearch_rs/rlookup/tests/row.rs
Labels: size:M

#6979 MOD-10721: Upload 99.99.99 beta version with unique suffix to beta subdir
  .github/workflows/task-build-artifacts.yml
  sbin/upload-artifacts
Labels: size:S

#6980 Generate beta version in flow-build-artifacts
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/task-build-artifacts.yml
Labels: size:S

#6960 Do not fanout FT.INFO command to replicas
  src/module.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.2

#6973 [8.2] [MOD-11233] - fix: empty string token should be counted in byteOffset…
  src/document.c
  src/forward_index.c
  src/forward_index.h
  tests/pytests/test_highlight.py
Labels: size:M
