Repository RediSearch/RediSearch, pull requests merged in 2025-08, with the labels that each got.

#6577 remove default-members from workspace
  Makefile
  build.sh
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/inverted_index/tests/doc_ids_only.rs
  src/redisearch_rs/inverted_index/tests/fields_only.rs
  src/redisearch_rs/inverted_index/tests/freqs_fields.rs
  src/redisearch_rs/inverted_index/tests/freqs_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  src/redisearch_rs/tools/license_header_linter/src/main.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/corpus.rs
  src/redisearch_rs/varint_bencher/src/bencher.rs
Labels: size:M

#6585 [MOD-9522] remove cargo verification
  .install/verify_build_deps.sh
Labels: backport 2.8, backport 2.6

#6578 [MOD-10677] Add lifetime to RSOffsetVector
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/fields_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  src/redisearch_rs/inverted_index_bencher/build.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/doc_ids_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/fields_only.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  src/redisearch_rs/rqe_iterators/src/rqe_iterator.rs
Labels: size:M

#6437 add `RLookup::get_key_load` - MOD-10397
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:M

#6593 Follow-up: Reduce unsafe usage - MOD-10396 - MOD-10395
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:S

#6592 Add `Revalidate` support for optimized wildcard and missing values indexes - [MOD-10732]
  src/fork_gc.c
  src/iterators/inverted_index_iterator.c
  src/iterators/inverted_index_iterator.h
  src/iterators/wildcard_iterator.c
  src/query.c
  tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
Labels: size:M

#6567 [MOD-10328] Guard access to `InvertedIndex` internals
  src/debug_commands.c
  src/fork_gc.c
  src/indexer.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/iterators/inverted_index_iterator.c
  src/numeric_index.c
  src/profile.c
  src/redis_index.c
  src/spell_check.c
  src/tag_index.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/index_utils.h
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
  tests/cpptests/test_cpp_iterator_not.cpp
  tests/cpptests/test_cpp_iterator_optional.cpp
  tests/cpptests/test_cpp_iterator_union.cpp
Labels: size:M, size:L, action:run-micro-benchmark

#6580 FFI adaptions for RLookupKey to work with CBindgen
  src/redisearch_rs/c_entrypoint/rlookup_ffi/cbindgen.toml
  src/redisearch_rs/headers/rlookup_rs.h
  src/redisearch_rs/rlookup/src/lookup.rs
Labels: size:M

#6595 [MOD-10767] update boost to 1.88.0
  .install/install_boost.sh
  src/util/hash/hash.cpp
  src/util/hash/hash.h
Labels: action:run-benchmark, size:S, size:XS, action:run-micro-benchmark

#6605 [MOD-10382] Implement the encodeOffsetsOnly encoder/decoder in Rust
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/tests/offsets_only.rs
  src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/offsets_only.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:M

#6608 [MOD-10383] Implement the encodeFreqsOffsets encoder/decoder in Rust
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/tests/freqs_offsets.rs
  src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_offsets.rs
  src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:M, size:L

#6622 boost: update cmake script to version 1.88.0
  build/boost/boost.cmake
  developer.md
Labels: size:XS

#6607 [MOD-10158] Guard access to `RSIndexResult`'s data field
  src/debug_commands.c
  src/ext/default.c
  src/fork_gc.c
  src/forward_index.c
  src/index_result.c
  src/index_result.h
  src/inverted_index/inverted_index.c
  src/iterators/hybrid_reader.c
  src/iterators/idlist_iterator.c
  src/iterators/inverted_index_iterator.c
  src/iterators/optimizer_reader.c
  src/numeric_index.c
  src/offset_vector.c
  src/profile.c
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/lib.rs
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_metric.cpp
  tests/cpptests/test_cpp_range.cpp
Labels: size:L

#6616 Avoid using SVS shared lib as default [MOD-10830]
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
  build.sh
  src/vector_index.c
  tests/pytests/includes.py
  tests/pytests/test_vecsim.py
Labels: size:S, size:XS, backport 8.2

#6620 [MOD-5935] Log DocTable capacity growth for memory diagnostics
  src/doc_table.c
Labels: backport 2.8, backport 2.6, backport 2.10, size:XS, backport 8.2

#6635 MOD-10835 Fix SORTBY 0 by not creating Arrange AggPlanStep
  src/aggregate/aggregate_plan.h
  src/aggregate/aggregate_request.c
  src/pipeline/pipeline_construction.c
  tests/cpptests/test_cpp_hybrid.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
Labels: size:M

#6610 MOD-10550 MOD-10645 Window / Limit defaults
  src/hybrid/hybrid_request.c
  src/hybrid/hybrid_scoring.c
  src/hybrid/hybrid_scoring.h
  src/hybrid/parse_hybrid.c
  src/hybrid/parse_hybrid.h
  src/hybrid/vector_query_utils.h
  src/result_processor.c
  tests/cpptests/test_cpp_hybrid.cpp
  tests/cpptests/test_cpp_hybrid_defaults.cpp
  tests/cpptests/test_cpp_hybridmerger.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
Labels: size:L, size:XL

#6638 Bump minimal redis version
  src/module.c
Labels: size:XS, backport 8.2

#6650 [2.10] [MOD-10622] Change time measurement method in FT.PROFILE
  coord/src/coord_module.h
  coord/src/dist_aggregate.c
  coord/src/module.c
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/index.c
  src/info/global_stats.c
  src/info/global_stats.h
  src/info/indexes_info.h
  src/info/info_command.c
  src/info/info_redis.c
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  src/rs_wall_clock.h
  src/spec.c
  src/spec.h
Labels: backport 2.8, backport 2.6

#6644 Make diff failures clearer
  .github/workflows/task-lint.yml
Labels: size:XS

#6640 [MOD-10845] Improve the lifetimes of `RSIndexResult`
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/fields_offsets.rs
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/full.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/test_utils.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  src/redisearch_rs/rqe_iterators/src/rqe_iterator.rs
Labels: size:M

#6666 MOD-10951: Update boost download url
  .install/install_boost.sh
  build/boost/boost.cmake
Labels: backport 2.8, backport 2.6, backport 2.10, size:XS, backport 8.2

#6673 build_utils: factor out link_static_libraries()
  src/redisearch_rs/build_utils/src/lib.rs
  src/redisearch_rs/inverted_index_bencher/build.rs
Labels: size:M

#6688 [8.2] Run against JSON 8.2
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/flow-macos.yml
  .github/workflows/task-test.yml
  build.sh
  tests/pytests/runtests.sh
Labels: size:S

#6643 [MOD-10745] Move `RSIndexResult` and `is_copy` field
  src/index_result.c
  src/iterators/hybrid_reader.c
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/index_result.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/test_utils.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  tests/cpptests/test_cpp_index.cpp
Labels: size:XL

#6700 [2.10] Fix to support lite and properly pack + fix notification syntax error
  .github/workflows/event-deploy-snapshots.yml
  Makefile
  build.sh
  sbin/pack.sh
Labels: backport 2.8, backport 2.6

#6712 fix amazon_linux_2 clang-devel install
  .install/amazon_linux_2.sh
Labels: size:S, size:XS, backport 8.2

#6651 MOD-10748: Fix ACLUserMayAccessIndex
  src/module.c
Labels: size:S, size:XS, backport 8.2

#6718 ci: install clang-devel on cbl-mariner
  .install/common_base_linux_mariner_2.0.sh
Labels: size:XS

#6674 inverted_index_bencher: remove blocklist_item
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/build_utils/Cargo.toml
  src/redisearch_rs/build_utils/src/lib.rs
  src/redisearch_rs/inverted_index_bencher/build.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:S, size:M

#6678 [MOD-10922] Port Empty iterator to Rust
  CMakeLists.txt
  build.sh
  src/iterators/CMakeLists.txt
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/rqe_iterators/src/empty.rs
  src/redisearch_rs/rqe_iterators/src/lib.rs
  src/redisearch_rs/rqe_iterators/src/rqe_iterator.rs
  src/redisearch_rs/rqe_iterators/tests/c_mocks/mod.rs
  src/redisearch_rs/rqe_iterators/tests/empty.rs
  src/redisearch_rs/rqe_iterators_bencher/Cargo.toml
  src/redisearch_rs/rqe_iterators_bencher/benches/iterators.rs
  src/redisearch_rs/rqe_iterators_bencher/build.rs
  src/redisearch_rs/rqe_iterators_bencher/src/benchers/empty.rs
  src/redisearch_rs/rqe_iterators_bencher/src/benchers/mod.rs
  src/redisearch_rs/rqe_iterators_bencher/src/ffi.rs
  src/redisearch_rs/rqe_iterators_bencher/src/lib.rs
Labels: size:L

#6624 [MOD-10831] Refactor debug_commands II code
  src/debug_commands.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/debug.rs
  src/redisearch_rs/inverted_index/src/lib.rs
Labels: size:M

#6682 [MOD-10746] Make `Borrowed` and `Owned` variants for the term and aggregate types
  src/ext/default.c
  src/forward_index.c
  src/index_result.c
  src/index_result.h
  src/inverted_index/inverted_index.c
  src/iterators/hybrid_reader.c
  src/iterators/inverted_index_iterator.c
  src/offset_vector.c
  src/profile.c
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/build_utils/src/lib.rs
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/fields_offsets.rs
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/full.rs
  src/redisearch_rs/inverted_index/src/index_result.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/test_utils.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/c_mocks/mod.rs
  src/redisearch_rs/inverted_index/tests/fields_offsets.rs
  src/redisearch_rs/inverted_index/tests/freqs_offsets.rs
  src/redisearch_rs/inverted_index/tests/full.rs
  src/redisearch_rs/inverted_index/tests/inverted_index.rs
  src/redisearch_rs/inverted_index/tests/offsets_only.rs
  src/redisearch_rs/inverted_index/tests/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  src/redisearch_rs/rqe_iterators/src/empty.rs
  src/redisearch_rs/rqe_iterators/src/lib.rs
  src/redisearch_rs/rqe_iterators_bencher/src/ffi.rs
  tests/cpptests/test_cpp_index.cpp
Labels: size:XL

#6734 ignore criterion output in sub dirs
  .gitignore
Labels: size:XS

#6720 [MOD-10705] Rust Inverted index memory usage and C refactors
  src/fork_gc.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redis_index.c
  src/redis_index.h
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/tag_index.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/index_utils.h
  tests/cpptests/test_cpp_range.cpp
Labels: size:S

#6729 [MOD-11101] Remove encoder arg from `InvertedIndex_WriteForwardIndexEntry`
  src/forward_index.c
  src/forward_index.h
  src/indexer.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/tag_index.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/index_utils.h
  tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
  tests/cpptests/test_cpp_iterator_not.cpp
  tests/cpptests/test_cpp_iterator_optional.cpp
  tests/cpptests/test_cpp_iterator_union.cpp
Labels: size:M

#6742 [MOD-11133] Optimize RSIndexResult drop
  src/index_result.c
  src/index_result.h
  src/iterators/hybrid_reader.c
  src/redisearch_rs/inverted_index/src/index_result.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/c_mocks/mod.rs
  src/redisearch_rs/inverted_index/tests/fields_offsets.rs
  src/redisearch_rs/inverted_index/tests/freqs_offsets.rs
  src/redisearch_rs/inverted_index/tests/full.rs
  src/redisearch_rs/inverted_index/tests/offsets_only.rs
  src/redisearch_rs/inverted_index/tests/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index_bencher/src/lib.rs
  src/redisearch_rs/rqe_iterators/tests/c_mocks/mod.rs
  src/redisearch_rs/rqe_iterators_bencher/src/lib.rs
Labels: size:M

#6730 [MOD-11154] Create unified memory checker
  src/fork_gc.c
  src/spec.c
  src/util/redis_mem_info.c
  src/util/redis_mem_info.h
Labels: size:S, size:M

#6715 Use uv to manage the Python environment for e2e tests.
  .github/workflows/event-pull_request.yml
  .install/alpine_linux_3.sh
  .install/amazon_linux_2.sh
  .install/amazon_linux_2023.sh
  .install/common_base_linux_mariner_2.0.sh
  .install/debian_gnu_linux_11.sh
  .install/debian_gnu_linux_12.sh
  .install/install_python.sh
  .install/install_script.sh
  .install/microsoft_azure_linux_3.0.sh
  .install/rocky_linux_8.sh
  .install/rocky_linux_9.sh
  .install/test_deps/common_installations.sh
  .install/ubuntu_18.04.sh
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  .install/ubuntu_24.04.sh
  .install/verify_build_deps.sh
  .install/verify_build_deps_macos.sh
  .python-version
  pyproject.toml
  tests/pytests/pyproject.toml
  tests/pytests/requirements.txt
  uv.lock
Labels: size:L, enforce:test
