Repository RediSearch/RediSearch, pull requests merged in 2025-06, with the labels that each got.

#6231 MOD-9774: Stop Compiling Redis-With Coverage
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/task-test.yml
Labels: size:XS

#6175 MOD-9768: Add Rust abstractions for Buffer*
  src/inverted_index.c
  src/inverted_index.h
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/buffer/Cargo.toml
  src/redisearch_rs/buffer/src/lib.rs
  src/redisearch_rs/buffer/src/mock.rs
  src/redisearch_rs/buffer/src/tests.rs
  src/redisearch_rs/ffi/.gitignore
  src/redisearch_rs/ffi/Cargo.toml
  src/redisearch_rs/ffi/README.md
  src/redisearch_rs/ffi/build.rs
  src/redisearch_rs/ffi/src/lib.rs
  src/redisearch_rs/redisearch_rs/Cargo.toml
  src/redisearch_rs/trie_bencher/Cargo.toml
  src/varint.c
  tests/cpptests/test_cpp_index.cpp
Labels: size:L

#6244 chore: Improve granularity of build invalidation logic for FFI bindings
  src/redisearch_rs/ffi/build.rs
Labels: size:S

#6249 Add `tests/deps/RedisJSON` to `.gitignore`
  .gitignore
Labels: size:XS

#6246 Indicate Which Test Suite Failed
  tests/pytests/runtests.sh
Labels: size:S, size:XS

#6227 [MOD-9806] Index encoder & decoder interfaces
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/ffi/build.rs
  src/redisearch_rs/inverted_index/Cargo.toml
  src/redisearch_rs/inverted_index/src/lib.rs
Labels: size:S, size:M

#6253 use redis 8.2 branch on CI
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
Labels: size:S, size:XS

#6258 bump version to 8.1.00
  src/version.h
Labels: size:XS

#6248 Refactor Decoders API
  src/inverted_index.c
  src/inverted_index.h
Labels: size:M

#6272 fix ci rust errors
  src/redisearch_rs/trie_rs/src/node/metadata.rs
Labels: size:XS

#6275 Fix skipTo target id
  tests/cpptests/micro-benchmarks/benchmark_idlist_iterator.cpp
  tests/cpptests/micro-benchmarks/benchmark_union_iterator.cpp
  tests/cpptests/micro-benchmarks/benchmark_wildcard_non_optimized_iterator.cpp
Labels: size:S

#6276 [MOD-9560] Revert marking index as faulty after reaching OOM (More queries)
  src/module.c
Labels: backport 8.0, size:S

#6274 Simplify INKEYS flow
  src/aggregate/aggregate_request.c
  src/id_list.c
  src/index.h
  src/query.c
  src/query.h
  src/query_node.h
  src/search_options.h
  tests/pytests/test.py
Labels: size:M

#6219 Refactor Index Iterator - [MOD-8848]
  src/iterators/inverted_index_iterator.c
  src/iterators/inverted_index_iterator.h
  src/iterators/union_iterator.c
  tests/cpptests/CMakeLists.txt
  tests/cpptests/iterator_util.cpp
  tests/cpptests/iterator_util.h
  tests/cpptests/micro-benchmarks/CMakeLists.txt
  tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
  tests/cpptests/micro-benchmarks/benchmark_union_iterator.cpp
  tests/cpptests/micro-benchmarks/deprecated_iterator_util.h
  tests/cpptests/test_cpp_iterator_index.cpp
Labels: size:L, size:XL

#6282 Fix flaky test_debug_commands:test_update_debug_scanner_config [MOD-9854]
  tests/pytests/test_debug_commands.py
Labels: backport 2.10, backport 8.0, size:XS

#6289 Revert temporary azure:linux setup workaround
  .install/microsoft_azure_linux_3.0.sh
Labels: backport 2.8, backport 2.10, backport 8.0, size:XS

#6262 [2.10] Backport OOM indexing to all branches [MOD-9715]
  coord/src/dist_aggregate.c
  coord/src/info_command.c
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/config.c
  src/config.h
  src/debug_commands.c
  src/debug_commands.h
  src/info/field_spec_info.c
  src/info/index_error.c
  src/info/index_error.h
  src/info/indexes_info.c
  src/info/indexes_info.h
  src/info/info_command.c
  src/info/info_redis.c
  src/module.c
  src/profile.c
  src/profile.h
  src/query_error.h
  src/spec.c
  src/spec.h
  tests/pytests/common.py
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_index_error.py
  tests/pytests/test_index_oom.py
  tests/pytests/test_resp3.py
  tests/pytests/test_vecsim.py
Labels: enforce:coverage, enforce:sanitize

#6298 MOD-9856: Check For Timeout Inside RpidxNext Loop
  src/result_processor.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#6255 [MOD-9999] Migrate `RSAggregateResult` to Rust
  src/redisearch.h
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/ffi/Cargo.toml
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/Cargo.toml
  src/redisearch_rs/inverted_index/src/lib.rs
Labels: size:S, size:M

#6300 fix `ffi` CI build issues
  src/redisearch_rs/ffi/build.rs
Labels: size:XS

#6303 Add redisearch_thpool_wait in redisearch_thpool_destroy [MOD-10105]
  deps/thpool/thpool.c
  src/spec.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#6230 Add micro-benchmarks to CI - [MOD - 8849]
  .github/workflows/benchmark-trigger.yml
  .github/workflows/flow-micro-benchmarks-runner.yml
  .github/workflows/flow-micro-benchmarks.yml
  .github/workflows/flow-rust-micro-benchmarks.yml
  build.sh
  tests/cpptests/micro-benchmarks/CMakeLists.txt
Labels: size:M, action:run-micro-benchmark

#6318 [2.10] Let unit-tests run with new build script [mod-6082]
  .github/workflows/task-test.yml
  build.sh
  sbin/unit-tests
  tests/ctests/test_leak.c
Labels: backport 2.8, backport 2.6

#6287 MOD-9769: Implement varint encoding/decoding in Rust
  CMakeLists.txt
  build.sh
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/c_entrypoint/redisearch_rs/Cargo.toml
  src/redisearch_rs/encode_decode/Cargo.toml
  src/redisearch_rs/encode_decode/src/lib.rs
  src/redisearch_rs/encode_decode/src/varint/mod.rs
  src/redisearch_rs/encode_decode/src/varint/vector_writer.rs
  src/redisearch_rs/trie_rs/src/node/metadata.rs
  src/redisearch_rs/varint_bencher/.gitignore
  src/redisearch_rs/varint_bencher/Cargo.toml
  src/redisearch_rs/varint_bencher/README.md
  src/redisearch_rs/varint_bencher/benches/core_operations.rs
  src/redisearch_rs/varint_bencher/benches/vector_writer.rs
  src/redisearch_rs/varint_bencher/build.rs
  src/redisearch_rs/varint_bencher/src/bencher.rs
  src/redisearch_rs/varint_bencher/src/c_varint.rs
  src/redisearch_rs/varint_bencher/src/ffi.rs
  src/redisearch_rs/varint_bencher/src/lib.rs
  src/redisearch_rs/varint_bencher/src/main.rs
  src/varint.c
  src/varint.h
Labels: size:XL, action:run-micro-benchmark

#6322 Refactor Intersection Iterator - [MOD-8842]
  src/iterators/intersection_iterator.c
  src/iterators/intersection_iterator.h
  tests/cpptests/micro-benchmarks/benchmark_intersection_iterator.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
Labels: size:L, action:run-micro-benchmark

#6343 fix microbenchmark link in comment
  .github/workflows/event-nightly.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/flow-micro-benchmarks.yml
Labels: size:S, action:run-micro-benchmark

#6337 MOD-10176: Fix parser for negation of nonexistent function
  src/aggregate/expr/parser.c
  src/aggregate/expr/parser.y
  src/query_parser/v2/lexer.c
  tests/cpptests/test_cpp_expr.cpp
  tests/pytests/test_aggregate.py
Labels: backport 8.0, size:M

#6261 MOD-10017 Rust Counter result processor
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/c_entrypoint/result_processor_ffi/Cargo.toml
  src/redisearch_rs/c_entrypoint/result_processor_ffi/build.rs
  src/redisearch_rs/c_entrypoint/result_processor_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/result_processor_ffi/src/counter.rs
  src/redisearch_rs/c_entrypoint/result_processor_ffi/src/lib.rs
  src/redisearch_rs/c_entrypoint/result_processor_ffi/tests/counter.rs
  src/redisearch_rs/headers/result_processor_rs.h
  src/redisearch_rs/result_processor/src/counter.rs
  src/redisearch_rs/result_processor/src/lib.rs
  src/redisearch_rs/result_processor/src/test_utils.rs
Labels: size:M, size:L

#6360 fix nightly
  .github/workflows/event-nightly.yml
Labels: size:XS

#6345 MOD-10187 Refactor Refactor RLookup_GetKey* C interface for porting
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/aggregate/expr/expression.c
  src/aggregate/reducer.c
  src/coord/dist_plan.cpp
  src/rlookup.c
  src/rlookup.h
  src/spec.c
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_expr.cpp
  tests/cpptests/test_cpp_resultprocessor.cpp
  tests/cpptests/test_cpp_rlookup.cpp
Labels: size:M

#6352 Refactor Optional Iterator Optimized mode - [MOD-9678]
  src/iterators/optional_iterator.c
  src/iterators/optional_iterator.h
  tests/cpptests/index_utils.h
  tests/cpptests/micro-benchmarks/benchmark_optional_iterator.cpp
  tests/cpptests/test_cpp_iterator_optional.cpp
Labels: size:M, action:run-micro-benchmark

#6336 [MOD-10177] Rust benchmark for `numeric` encoder and decoder
  CMakeLists.txt
  build.sh
  src/inverted_index/CMakeLists.txt
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/ffi/build.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index_bencher/Cargo.toml
  src/redisearch_rs/inverted_index_bencher/README.md
  src/redisearch_rs/inverted_index_bencher/benches/numeric.rs
  src/redisearch_rs/inverted_index_bencher/build.rs
  src/redisearch_rs/inverted_index_bencher/src/bencher.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  src/redisearch_rs/inverted_index_bencher/src/lib.rs
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/index_utils.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
  tests/ctests/test_cntokenize.c
Labels: size:L, action:run-micro-benchmark

#6364 Fix TTL dictionary - [MOD-10240]
  build.sh
  src/ttl_table.c
  tests/pytests/test_expire.py
Labels: bug, backport 2.10, backport 8.0, size:S

#6365 Test only for debian with gcc11 + remove arm from amzn2
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/task-get-linux-configurations.yml
Labels: size:S

#6367 MOD-10248 - Less restrictive Rust allocator shim
  src/redisearch_rs/redis_mock/src/allocator.rs
Labels: size:S, size:M

#6368 [8.0] Fix TTL dictionary - [MOD-10240]
  build.sh
  src/ttl_table.c
  tests/pytests/test_expire.py
Labels: bug, size:S

#6372 [MOD-9403] Remove stale varint target
  CMakeLists.txt
Labels: size:XS

#6389 Prevent CI breakage when Rust 1.88.0 is released (#6375)
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/low_memory_thin_vec/src/lib.rs
  src/redisearch_rs/wildcard/src/fmt.rs
Labels: size:S

#6384 Fix test flakiness - [MOD-10076]
  src/fork_gc.c
  tests/pytests/common.py
  tests/pytests/test_gc.py
  tests/pytests/test_index_oom.py
Labels: backport 8.0, size:S

#6394 Add serialisation for svs + adjustments [MOD-10097]
  src/info/info_command.c
  src/json.c
  src/spec.c
  src/spec.h
  src/vector_index.c
  src/vector_index.h
  tests/pytests/test_json.py
  tests/pytests/test_multithread.py
  tests/pytests/test_rdb_compatibility.py
  tests/pytests/test_vecsim.py
Labels: size:L, size:XL
