Repository RediSearch/RediSearch, pull requests merged in 2025-04, with the labels that each got.

#5850 MOD-9274: Pin CMake Version For Mac OS
  .install/macos.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5844 MOD-9222: Fix strict timeout result aggregation
  src/aggregate/aggregate_exec.c
  tests/pytests/test_cursors.py
Labels: backport 2.8, backport 2.10, backport 8.0

#5862 Account For Vector Set Module In Tests
  tests/pytests/test_config.py
Labels: backport 8.0

#5870 PR size label
  .github/workflows/pr_label_size.yml
Labels: size:S

#5797 [MOD-8972] - Implement basic TrieMap functionality in Rust
  .github/workflows/task-test.yml
  .install/alpine_linux_3.sh
  Makefile
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/low_memory_thin_vec/src/lib.rs
  src/redisearch_rs/trie_rs/Cargo.toml
  src/redisearch_rs/trie_rs/src/ffi.rs
  src/redisearch_rs/trie_rs/src/lib.rs
  src/redisearch_rs/trie_rs/src/trie.rs
Labels: size:XL

#5886 Fix regex pattern in build artifact validation
  .github/workflows/flow-build-artifacts.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#5819 [MOD-8974] Microbenchmarks for the Rust trie map implementation
  .codespell/.codespellrc
  CMakeLists.txt
  Makefile
  deps/triemap/CMakeLists.txt
  deps/triemap/triemap.c
  deps/triemap/triemap.h
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/trie_bencher/.gitignore
  src/redisearch_rs/trie_bencher/Cargo.toml
  src/redisearch_rs/trie_bencher/README.md
  src/redisearch_rs/trie_bencher/benches/operations.rs
  src/redisearch_rs/trie_bencher/build.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/c_map.rs
  src/redisearch_rs/trie_bencher/src/corpus.rs
  src/redisearch_rs/trie_bencher/src/ffi.rs
  src/redisearch_rs/trie_bencher/src/lib.rs
  src/redisearch_rs/trie_bencher/src/main.rs
  src/redisearch_rs/trie_bencher/src/redis_allocator.rs
  src/redisearch_rs/trie_rs/Cargo.toml
  src/redisearch_rs/trie_rs/src/trie.rs
Labels: size:L

#5892 MOD-9316: Fix Duplicate Index Loading From RDB
  src/spec.c
  src/spec.h
Labels: backport 2.10, backport 8.0, size:S

#5778 MOD-7795: Background indexing memory limitation & configuration
  deps/rmutil/args.c
  deps/rmutil/args.h
  src/aggregate/aggregate_exec.c
  src/config.c
  src/config.h
  src/coord/info_command.c
  src/debug_commands.c
  src/debug_commands.h
  src/info/field_spec_info.c
  src/info/index_error.c
  src/info/index_error.h
  src/info/indexes_info.c
  src/info/indexes_info.h
  src/info/info_command.c
  src/info/info_redis/info_redis.c
  src/module.c
  src/query_error.h
  src/spec.c
  src/spec.h
  tests/pytests/common.py
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_index_error.py
  tests/pytests/test_index_oom.py
  tests/pytests/test_resp3.py
  tests/pytests/test_vecsim.py
Labels: backport 8.0, size:XL

#5828 MOD-9058 linter for dependencies on ubuntu OSs
  .github/workflows/flow-temp.yml
  .github/workflows/task-get-linux-configurations.yml
  .install/verify_build_deps.sh
  Makefile
Labels: backport 8.0, size:M

#5918 MOD-9234: Pin test dependencies
  tests/pytests/requirements.txt
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S

#5913 get_cmake_version is not complatible with alpine, fix that
  .install/verify_build_deps.sh
Labels: backport 8.0, size:XS

#5883 [MOD-9258] MacOS Deps check linter
  .github/workflows/flow-temp.yml
  .install/install_llvm.sh
  .install/verify_build_deps.sh
  .install/verify_build_deps_macos.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S

#5941 fix flaky OOM tests MOD-9406
  tests/pytests/common.py
Labels: backport 8.0, size:S

#5944 Fix upload-artifact Script
  .github/workflows/task-build-artifacts.yml
  sbin/upload-artifacts
Labels: backport 8.0, size:S

#5949 MOD-9368: Add configurable stretch factor for normalized BM25STD.TANH
  deps/rmutil/args.c
  deps/rmutil/args.h
  src/aggregate/aggregate.h
  src/aggregate/aggregate_request.c
  src/config.c
  src/config.h
  src/coord/dist_aggregate.c
  src/ext/default.c
  src/info/info_redis/info_redis.c
  src/redisearch.h
  tests/pytests/test_config.py
  tests/pytests/test_info_modules.py
  tests/pytests/test_scorers.py
Labels: backport 2.10, backport 8.0, size:M

#5958 Fix scores when document has no text - [MOD-9423]
  src/ext/default.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S

#5963 [MOD-9437] Avoid linking `libuv` dynamically
  build/libuv/Makefile
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#5979 Fix Upload Script Again 2
  sbin/upload-artifacts
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#5897 Moved all request based benchmarks to time-based benchmarks.
  .github/workflows/benchmark-runner.yml
  tests/benchmarks/search-expire-doc-10-milliseconds.yml
  tests/benchmarks/search-expire-doc-1000-seconds.yml
  tests/benchmarks/search-expire-numeric-field-10-milliseconds.yml
  tests/benchmarks/search-expire-numeric-field-1000-seconds.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml
  tests/benchmarks/search-ftsb-10K-multivalue-numeric-json.yml
  tests/benchmarks/search-ftsb-10K-singlevalue-numeric-json.yml
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable@50_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
Labels: action:run-benchmark, backport 2.8, backport 2.10, size:M

#5849 Changing b value to 0.75 in BM25STD
  src/ext/default.c
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test_scorers.py
  tests/pytests/test_vecsim.py
Labels: backport 8.0, size:M

#5951 MOD-9231 Enhance Allocator/Deallcator Shims for Rust Benchmarks
  src/redisearch_rs/trie_bencher/benches/operations.rs
  src/redisearch_rs/trie_bencher/build.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/c_map.rs
  src/redisearch_rs/trie_bencher/src/corpus.rs
  src/redisearch_rs/trie_bencher/src/ffi.rs
  src/redisearch_rs/trie_bencher/src/lib.rs
  src/redisearch_rs/trie_bencher/src/main.rs
  src/redisearch_rs/trie_bencher/src/redis_allocator.rs
Labels: size:L

#5987 Rename UV thread when spinning it up
  src/coord/rmr/rq.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S

#5737 Refactor build system - remove readies from module build [MOD-5722]
  .github/workflows/benchmark-flow.yml
  .github/workflows/task-test.yml
  .install/macos_update_profile.sh
  CMakeLists.txt
  Makefile
  build.sh
  build/boost/boost.cmake
  build/docker/Makefile
  build/docker/dockerfile.tmpl
  build/hiredis/hiredis.cmake
  build/s2geometry/Makefile
  build/s2geometry/Makefile.defs
  sbin/unit-tests
  src/coord/CMakeLists.txt
  src/coord/rmr/CMakeLists.txt
  tests/pytests/runtests.sh
Labels: action:run-benchmark, backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XL

#5984 Improve parser for intersections [MOD-9278]
  .codespell/ignore_wordlist.txt
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_parser.py
  tests/pytests/test_profile.py
  tests/pytests/test_scorers.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M

#6003 Revert "Refactor build system - remove readies from module build"
  .github/workflows/benchmark-flow.yml
  .github/workflows/task-test.yml
  .install/macos_update_profile.sh
  CMakeLists.txt
  Makefile
  build.sh
  build/boost/boost.cmake
  build/docker/Makefile
  build/docker/dockerfile.tmpl
  build/hiredis/hiredis.cmake
  build/s2geometry/Makefile
  build/s2geometry/Makefile.defs
  sbin/unit-tests
  src/coord/CMakeLists.txt
  src/coord/rmr/CMakeLists.txt
  tests/pytests/runtests.sh
Labels: size:XL

#6006 [8.0] Improve parser for intersections [MOD-9278]
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_parser.py
  tests/pytests/test_profile.py
  tests/pytests/test_scorers.py
Labels: bug, size:M

#6011 Introduce a facade crate, `redisearch_rs`.
  CMakeLists.txt
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/redis_mock/Cargo.toml
  src/redisearch_rs/redis_mock/src/allocator.rs
  src/redisearch_rs/redis_mock/src/lib.rs
  src/redisearch_rs/redisearch_rs/Cargo.toml
  src/redisearch_rs/redisearch_rs/src/lib.rs
  src/redisearch_rs/redisearch_rs/src/trie.rs
  src/redisearch_rs/trie_bencher/Cargo.toml
  src/redisearch_rs/trie_bencher/src/lib.rs
  src/redisearch_rs/trie_rs/Cargo.toml
  src/redisearch_rs/trie_rs/src/lib.rs
Labels: size:M

#6013 MOD-9516: Remove ubuntu:bionic from ci
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-get-linux-configurations.yml
  .github/workflows/task-test.yml
Labels: size:S

#6001 MOD-9506: Lazily subscribe to key-space notifications
  src/module-init/module-init.c
  src/module.c
  src/module.h
  src/notifications.c
  src/notifications.h
  src/spec.c
Labels: size:S

#5836 [8.0] Updated the base image of benchmarks to run on 24.04 (#5823)
  .github/workflows/benchmark-flow.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/requirements.txt
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
Labels: action:run-benchmark

#5959 Skip Atempting to Load Key Name - [MOD-9419]
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/common.py
  tests/pytests/test_multithread.py
Labels: experimental, backport 2.10, backport 8.0, size:M

#6021 [8.0] Skip Atempting to Load Key Name - [MOD-9419]
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/common.py
  tests/pytests/test_multithread.py
Labels: experimental, size:M

#5966 [2.8] Fix scores when document has no text - [MOD-9423]
  src/ext/default.c
  tests/pytests/test_issues.py
  tests/pytests/test_search_params.py
  tests/pytests/test_tags.py
Labels: bug

#5967 [2.10] Fix scores when document has no text - [MOD-9423]
  src/ext/default.c
  tests/pytests/test_issues.py
  tests/pytests/test_search_params.py
  tests/pytests/test_tags.py
Labels: bug

#6007 [2.10] Improve parser for intersections [MOD-9278]
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_dialect.py
  tests/pytests/test_parser.py
  tests/pytests/test_profile.py
  tests/pytests/test_scorers.py
Labels: bug, size:M

#6020 [2.10] Skip Atempting to Load Key Name - [MOD-9419]
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/common.py
  tests/pytests/test_multithread.py
Labels: experimental, size:M

#5992 [2.10] Moved all request based benchmarks to time-based benchmarks
  .github/workflows/benchmark-runner.yml
  tests/benchmarks/search-expire-doc-10-milliseconds.yml
  tests/benchmarks/search-expire-doc-1000-seconds.yml
  tests/benchmarks/search-expire-numeric-field-10-milliseconds.yml
  tests/benchmarks/search-expire-numeric-field-1000-seconds.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml
  tests/benchmarks/search-ftsb-10K-multivalue-numeric-json.yml
  tests/benchmarks/search-ftsb-10K-singlevalue-numeric-json.yml
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable@50_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
Labels: action:run-benchmark

#6008 [2.8] Improve parser for intersections [MOD-9278]
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_dialect.py
  tests/pytests/test_parser.py
  tests/pytests/test_profile.py
  tests/pytests/test_scorers.py
Labels: bug, size:M

#6022 CI improvement - Improve getting latest tags
  .github/workflows/task-get-latest-tag.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#5965 [2.6] Fix scores when document has no text - [MOD-9423]
  src/ext/default.c
  tests/pytests/test_issues.py
Labels: bug

#5993 [2.8] Moved all request based benchmarks to time-based benchmarks
  .github/workflows/benchmark-runner.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
  tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml
  tests/benchmarks/search-ftsb-10K-multivalue-numeric-json.yml
  tests/benchmarks/search-ftsb-10K-singlevalue-numeric-json.yml
  tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml
  tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable@50_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query.yml
  tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query@100_ops_sec.yml
  tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml
  tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml
  tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
Labels: action:run-benchmark

#5926 MOD-9231 - Integrate Rust Benchmarks in CI
  .github/workflows/event-pull_request.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/flow-micro-benchmarks.yml
  .github/workflows/task-check-changes.yml
  .github/workflows/task-lint.yml
  src/redisearch_rs/trie_bencher/Cargo.toml
  src/redisearch_rs/trie_bencher/benches/operations.rs
  src/redisearch_rs/trie_bencher/build.rs
Labels: size:M

#6005 Fix Cursor Purge - [MOD-9408]
  src/cursor.c
  src/cursor.h
  tests/cpptests/test_cpp_cursors.cpp
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M

#6000 [MOD-9547] Implement wildcard matching, as a preliminary step towards wildcard trie iterators.
  .codespell/.codespellrc
  src/redisearch_rs/.gitignore
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/wildcard/Cargo.toml
  src/redisearch_rs/wildcard/benches/matching.rs
  src/redisearch_rs/wildcard/src/fmt.rs
  src/redisearch_rs/wildcard/src/lib.rs
  src/redisearch_rs/wildcard/tests/integration/fmt.rs
  src/redisearch_rs/wildcard/tests/integration/main.rs
  src/redisearch_rs/wildcard/tests/integration/matches.rs
  src/redisearch_rs/wildcard/tests/integration/parse.rs
  src/redisearch_rs/wildcard/tests/integration/properties.rs
  src/redisearch_rs/wildcard/tests/integration/utils.rs
Labels: size:L

#5856 Coverage Report Without `readies` - Phase 1 - [MOD-9056]
  .github/workflows/flow-coverage.yml
  Makefile
  README.md
  tests/cpptests/redismock/redismock.cpp
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S

#6034 [MOD-9566] Fix format-security compilation and enforce flag in CMake
  CMakeLists.txt
  src/spec.c
Labels: backport 8.0, size:XS

#6039 [8.0] Fix OOM behavior
  src/aggregate/aggregate_exec.c
  src/config.c
  src/config.h
  src/module.c
  src/query_error.h
  tests/pytests/common.py
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_index_oom.py
Labels: backport master

#6045 CI fixes - PR workflow conditions
  .github/workflows/event-pull_request.yml
Labels: size:S

#6032 [2.6] Fix Cursor Purge - [MOD-9408]
  src/cursor.c
  src/cursor.h
  tests/cpptests/test_cpp_cursors.cpp
Labels: bug

#5985 2.10 upload package COORD=oss
  .github/workflows/task-build-artifacts.yml
  Makefile
  pack/ramp-oss-cluster.yml
  sbin/upload-artifacts
Labels: backport 2.8, backport 2.6

#6002 Avoid lazy expiration in background indexing for CRDT [MOD-9486]
  src/spec.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:S

#6061 MOD-9581: Fix rocky9 CI
  .install/rocky_linux_9.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#6060 Temporarily skip flaky test
  tests/pytests/test.py
Labels: backport 2.8, backport 2.10, backport 8.0, size:XS
