Repository RediSearch/RediSearch, pull requests merged in 2025-01, with the labels that each got.

#5417 [MOD-8451] install boost from official site
  .install/install_boost.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5187 MOD-8058: Avoid error with _NUM_SSTRING
  src/value.c
  tests/pytests/test_aggregate.py
Labels: action:run-benchmark, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5440 [MOD-8462] rename total_active_writes -> total_active_write_threads
  src/info/indexes_info.c
  src/info/indexes_info.h
  src/info/info_redis.c
  tests/pytests/test_info_modules.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5450 [MOD-8469] Test macos latest on arm instead of 13
  .github/workflows/flow-macos.yml
Labels: backport 2.8, backport 2.6

#5454 MOD-8486: Sanitize User Input
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/buffer.c
  src/config.c
  src/config.h
  src/coord/dist_aggregate.c
  src/module.c
  src/varint.c
  src/vector_index.c
  src/vector_index.h
  tests/pytests/test_issues.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5422 MOD-7570: Valid safe vector index pointer access
  src/debug_commands.c
  src/indexer.c
  src/spec.c
  src/vector_index.c
  tests/pytests/common.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_vecsim.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5469 Fix release flow
  .github/workflows/event-release.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5494 Fix get-redisjson script
  sbin/get-redisjson
Labels: backport 2.10, backport 8.0

#5340 MOD-8229: FT.ALIASADD does not fail when adding an alias that is an existing index name
  src/module.c
  src/query_error.h
  tests/pytests/test.py
Labels: breaking change

#5343 MOD-8240: FT.DROPINDEX does not fail with an illegal third argument.
  src/module.c
  tests/pytests/test.py
Labels: breaking change

#5402 MOD-8413 MOD-8553: Fix optimized NOT iterator
  src/index.c
  src/inverted_index.c
  src/inverted_index.h
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_tags.py
Labels: backport 8.0

#5505 Revert field validation on DIALECT 1 - [MOD-8195]
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  tests/pytests/test.py
  tests/pytests/test_tags.py
Labels: backport 8.0

#5320 MOD-8223: Delete empty suggest dict
  src/suggest.c
  tests/pytests/test_aux_save2.py
  tests/pytests/test_suggest.py
Labels: breakingchange, backport 8.0

#5503 MOD-7069: Send GC heartbeats to track copy on write behaviour
  src/fork_gc.c
  src/fork_gc.h
  tests/cpptests/redismock/redismock.cpp
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5017 MOD-7731: Align command registration
  src/module.c
  tests/pytests/test_replicate.py
Labels: backport 8.0, breaking change

#5516 [2.10] Fix legacy geofilter leak - [MOD-8568]
  src/aggregate/aggregate_request.c
  src/search_options.h
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6

#5511 Improve reducers no-value behavior - [MOD-7786, MOD-7787, MOD-7789, MOD-7800, MOD-7802]
  src/aggregate/reducers/deviation.c
  src/aggregate/reducers/first_value.c
  src/aggregate/reducers/minmax.c
  src/aggregate/reducers/quantile.c
  src/aggregate/reducers/sum.c
  src/util/quantile.c
  tests/pytests/test_aggregate.py
Labels: bug, backport 8.0

#5515 Revert Dropping Legacy Filters Support - [MOD-8256]
  src/aggregate/aggregate_request.c
  src/geo_index.c
  src/geo_index.h
  src/numeric_filter.c
  src/numeric_filter.h
  src/query.c
  src/query.h
  src/query_param.c
  src/search_options.h
  tests/pytests/test.py
Labels: backport 8.0

#5258 Change default scorer - [MOD-7796]
  src/ext/default.c
  src/ext/default.h
  src/query_optimizer.c
  tests/cpptests/test_cpp_llapi.cpp
  tests/pytests/test.py
  tests/pytests/test_existing.py
  tests/pytests/test_expire.py
  tests/pytests/test_followhashes.py
  tests/pytests/test_issues.py
  tests/pytests/test_json.py
  tests/pytests/test_resp3.py
  tests/pytests/test_scorers.py
  tests/pytests/test_tags.py
  tests/pytests/test_vecsim.py
  tests/pytests/test_wildcard.py
Labels: backport 8.0, breaking change

#5523 Fix legacy geofilter leak - [MOD-8568]
  src/aggregate/aggregate_request.c
  src/geo_index.c
  src/search_options.h
  tests/pytests/test_issues.py
Labels: bug, backport 8.0

#5528 MOD-8561: Fix Inverted Index SeekTo Edge Case
  src/inverted_index.c
  tests/cpptests/test_cpp_tagindex.cpp
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5538 Load config params for Redis 8.0-m03
  src/module.c
  tests/pytests/test_config.py
Labels: backport 8.0

#5531 MOD-8601: Fix error message for LOAD
  src/aggregate/aggregate_request.c
  tests/pytests/common.py
  tests/pytests/test_aggregate.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5541 Fix flakiness in a test - [MOD-8611]
  tests/pytests/test_issues.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5544 Bump version to 7.99.3
  src/version.h
Labels: backport 8.0

#5520 Fix APPLY/FILTER parser - [MOD-7804]
  src/aggregate/expr/exprast.c
  src/aggregate/expr/exprast.h
  src/aggregate/expr/expression.c
  src/aggregate/expr/lexer.c
  src/aggregate/expr/lexer.rl
  src/aggregate/expr/parser.c
  src/aggregate/expr/parser.h
  src/aggregate/expr/parser.y
  src/aggregate/functions/date.c
  src/aggregate/functions/function.c
  src/aggregate/functions/function.h
  src/aggregate/functions/geo.c
  src/aggregate/functions/math.c
  src/aggregate/functions/string.c
  tests/cpptests/test_cpp_expr.cpp
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_issues.py
  tests/pytests/test_profile.py
Labels: bug, backport 8.0

#5559 [2.6] Fix Max Frequency Misscalculation - [MOD-8158]
  src/document.c
  tests/pytests/test_issues.py
  tests/pytests/test_vecsim.py
Labels: bug

#5560 [2.8] Fix Max Frequency Misscalculation - [MOD-8158]
  src/document.c
  tests/pytests/test_issues.py
  tests/pytests/test_vecsim.py
Labels: bug

#5568 MOD-8670, MOD-8648: Make Quotes and Single Quotes Interchangeable
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.h
  src/query_parser/v2/parser.y
  tests/pytests/test_parser.py
  tests/pytests/test_quotes.py
Labels: backport 8.0

#5555 MOD-7791: Change ON_TIMEOUT default value
  src/config.c
  src/config.h
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_config.py
  tests/pytests/test_contains.py
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
  tests/pytests/test_expire.py
  tests/pytests/test_issues.py
  tests/pytests/test_json.py
  tests/pytests/test_multithread.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
  tests/pytests/test_tags.py
  tests/pytests/test_wildcard.py
Labels: backport 8.0

#5566 Fix Empty Numeric Value - [MOD-7244]
  src/aggregate/aggregate_request.c
  src/coord/dist_aggregate.c
  src/geo_index.c
  src/geo_index.h
  src/module.c
  src/module.h
  src/numeric_filter.c
  src/numeric_filter.h
  src/query.c
  src/query.h
  src/query_node.h
  src/query_param.c
  src/query_param.h
  src/vector_index.c
  src/vector_index.h
  tests/pytests/test_empty.py
Labels: backport 8.0

#5579 CI Improvements
  .github/workflows/flow-coverage.yml
  .github/workflows/task-backport_pr.yml
  .github/workflows/task-get-latest-tag.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0
