Repository RediSearch/RediSearch, pull requests merged in 2025-09, with the labels that each got.

#6741 [MOD-11129] Enforce encoder/decoder relationship in the type system
  src/redisearch_rs/inverted_index/src/doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/fields_offsets.rs
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/full.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/tests.rs
Labels: size:M

#6743 [MOD-11103] Inverted Index Reader and API
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/iterators/inverted_index_iterator.c
  src/iterators/inverted_index_iterator.h
  src/profile.c
  tests/cpptests/test_cpp_iterator_index.cpp
Labels: size:M

#6554 [MOD-10448] Have Rust clone a `RSIndexResult` correctly
  src/index_result.c
  src/index_result.h
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/inverted_index/src/index_result.rs
  src/redisearch_rs/inverted_index/tests/c_mocks/mod.rs
  src/redisearch_rs/inverted_index/tests/index_result.rs
  src/redisearch_rs/inverted_index/tests/inverted_index.rs
Labels: size:L

#6754 iterator: return a borrow instead of an owned result
  src/redisearch_rs/rqe_iterators/src/empty.rs
  src/redisearch_rs/rqe_iterators/src/lib.rs
Labels: size:S

#6737 MOD-10407: Handle warnings and errors of the subquery pipelines
  src/aggregate/aggregate_debug.c
  src/debug_commands.c
  src/hybrid/hybrid_debug.c
  src/hybrid/hybrid_debug.h
  src/hybrid/hybrid_exec.c
  src/hybrid/hybrid_exec.h
  src/hybrid/hybrid_request.c
  src/hybrid/hybrid_request.h
  src/hybrid/parse_hybrid.c
  src/result_processor.c
  src/result_processor.h
  tests/cpptests/test_cpp_hybridmerger.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
  tests/pytests/test_debug_commands.py
  tests/pytests/test_hybrid_errors.py
  tests/pytests/test_rrf.py
Labels: size:L, size:XL

#6485 Add an FFI layer for RLookupRow - MOD-10403
  src/aggregate/expr/expression.c
  src/aggregate/group_by.c
  src/document.c
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/c_entrypoint/rlookup_ffi/Cargo.toml
  src/redisearch_rs/c_entrypoint/rlookup_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/rlookup_ffi/src/lib.rs
  src/redisearch_rs/c_entrypoint/rlookup_ffi/src/row.rs
  src/redisearch_rs/headers/rlookup_rs.h
  src/redisearch_rs/rlookup/src/row.rs
  src/result_processor.c
  src/rlookup.c
  src/rlookup.h
  tests/cpptests/test_cpp_expr.cpp
  tests/cpptests/test_cpp_rlookup.cpp
Labels: size:M

#6756 [MOD-10704] Implement Rust providing a debug summary for an inverted index
  src/redisearch_rs/inverted_index/src/debug.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
Labels: size:M

#6747 [MOD-11098] Have a wrapper to track the number of entries in an inverted index
  src/redisearch_rs/inverted_index/src/doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/fields_offsets.rs
  src/redisearch_rs/inverted_index/src/fields_only.rs
  src/redisearch_rs/inverted_index/src/freqs_fields.rs
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/freqs_only.rs
  src/redisearch_rs/inverted_index/src/full.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
Labels: size:S, size:M

#6759 [MOD-11194] Port `NumericFilter` to Rust
  src/numeric_filter.c
  src/numeric_filter.h
  src/numeric_index.c
  src/query.c
  src/query_optimizer.c
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/lib.rs
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_query.cpp
Labels: size:M

#6761 [MOD-10347] Remove unused code from RSValue
  src/value.c
  src/value.h
Labels: size:M

#6746 [MOD-11082] remove offsets_tz var in RSIndexResult
  src/forward_index.c
  src/indexer.c
  src/inverted_index/inverted_index.c
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/fields_offsets.rs
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/full.rs
  src/redisearch_rs/inverted_index/src/index_result.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/src/test_utils.rs
  src/redisearch_rs/inverted_index/tests/index_result.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  src/tag_index.c
Labels: size:S, size:M

#6771 [MOD-10704] Implement Rust providing a debug summary for an inverted index
  src/redisearch_rs/inverted_index/src/debug.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Labels: size:M

#6745 MOD-11047: Rename RRF K parameter to CONSTANT
  src/hybrid/hybrid_scoring.c
  src/hybrid/hybrid_scoring.h
  src/hybrid/parse_hybrid.c
  tests/cpptests/test_cpp_hybrid_defaults.cpp
  tests/cpptests/test_cpp_hybridmerger.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
  tests/pytests/test_hybrid.py
Labels: size:S, size:M

#6768 [MOD-10707] Implement `skip_to` functionality on the Rust index reader
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
Labels: size:M

#6760 [MOD-11195] Port `DecoderCtx` to Rust
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/iterators/inverted_index_iterator.c
  src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
  src/redisearch_rs/headers/types_rs.h
  src/redisearch_rs/inverted_index/src/lib.rs
Labels: size:M

#6766 [MOD-11171] Rust filter wrapper around inverted index reader
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/tests.rs
Labels: size:M

#6758 [MOD-11220] move core logic of FGC_applyInvertedIndex to II
  .install/test_deps/common_installations.sh
  Makefile
  build.sh
  src/fork_gc.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  tests/deps/setup_rejson.sh
Labels: size:M, size:L

#6780 [MOD-11242] FFI crate for the Rust inverted index
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/Cargo.toml
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/build.rs
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/src/lib.rs
  src/redisearch_rs/headers/future/inverted_index.h
Labels: size:M

#6802 Implements seekers for Rust decoders
  src/redisearch_rs/inverted_index/src/fields_offsets.rs
  src/redisearch_rs/inverted_index/src/freqs_offsets.rs
  src/redisearch_rs/inverted_index/src/full.rs
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/offsets_only.rs
  src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index/tests/fields_offsets.rs
  src/redisearch_rs/inverted_index/tests/freqs_offsets.rs
  src/redisearch_rs/inverted_index/tests/full.rs
  src/redisearch_rs/inverted_index/tests/offsets_only.rs
  src/redisearch_rs/inverted_index/tests/raw_doc_ids_only.rs
Labels: size:M, size:L

#6819 [MOD-11137] Add module.conf file
  module.conf
Labels: size:M

#6801 MOD-11276, MOD-11043: Reconstruct RlookupRow when merging
  src/hybrid/hybrid_lookup_context.h
  src/hybrid/hybrid_request.c
  src/hybrid/hybrid_search_result.c
  src/hybrid/hybrid_search_result.h
  src/hybrid/parse_hybrid.c
  src/result_processor.c
  src/result_processor.h
  src/rlookup.c
  src/rlookup.h
  tests/cpptests/test_cpp_hybridmerger.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
  tests/cpptests/test_cpp_rlookup.cpp
  tests/pytests/common.py
  tests/pytests/test_hybrid_distance.py
  tests/pytests/test_hybrid_search.py
  tests/pytests/test_rrf.py
Labels: size:XL

#6840 [Chore] Version Bump to 8.2.5
  src/version.h
Labels: size:XS

#6828 [MOD-11398] Add "ignore" option to ON_OOM config
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_request.c
  src/config.c
  src/config.h
  src/coord/dist_aggregate.c
  src/info/info_redis/info_redis.c
  src/module.c
  src/result_processor.c
  src/result_processor.h
  tests/pytests/test_config.py
Labels: size:M

#6837 [MOD-11260] FFI layer for inverted index reader
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/src/lib.rs
  src/redisearch_rs/headers/future/inverted_index.h
Labels: size:L

#6826 MOD-11258: Add parameter count validation to COMBINE LINEAR clause
  src/hybrid/parse_hybrid.c
  tests/cpptests/test_cpp_hybrid_defaults.cpp
  tests/cpptests/test_cpp_parse_hybrid.cpp
  tests/cpptests/test_cpp_parsed_hybrid_pipeline.cpp
  tests/pytests/test_hybrid_apply_filter.py
  tests/pytests/test_hybrid_search.py
  tests/pytests/test_hybrid_timeout.py
  tests/pytests/test_rrf.py
Labels: size:S, size:M

#6850 [MOD-11045] Have Rust track the total number of index block
  src/info/info_command.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/src/lib.rs
  src/redisearch_rs/headers/future/inverted_index.h
  src/redisearch_rs/inverted_index/src/lib.rs
  src/spec.c
  tests/cpptests/test_cpp_forkgc.cpp
Labels: size:S

#6860 Provide FFI stubs and ignore flaky test
  src/redisearch_rs/inverted_index_bencher/src/ffi.rs
  src/redisearch_rs/inverted_index_bencher/src/lib.rs
Labels: size:S, size:XS

#6817 MOD-11190: Add IndexSpec RDB Comparison Tests - Fix Index RDB field initialization
  src/spec.c
  src/spec.h
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/redismock/redismock.h
  tests/cpptests/test_cpp_rdb.cpp
Labels: backport 2.8, backport 2.6, backport 2.10, size:L, backport 8.2

#6773 MOD-11173: Fix unreachable links in markdown files
  .github/workflows/event-weekly.yml
  .github/workflows/link-check.yml
  Makefile
  README.md
  developer.md
  docs/images/logo.svg
  scripts/README-linkcheck.md
  scripts/check_links.py
  scripts/link-check-config.json
  scripts/requirements-linkcheck.txt
  scripts/test_link_checker.py
Labels: size:L

#6838 fix: RLookupRow use-after-free due to inconsistent refcount handling
  src/redisearch_rs/c_entrypoint/rlookup_ffi/src/row.rs
  src/redisearch_rs/c_entrypoint/sorting_vector_ffi/src/lib.rs
  src/redisearch_rs/rlookup/src/row.rs
  src/redisearch_rs/rlookup/tests/row.rs
  src/redisearch_rs/sorting_vector/tests/sorting_vector.rs
  src/redisearch_rs/value/src/lib.rs
Labels: size:M

#6856 MOD-11172: Add Argument Parser Struct To Improve Parsing Experience
  src/util/arg_parser.c
  src/util/arg_parser.h
  tests/cpptests/test_cpp_arg_parser.cpp
Labels: size:L, size:XL

#6844 mov repairInvIndex logic and friends from gc to II
  src/fork_gc.c
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/redisearch_rs/inverted_index_bencher/build.rs
Labels: size:M, size:L

#6882 MOD-11352: Support SVS in FT.HYBRID
  src/vector_index.c
  tests/pytests/test_hybrid_vector_normalizer.py
Labels: size:M

#6892 test: increase timeout to avoid flakyness due to some clock precision
  tests/pytests/test_expire.py
Labels: size:S, enforce:test

#6888 Fix test_hybrid_multithread flakiness
  tests/pytests/test_hybrid_multithread.py
Labels: size:XS

#6889 MOD-11584: Align FT.HYBRID response format with the PRD
  src/hybrid/hybrid_exec.c
  tests/pytests/common.py
  tests/pytests/test_hybrid.py
  tests/pytests/utils/hybrid.py
Labels: size:M

#6868 remove readies from memcheck
  sbin/memcheck-summary
Labels: backport 2.8, backport 2.6, backport 2.10, size:XS, backport 8.2

#6846 MOD-10082 Rust Wildcard Iterator
  src/redisearch_rs/Cargo.lock
  src/redisearch_rs/build_utils/src/lib.rs
  src/redisearch_rs/inverted_index_bencher/build.rs
  src/redisearch_rs/rqe_iterators/src/lib.rs
  src/redisearch_rs/rqe_iterators/src/wildcard.rs
  src/redisearch_rs/rqe_iterators/tests/wildcard.rs
  src/redisearch_rs/rqe_iterators_bencher/Cargo.toml
  src/redisearch_rs/rqe_iterators_bencher/benches/iterators.rs
  src/redisearch_rs/rqe_iterators_bencher/build.rs
  src/redisearch_rs/rqe_iterators_bencher/src/benchers/c/wildcard.c
  src/redisearch_rs/rqe_iterators_bencher/src/benchers/mod.rs
  src/redisearch_rs/rqe_iterators_bencher/src/benchers/wildcard.rs
  src/redisearch_rs/rqe_iterators_bencher/src/ffi.rs
Labels: size:L

#6877 [MOD-11400] Add memory guardrail before AREQ_BuildPipeline
  src/aggregate/aggregate_exec.c
  src/query_error.h
  tests/pytests/test_query_oom.py
Labels: size:M, size:XL

#6803 Move `RSValue_SendReply` to `reply` module
  src/aggregate/aggregate_exec.c
  src/debug_commands.c
  src/hybrid/hybrid_exec.c
  src/reply.c
  src/reply.h
  src/value.c
  src/value.h
Labels: enforce:coverage, enforce:sanitize, size:M, enforce:test

#6929 fix path on benchmarks input
  .github/workflows/benchmark-flow.yml
Labels: action:run-benchmark, size:XS

#6919 [8.4]: Cherry-pick #6913 Add missing lines after feature branch merge (#6913)
  pack/ramp-community.yml
  pack/ramp-enterprise.yml
  src/aggregate/aggregate_request.c
  src/pipeline/pipeline_construction.c
Labels: size:S, size:XS

#6852 Fix The Unit Tests Script To Work With GDB And Compute BINDIR
  sbin/unit-tests
Labels: size:M

#6807 MOD-11307 implement `RLookupRow::get` in Rust porting C function `RLookup_GetItem`
  src/redisearch_rs/rlookup/src/lookup.rs
  src/redisearch_rs/rlookup/src/row.rs
  src/redisearch_rs/rlookup/tests/row.rs
  src/redisearch_rs/sorting_vector/src/lib.rs
Labels: size:M

#6894 MOD-11043: FT.HYBRID - Support Score And Distance Aliasing
  src/aggregate/aggregate_plan.h
  src/aggregate/aggregate_request.c
  src/hybrid/hybrid_request.c
  src/hybrid/parse/hybrid_combine.c
  src/hybrid/parse_hybrid.c
  src/hybrid/vector_query_utils.h
  src/pipeline/pipeline.h
  src/pipeline/pipeline_construction.c
  src/query_error.h
  src/result_processor.c
  src/search_options.h
  tests/cpptests/test_cpp_parse_hybrid.cpp
  tests/pytests/test_hybrid.py
  tests/pytests/test_hybrid_yield.py
Labels: size:M, size:L

#6885 [MOD-10970] - Default Dialect for Hybrid commands should be at least 2
  src/hybrid/hybrid_exec.c
  src/hybrid/parse/hybrid_callbacks.c
  src/hybrid/parse/hybrid_optional_args.c
  src/hybrid/parse/hybrid_optional_args.h
  src/hybrid/parse_hybrid.c
  tests/cpptests/test_cpp_parse_hybrid.cpp
  tests/pytests/test_hybrid.py
  tests/pytests/test_hybrid_dialect.py
  tests/pytests/test_hybrid_internal.py
Labels: size:S, size:M, size:XL

#6795 MOD-11090: Try marking DROP commands as touches-arbitrary-keys
  src/module.c
Labels: size:S

#6851 Inverted Index FFI preparation and tweaks
  src/inverted_index/inverted_index.c
  src/inverted_index/inverted_index.h
  src/iterators/inverted_index_iterator.c
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/cbindgen.toml
  src/redisearch_rs/c_entrypoint/inverted_index_ffi/src/lib.rs
  src/redisearch_rs/headers/future/inverted_index.h
  src/redisearch_rs/inverted_index/src/lib.rs
  src/redisearch_rs/inverted_index/src/numeric.rs
  src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
  src/redisearch_rs/inverted_index/tests/numeric.rs
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/index_utils.cpp
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_iterator_index.cpp
  tests/cpptests/test_cpp_iterator_intersection.cpp
  tests/cpptests/test_cpp_iterator_not.cpp
  tests/cpptests/test_cpp_iterator_optional.cpp
  tests/cpptests/test_cpp_iterator_union.cpp
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/cpptests/test_cpp_tagindex.cpp
  tests/ctests/test_cntokenize.c
  tests/pytests/test_json_multi_geo.py
  tests/pytests/test_json_multi_numeric.py
Labels: size:M

#6808 MOD-10399 refactor: encapsulate SearchResult
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_exec_common.c
  src/aggregate/expr/expression.c
  src/aggregate/functions/string.c
  src/aggregate/group_by.c
  src/coord/dist_aggregate.c
  src/highlight_processor.c
  src/hybrid/hybrid_exec.c
  src/hybrid/hybrid_search_result.c
  src/hybrid/hybrid_search_result.h
  src/index_result.c
  src/index_result.h
  src/redisearch_rs/ffi/build.rs
  src/result_processor.c
  src/result_processor.h
  src/score_explain.c
  src/score_explain.h
  src/search_result.c
  src/search_result.h
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_hybridmerger.cpp
  tests/cpptests/test_cpp_resultprocessor.cpp
  tests/cpptests/test_cpp_rpdepleter.cpp
Labels: size:M, size:L

#6880 MOD-11416: Fix `total_result` Accuracy When Using FILTER
  src/aggregate/expr/expression.c
  tests/pytests/common.py
  tests/pytests/test_hybrid.py
  tests/pytests/test_hybrid_apply_filter.py
  tests/pytests/test_hybrid_dialect.py
  tests/pytests/test_hybrid_distance.py
  tests/pytests/test_hybrid_groupby.py
  tests/pytests/test_hybrid_multithread.py
  tests/pytests/test_hybrid_search.py
  tests/pytests/test_hybrid_timeout.py
  tests/pytests/test_hybrid_vector.py
  tests/pytests/test_hybrid_vector_normalizer.py
  tests/pytests/test_hybrid_yield.py
  tests/pytests/test_rrf.py
Labels: size:S, size:M
