Repository RediSearch/RediSearch, pull requests merged in 2025-02, with the labels that each got.

#5591 Fix SkipTo edge case - [MOD-8561 MOD-8673]
  src/fork_gc.c
  src/inverted_index.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5597 [2.8] Fix inverted index last id update on GC
  src/fork_gc.c
  src/inverted_index.c
  tests/pytests/test_issues.py
Labels: bug

#5599 [2.10] Fix inverted index last id update on GC
  src/fork_gc.c
  src/inverted_index.c
  tests/pytests/test_issues.py
Labels: bug

#5596 Revert inverted index iterator changes
  src/inverted_index.c
  tests/cpptests/test_cpp_index.cpp
Labels: bug, backport 2.8, backport 2.6

#5598 [2.6] Fix inverted index last id update on GC
  src/fork_gc.c
  src/inverted_index.c
  tests/pytests/test_issues.py
Labels: bug

#5574 MOD-8144: Restore filtering stop words in the beginning of tag queries
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_parser.py
Labels: backport 2.8, backport 2.6, backport 2.10

#5600 Parser Performance Improvement - [MOD-8656]
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
Labels: action:run-benchmark, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5620 MOD-8791: Update redis version for coverage flow to unstable
  .github/workflows/flow-coverage.yml
Labels: backport 8.0

#5572 MOD-8178: Remove stopwords filtering from termlist parsing
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  tests/pytests/test_parser.py
Labels: backport 8.0

#5628 MOD-8791: Fix redis version of artifact deployment to unstable
  .github/workflows/flow-build-artifacts.yml
Labels: backport 8.0

#5565 MOD-8649: Fix number parsing
  src/aggregate/expr/lexer.c
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  tests/pytests/test_dialect.py
  tests/pytests/test_numbers.py
Labels: backport 8.0, breaking change

#5634 ACL check fix
  src/module.c
Labels: backport 8.0

#5616 Rename info fields [MOD-8168]
  src/cursor.c
  src/cursor.h
  src/info/info_redis.c
  tests/pytests/test_info_modules.py
Labels: backport 8.0

#5391 MOD-7944: Support multi-byte char terms
  CMakeLists.txt
  src/query.c
  src/query_param.c
  src/query_parser/v1/lexer.c
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/lexer.c
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/stemmer.c
  src/synonym_map.c
  src/tag_index.c
  src/tokenize.c
  src/trie/levenshtein.c
  src/trie/levenshtein.h
  src/trie/rune_util.c
  src/trie/rune_util.h
  src/trie/trie_type.c
  src/util/strconv.h
  tests/cpptests/test_cpp_llapi.cpp
  tests/cpptests/test_cpp_tokenizer.cpp
  tests/ctests/test_trie.c
  tests/pytests/test_cn.py
  tests/pytests/test_multibyte_char_terms.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5635 Fail `FT.INFO` if schema is inconsistent across shards - [MOD-7609]
  src/coord/info_command.c
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.10, backport 8.0

#5623 Support KNN and HIGHLIGHT - [MOD-8695]
  src/aggregate/aggregate_request.c
  src/highlight_processor.c
  src/hybrid_reader.c
  src/hybrid_reader.h
  src/search_options.h
  src/vector_index.c
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_issues.py
Labels: bug, backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5650 [2.8] Support KNN and HIGHLIGHT - [MOD-8695]
  src/aggregate/aggregate_request.c
  src/highlight_processor.c
  src/hybrid_reader.c
  src/hybrid_reader.h
  src/search_options.h
  src/vector_index.c
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_issues.py
Labels: bug

#5651 [2.10] Support KNN and HIGHLIGHT - [MOD-8695]
  src/aggregate/aggregate_request.c
  src/highlight_processor.c
  src/hybrid_reader.c
  src/hybrid_reader.h
  src/search_options.h
  src/vector_index.c
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_issues.py
Labels: bug

#5653 [2.10] Fail `FT.INFO` if schema is inconsistent across shards - [MOD-7609]
  coord/src/info_command.c
  tests/pytests/test_issues.py
Labels: bug

#5652 [2.8] Fail `FT.INFO` if schema is inconsistent across shards - [MOD-7609]
  coord/src/info_command.c
  tests/pytests/test_issues.py
Labels: bug

#5480 MOD-6052: Elaborate "FT.INFO"
  src/coord/info_command.c
  src/field_spec.c
  src/field_spec.h
  src/info/field_spec_info.c
  src/info/field_spec_info.h
  src/info/index_error.c
  src/info/index_error.h
  src/info/indexes_info.c
  src/info/indexes_info.h
  src/info/info_command.c
  src/info/vector_index_stats.c
  src/info/vector_index_stats.h
  src/spec.c
  src/spec.h
  tests/ctests/test_vector_index_stats.c
  tests/pytests/common.py
  tests/pytests/test_info.py
  tests/pytests/test_replicate.py
Labels: backport 8.0

#5442 MOD-7595: Use Open Key Expiration Flags To Access Lazily Expired Keys/Fields
  sbin/get-redisjson
  src/document.h
  src/document_basic.c
  src/rlookup.c
  src/spec.c
  tests/pytests/test_expire.py
  tests/pytests/test_replicate.py
Labels: backport 8.0

#5649 [2.6] Support KNN and HIGHLIGHT - [MOD-8695]
  src/aggregate/aggregate.h
  src/aggregate/aggregate_request.c
  src/highlight_processor.c
  src/hybrid_reader.c
  src/hybrid_reader.h
  src/search_options.h
  src/vector_index.c
  tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_issues.py
Labels: bug

#5355 MOD-8271: Use TTL Information In IR_SkipTo
  src/inverted_index.c
  tests/cpptests/CMakeLists.txt
  tests/cpptests/redismock/internal.h
  tests/cpptests/redismock/redismock.cpp
  tests/cpptests/test_cpp_expire.cpp
  tests/cpptests/test_cpp_forkgc.cpp
  tests/pytests/test_expire.py
Labels: backport 2.10, backport 8.0

#5622 Simplify testing with JSON flow - purge readies [MOD-8156]
  .codespell/ignore_wordlist.txt
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-coverage.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/flow-macos.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
  .install/amazon_linux_2.sh
  .install/amazon_linux_2023.sh
  .install/common_base_linux_mariner_2.0.sh
  .install/debian_gnu_linux_11.sh
  .install/debian_gnu_linux_12.sh
  .install/test_deps/common_installations.sh
  .install/ubuntu_18.04.sh
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  Makefile
  sbin/build-redisjson
  sbin/get-redisjson
  tests/deps/setup_rejson.sh
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5456 MOD-8275: Add A Function To Format A Parsed Expression
  src/aggregate/expr/exprast.c
  src/aggregate/expr/expression.h
  src/obfuscation/obfuscation_api.c
  src/obfuscation/obfuscation_api.h
  src/result_processor.c
  src/rlookup.c
  src/rlookup.h
  src/value.c
  src/value.h
  tests/cpptests/test_cpp_agg.cpp
  tests/cpptests/test_cpp_expr.cpp
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5664 MOD-8835: Fix CONFIG names in __configPairs
  src/config.c
  src/config.h
  src/coord/config.c
  src/coord/config.h
  src/module.c
  tests/pytests/test_config.py
Labels: backport 8.0
