Repository RediSearch/RediSearch, pull requests merged in 2025-03, with the labels that each got.

#5554 Introducing query debug mechanism :tada:
  src/aggregate/aggregate.h
  src/aggregate/aggregate_debug.c
  src/aggregate/aggregate_debug.h
  src/aggregate/aggregate_exec.c
  src/coord/dist_aggregate.c
  src/coord/rmr/chan.c
  src/coord/rmr/chan.h
  src/coord/rmr/rmr.c
  src/coord/rmr/rmr.h
  src/debug_commands.c
  src/module.c
  src/module.h
  src/result_processor.c
  src/result_processor.h
  src/util/timeout.h
  tests/pytests/common.py
  tests/pytests/test_cursors.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_resp3.py
  tests/pytests/test_timeout.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5716 MOD-8989 - Obfuscation API Changes
  CMakeLists.txt
  build/boost/boost.cmake
  src/geometry/CMakeLists.txt
  src/obfuscation/hidden.c
  src/obfuscation/hidden.h
  src/obfuscation/hidden_unicode.c
  src/obfuscation/hidden_unicode.h
  src/obfuscation/obfuscation_api.c
  src/obfuscation/obfuscation_api.h
  src/util/hash/CMakeLists.txt
  src/util/hash/hash.cpp
  src/util/hash/hash.h
  tests/cpptests/test_cpp_hash.cpp
  tests/cpptests/test_cpp_hidden.cpp
  tests/ctests/test_obfuscation.c
Labels: backport 2.10, backport 8.0

#5726 Simplify install script
  .github/workflows/benchmark-flow.yml
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-coverage.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-get-linux-configurations.yml
  .github/workflows/task-test.yml
  .install/alpine_linux_3.sh
  .install/amazon_linux_2.sh
  .install/amazon_linux_2023.sh
  .install/common_base_linux_mariner_2.0.sh
  .install/debian_gnu_linux_11.sh
  .install/debian_gnu_linux_12.sh
  .install/install_boost.sh
  .install/install_llvm.sh
  .install/install_script.sh
  .install/macos.sh
  .install/macos_update_profile.sh
  .install/rocky_linux_8.sh
  .install/rocky_linux_9.sh
  .install/test_deps/common_installations.sh
  .install/test_deps/install_llvm.sh
  .install/ubuntu_18.04.sh
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  .install/ubuntu_24.04.sh
  developer.md
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5752 Remove cmdCtx from prepareForExecution
  src/coord/dist_aggregate.c
Labels: backport 8.0

#5733 Fixing benchmark runner: Update terraform to 1.11.1 and redisbench-admin>=0.11.14
  .github/workflows/benchmark-flow.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/requirements.txt
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
Labels: action:run-benchmark

#5717 MOD-8992: Numeric Filter Separate Legacy Types
  .codespell/ignore_wordlist.txt
  src/aggregate/aggregate_request.c
  src/aggregate/expr/lexer.c
  src/geo_index.c
  src/geo_index.h
  src/numeric_filter.c
  src/numeric_filter.h
  src/numeric_index.c
  src/optimizer_reader.c
  src/query.c
  src/query_internal.h
  src/query_optimizer.c
  src/query_param.c
  src/query_parser/v1/lexer.c
  src/query_parser/v1/parser.c
  src/query_parser/v1/parser.y
  src/query_parser/v2/lexer.c
  src/query_parser/v2/parser.c
  src/query_parser/v2/parser.y
  src/redisearch_api.c
  src/search_options.h
  tests/cpptests/test_cpp_query.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/pytests/test.py
Labels: backport 2.10, backport 8.0

#5748 Fix CI - snapshot build and nightly - [MOD-9036]
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/task-build-artifacts.yml
  .github/workflows/task-test.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5749 MOD-9034: Fix Undefined BOOST_DIR
  CMakeLists.txt
  build/boost/boost.cmake
Labels: backport 8.0

#5764 remove docs only check
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-temp.yml
  .github/workflows/task-check-docs.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5767 Lock deepdiff module version
  tests/pytests/requirements.txt
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5720 MOD-8949: Support azure linux 3
  .github/workflows/flow-build-artifacts.yml
  .github/workflows/flow-linux-platforms.yml
  .github/workflows/task-get-linux-configurations.yml
  .install/microsoft_azure_linux_3.0.sh
Labels: backport 2.10, backport 8.0

#5759 [2.10] Fixing benchmark runner: Update terraform to 1.11.1 and redisbench-admin>=0.11.14
  .github/workflows/benchmark-flow.yml
  tests/benchmarks/defaults.yml
  tests/benchmarks/requirements.txt
  tests/benchmarks/vecsim-ann-benchmarks_LOAD_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
  tests/benchmarks/vecsim-ann-benchmarks_QUERY_1c_redisearch-hnsw_mnist-784-euclidean_M-4.yml
Labels: action:run-benchmark

#5780 MOD-8969: Compute test coverage for Rust code
  .github/workflows/flow-coverage.yml
  .install/install_rust.sh
  .install/test_deps/common_installations.sh
  Makefile
  src/redisearch_rs/trie_rs/src/lib.rs
Labels: enforce:coverage

#5785 Prevent install.sh from exiting early when Boost is already installed
  .install/install_script.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5786 Print "sanitizer" in CI artifacts to ensure unique name among flows
  .github/workflows/task-test.yml
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5765 MOD-9054: Fix `total_results` field in shard RESP3 response
  src/aggregate/aggregate_exec.c
  tests/pytests/test_resp3.py
Labels: backport 2.8, backport 2.10, backport 8.0

#5787 Fix indentation to set pre-deps
  .github/workflows/task-get-linux-configurations.yml
Labels: backport 8.0

#5781 MOD-8969: Run Rust tests through miri to catch undefined behaviour
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/task-test.yml
  .install/install_rust.sh
  .install/test_deps/common_installations.sh
  Makefile
Labels: enforce:sanitize

#5349 MOD-8578: Use fast_float library
  .codespell/ignore_wordlist.txt
  CMakeLists.txt
  deps/fast_float/CMakeLists.txt
  deps/fast_float/README.md
  deps/fast_float/fast_float.h
  deps/fast_float/fast_float_strtod.cpp
  deps/fast_float/fast_float_strtod.h
  src/aggregate/expr/lexer.c
  src/aggregate/expr/lexer.rl
  src/coord/rmr/reply.c
  src/document.c
  src/module.c
  src/numeric_filter.c
  src/query_parser/v1/lexer.c
  src/query_parser/v1/lexer.rl
  src/query_parser/v2/lexer.c
  src/query_parser/v2/lexer.rl
  src/rs_geo.c
  src/rules.c
  src/util/strconv.h
  src/value.c
  tests/pytests/test_search_params.py
Labels: action:run-benchmark, backport 8.0

#5789 MOD-9105: Fix section name in `INFO` response
  src/info/info_redis.c
  tests/pytests/test_info_modules.py
Labels: backport 8.0

#5740 MOD-7878: Support Index Debug Commands
  src/coord/info_command.c
  src/cursor.c
  src/cursor.h
  src/debug_commands.c
  src/document.c
  src/document.h
  src/fork_gc.c
  src/indexer.c
  src/indexer.h
  src/info/field_spec_info.c
  src/info/field_spec_info.h
  src/info/info_command.c
  src/info/info_command.h
  src/module.c
  src/notifications.c
  src/query.c
  src/search_ctx.h
  src/spec.c
  src/spec.h
  src/tag_index.c
  src/tag_index.h
  tests/cpptests/test_cpp_expire.cpp
  tests/cpptests/test_cpp_forkgc.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/pytests/test_debug_commands.py
  tests/pytests/test_issues.py
Labels: backport 2.10, backport 8.0

#5820 MOD-9161: Change scorer name from BM25STD.NORM to BM25STD.TANH
  src/ext/default.c
  src/ext/default.h
  tests/pytests/test_scorers.py
Labels: backport 2.10, backport 8.0

#5823 Updated the base image of benchmarks to run on 24.04
  .github/workflows/benchmark-flow.yml
Labels: action:run-benchmark

#5818 MOD-8674: Fix TLS connection to shards
  src/coord/rmr/conn.c
  tests/pytests/requirements.txt
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0

#5403 MOD-8391: Report active threads-indexes upon crash
  CMakeLists.txt
  src/aggregate/aggregate_debug.c
  src/aggregate/aggregate_exec.c
  src/aggregate/aggregate_plan.c
  src/aggregate/aggregate_plan.h
  src/aggregate/aggregate_request.c
  src/coord/dist_aggregate.c
  src/coord/dist_plan.cpp
  src/doc_table.c
  src/document_add.c
  src/fork_gc.c
  src/info/info_command.c
  src/info/info_redis/block_client.c
  src/info/info_redis/block_client.h
  src/info/info_redis/info_redis.c
  src/info/info_redis/info_redis.h
  src/info/info_redis/threads/current_thread.c
  src/info/info_redis/threads/current_thread.h
  src/info/info_redis/threads/main_thread.c
  src/info/info_redis/threads/main_thread.h
  src/info/info_redis/types/blocked_queries.c
  src/info/info_redis/types/blocked_queries.h
  src/info/info_redis/types/spec_info.h
  src/module-init/module-init.c
  src/module.c
  src/notifications.c
  src/redisearch_api.c
  src/result_processor.c
  src/result_processor.h
  src/spec.c
  src/spec.h
  src/util/dllist.h
  src/util/threadpool_api.c
  tests/cpptests/index_utils.cpp
  tests/cpptests/test_cpp_expire.cpp
  tests/cpptests/test_cpp_index.cpp
  tests/cpptests/test_cpp_query.cpp
  tests/cpptests/test_cpp_range.cpp
  tests/pytests/common.py
  tests/pytests/test_crash.py
Labels: backport 2.10, backport 8.0

#5839 [MOD-9217] Fix timeout testFailOnTimeout_nonStrict ON_TIMEOUT policy
  tests/pytests/test_profile.py
Labels: backport 2.8, backport 2.10, backport 8.0
