Repository RediSearch/RediSearch, pull requests merged in 2025-05, with the labels that each got.

#6017 Build without readies [MOD-5711]
  .github/workflows/benchmark-flow.yml
  .github/workflows/task-test.yml
  .install/macos_update_profile.sh
  CMakeLists.txt
  Makefile
  build.sh
  build/boost/boost.cmake
  build/docker/Makefile
  build/docker/dockerfile.tmpl
  build/hiredis/hiredis.cmake
  build/s2geometry/Makefile
  build/s2geometry/Makefile.defs
  sbin/unit-tests
  src/coord/CMakeLists.txt
  src/coord/rmr/CMakeLists.txt
  tests/pytests/runtests.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XL

#6044 CI Improvement - Coverage fixes
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-coverage.yml
  Makefile
Labels: size:S

#6079 Fix rust format
  .github/workflows/event-pull_request.yml
  src/redisearch_rs/trie_rs/src/node/metadata.rs
Labels: size:XS

#6080 Revert changing default timeout to fail + adjust tests [MOD-7791]
  .codespell/ignore_wordlist.txt
  src/config.c
  src/config.h
  tests/pytests/test.py
  tests/pytests/test_aggregate.py
  tests/pytests/test_config.py
  tests/pytests/test_contains.py
  tests/pytests/test_coordinator.py
  tests/pytests/test_cursors.py
  tests/pytests/test_expire.py
  tests/pytests/test_issues.py
  tests/pytests/test_json.py
  tests/pytests/test_multibyte_char_terms.py
  tests/pytests/test_multithread.py
  tests/pytests/test_optimizer.py
  tests/pytests/test_profile.py
  tests/pytests/test_resp3.py
  tests/pytests/test_tags.py
  tests/pytests/test_wildcard.py
Labels: backport 8.0, size:S

#6030 Run all Rust benchmarks in the workspace
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-micro-benchmarks.yml
  src/redisearch_rs/redisearch_rs/Cargo.toml
Labels: size:S, enforce:micro-benchmarks

#6086 Fix Rust build after switching off readies
  CMakeLists.txt
  Makefile
  build.sh
Labels: size:S

#6053 [MOD-9560] Change default config value for _BG_INDEX_MEM_PCT_THR
  src/config.c
  src/config.h
  tests/pytests/common.py
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_index_oom.py
Labels: backport 8.0, size:M

#6082 Build unit tests without readies [MOD-9099]
  .github/workflows/task-test.yml
  build.sh
  sbin/unit-tests
  tests/ctests/test_leak.c
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M

#6070 Update SECURITY.md
  SECURITY.md
Labels: backport 8.0, size:XS

#6090 Enforce license headers for Rust files
  .github/workflows/task-lint.yml
  Makefile
  src/redisearch_rs/.cargo/config.toml
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/tools/license_header_linter/Cargo.toml
  src/redisearch_rs/tools/license_header_linter/src/main.rs
Labels: size:M

#5908 MOD-6151: Build without readies - simplify packing
  Makefile
  sbin/get-platform
  sbin/getver
  sbin/pack.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M

#6095 Don't add unnecessary \n after the license header
  src/redisearch_rs/tools/license_header_linter/src/main.rs
Labels: size:XS

#6100 MOD-9612: Fix flaky test and change early timeout error message
  src/aggregate/aggregate_exec.c
  src/query_error.h
  src/util/timeout.h
  tests/pytests/test.py
Labels: backport 2.8, backport 2.10, backport 8.0, size:S

#6108 MOD-9612: Do not check for early timeouts in non-strict timeout policy
  src/aggregate/aggregate_exec.c
  src/query_error.h
  src/util/timeout.h
  tests/pytests/test.py
  tests/pytests/test_contains.py
  tests/pytests/test_wildcard.py
Labels: backport 2.8, backport 2.10, backport 8.0, size:S

#6033 MOD 9367 - qint Encoding/Decoding rewrite in Rust
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/qint/Cargo.toml
  src/redisearch_rs/qint/benches/qint-bench.rs
  src/redisearch_rs/qint/src/lib.rs
  src/redisearch_rs/qint/tests/qint.rs
Labels: size:L

#6118 MOD-9671: Use wheel for gevent
  .github/workflows/flow-macos.yml
  tests/pytests/requirements.txt
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#6102 Fix build for C23
  CMakeLists.txt
  src/util/circular_buffer.c
  tests/ctests/test_khtable.c
Labels: size:S

#6099 Save compile_commands.json
  CMakeLists.txt
Labels: size:XS

#6117 [MOD-9688] Use `&[u8]` as key type rather than `&[c_char]` to get the expected ordering behaviour in iterators.
  .github/workflows/flow-micro-benchmarks.yml
  src/redisearch_rs/trie_bencher/build.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/lib.rs
  src/redisearch_rs/trie_bencher/src/main.rs
  src/redisearch_rs/trie_rs/src/iter/filter.rs
  src/redisearch_rs/trie_rs/src/iter/iter_.rs
  src/redisearch_rs/trie_rs/src/iter/lending.rs
  src/redisearch_rs/trie_rs/src/node/accessors.rs
  src/redisearch_rs/trie_rs/src/node/metadata.rs
  src/redisearch_rs/trie_rs/src/node/mod.rs
  src/redisearch_rs/trie_rs/src/node/trait_impls.rs
  src/redisearch_rs/trie_rs/src/node/trie_ops.rs
  src/redisearch_rs/trie_rs/src/trie.rs
  src/redisearch_rs/trie_rs/src/utils.rs
  src/redisearch_rs/trie_rs/tests/integration/iter.rs
  src/redisearch_rs/trie_rs/tests/integration/main.rs
  src/redisearch_rs/trie_rs/tests/integration/trie.rs
  src/redisearch_rs/trie_rs/tests/integration/utils.rs
  src/redisearch_rs/wildcard/src/fmt.rs
  src/redisearch_rs/wildcard/src/lib.rs
  src/redisearch_rs/wildcard/tests/integration/matches.rs
  src/redisearch_rs/wildcard/tests/integration/parse.rs
  src/redisearch_rs/wildcard/tests/integration/properties.rs
  src/redisearch_rs/wildcard/tests/integration/utils.rs
Labels: size:L

#6121 CI: Enable full backtrace for Rust panics
  .github/workflows/flow-coverage.yml
  .github/workflows/task-test.yml
Labels: size:XS

#6122 Some cargo clippy fixes
  src/redisearch_rs/low_memory_thin_vec/tests/tests.rs
  src/redisearch_rs/wildcard/benches/matching.rs
  src/redisearch_rs/wildcard/tests/integration/utils.rs
Labels: size:S

#6128 Use the correct Rust profile for every task
  .github/workflows/task-test.yml
  build.sh
Labels: size:S

#6127 Compute coverage for Rust tests in CI
  .github/workflows/flow-coverage.yml
  Makefile
Labels: size:XS

#6132 restore macos-latest-xlarge
  .github/workflows/flow-macos.yml
Labels: size:XS

#6131 CI - update release flow - [MOD-9681]
  .github/workflows/event-release.yml
Labels: backport 8.0, size:S

#6119 [MOD-9694] Trie prefixes iterator
  CMakeLists.txt
  src/redisearch_rs/trie_bencher/Cargo.toml
  src/redisearch_rs/trie_bencher/benches/iter.rs
  src/redisearch_rs/trie_bencher/build.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/c_map.rs
  src/redisearch_rs/trie_bencher/src/corpus.rs
  src/redisearch_rs/trie_bencher/src/ffi.rs
  src/redisearch_rs/trie_rs/src/iter/mod.rs
  src/redisearch_rs/trie_rs/src/iter/prefixes.rs
  src/redisearch_rs/trie_rs/src/node/trait_impls.rs
  src/redisearch_rs/trie_rs/src/trie.rs
  src/redisearch_rs/trie_rs/tests/integration/iter.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/filter.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/mod.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/prefixed.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/prefixes.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/unfiltered.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/values.rs
  src/redisearch_rs/trie_rs/tests/integration/trie.rs
  src/util/arr.c
  src/util/arr.h
  src/util/arr/CMakeLists.txt
  src/util/arr/arr.c
  src/util/arr/arr.h
Labels: size:XL

#6129 [MOD-9693] IntoValues trie iterator.
  src/redisearch_rs/trie_bencher/benches/iter.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_rs/src/iter/into_values.rs
  src/redisearch_rs/trie_rs/src/iter/mod.rs
  src/redisearch_rs/trie_rs/src/node/metadata.rs
  src/redisearch_rs/trie_rs/src/node/mod.rs
  src/redisearch_rs/trie_rs/src/node/trait_impls.rs
  src/redisearch_rs/trie_rs/src/node/trie_ops.rs
  src/redisearch_rs/trie_rs/src/trie.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/values.rs
Labels: size:M

#6147 rockylinux:8 install python3.12 packages
  .install/rocky_linux_8.sh
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:XS

#6146 Fix linting failure on Rust LowMemoryThinVec drop implementation
  src/redisearch_rs/low_memory_thin_vec/src/lib.rs
Labels: size:XS

#5909 Coverage Report Without `readies` - Phase 2 - [MOD-6711]
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-coverage.yml
  .github/workflows/task-test.yml
  CMakeLists.txt
  build.sh
  sbin/unit-tests
  src/doc_types.c
  src/print_version.c
  src/redisearch_rs/qint/tests/qint.rs
Labels: backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M

#6120 Build without readies [2.10]
  .github/workflows/benchmark-flow.yml
  .github/workflows/task-test.yml
  .install/macos_update_profile.sh
  CMakeLists.txt
  Makefile
  build.sh
  build/boost/boost.cmake
  build/docker/Makefile
  build/docker/dockerfile.tmpl
  build/hiredis/hiredis.cmake
  build/s2geometry/Makefile
  build/s2geometry/Makefile.defs
  coord/CMakeLists.txt
  coord/src/rmr/CMakeLists.txt
  sbin/unit-tests
  tests/cpptests/CMakeLists.txt
  tests/pytests/runtests.sh
Labels: action:run-benchmark

#6153 CI Improvements
  .github/workflows/benchmark-flow.yml
  .github/workflows/benchmark-runner.yml
  .github/workflows/benchmark-trigger.yml
  .github/workflows/event-pull_request.yml
  .github/workflows/event-push-to-integ.yml
  .github/workflows/event-weekly.yml
  .github/workflows/flow-micro-benchmarks.yml
  .github/workflows/task-check-changes.yml
  .github/workflows/task-lint.yml
Labels: size:M

#6157 Add .cache to git ignore list
  .gitignore
Labels: size:XS

#6114 [MOD-9372 , MOD-9733] Stop indexing OOM - Add wait before OOM
  src/config.c
  src/config.h
  src/debug_commands.c
  src/debug_commands.h
  src/spec.c
  src/spec.h
  tests/pytests/common.py
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_index_oom.py
Labels: enforce:coverage, size:L

#6166 Temp disable coverage as required for CI to pass in PRs
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-pull_request.yml
Labels: size:XS

#6156 [MOD-9735] Track the number of unique keys in the trie.
  src/redisearch_rs/trie_rs/src/trie.rs
  src/redisearch_rs/trie_rs/tests/integration/trie.rs
Labels: size:S

#6170 Use the correct profile name for Rust debug builds
  build.sh
Labels: size:XS

#6167 MOD-9787: Add More Diagnostics When Active Queries Are Not Empty
  src/info/info_redis/block_client.c
  src/info/info_redis/types/blocked_queries.c
  src/info/info_redis/types/blocked_queries.h
  src/module-init/module-init.c
Labels: size:S

#6165 mention BM25 as default scorer in README
  README.md
Labels: size:XS

#6103 Yield to redis while indexing - [MOD-9220]
  src/config.c
  src/config.h
  src/debug_commands.c
  src/indexer.c
  src/indexer.h
  src/spec.c
  tests/cpptests/redismock/redismock.cpp
  tests/pytests/test_config.py
  tests/pytests/test_debug_commands.py
  tests/pytests/test_issues.py
Labels: action:run-benchmark, backport 2.8, backport 2.6, backport 2.10, backport 8.0, size:M

#6176 Small Diagnostic Fix
  .github/workflows/task-test.yml
  src/module-init/module-init.c
Labels: size:XS

#6174 MOD-9766: Build and pack RediSearch OSS
  .github/workflows/task-build-artifacts.yml
  sbin/upload-artifacts
Labels: backport 8.0, size:XS

#6155 [MOD-9695] Trie range iterator
  src/redisearch_rs/trie_bencher/benches/iter.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/c_map.rs
  src/redisearch_rs/trie_bencher/src/ffi.rs
  src/redisearch_rs/trie_rs/src/iter/iter_.rs
  src/redisearch_rs/trie_rs/src/iter/lending_range.rs
  src/redisearch_rs/trie_rs/src/iter/mod.rs
  src/redisearch_rs/trie_rs/src/iter/range.rs
  src/redisearch_rs/trie_rs/src/iter/values.rs
  src/redisearch_rs/trie_rs/src/trie.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/mod.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/range.rs
Labels: size:L

#6159 [MOD-9734] Trie contains iterator
  src/redisearch_rs/trie_bencher/benches/iter.rs
  src/redisearch_rs/trie_bencher/src/bencher.rs
  src/redisearch_rs/trie_bencher/src/c_map.rs
  src/redisearch_rs/trie_bencher/src/ffi.rs
  src/redisearch_rs/trie_rs/src/iter/contains.rs
  src/redisearch_rs/trie_rs/src/iter/lending_contains.rs
  src/redisearch_rs/trie_rs/src/iter/mod.rs
  src/redisearch_rs/trie_rs/src/trie.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/contains.rs
  src/redisearch_rs/trie_rs/tests/integration/iter/mod.rs
Labels: size:M

#6187 Build focal with gcc-11
  .install/ubuntu_20.04.sh
Labels: backport 8.0, size:XS

#6140 [MOD-9560] Revert marking index as faulty after reaching OOM
  src/aggregate/aggregate.h
  src/aggregate/aggregate_exec.c
  src/config.c
  src/coord/dist_aggregate.c
  src/module.c
  src/profile.c
  src/profile.h
  src/query_error.h
  src/spec.c
  tests/pytests/common.py
  tests/pytests/test_index_oom.py
Labels: size:M

#5948 MOD-8918, MOD-8920: Score normalization result processor for BM25STD.NORM scorer
  src/aggregate/aggregate_request.c
  src/ext/default.c
  src/ext/default.h
  src/profile.c
  src/result_processor.c
  src/result_processor.h
  src/score_explain.c
  src/score_explain.h
  tests/pytests/common.py
  tests/pytests/test_cursors.py
  tests/pytests/test_profile.py
  tests/pytests/test_scorers.py
Labels: backport 2.10, backport 8.0, size:M

#6205 Fix MT build with makefile [2.10]
  Makefile
Labels: backport 2.8

#6160 [MOD-9762] FFI bindings for Rust trie iterators
  src/redisearch_rs/Cargo.toml
  src/redisearch_rs/headers/triemap.h
  src/redisearch_rs/redis_mock/src/allocator.rs
  src/redisearch_rs/redis_mock/src/lib.rs
  src/redisearch_rs/redisearch_rs/Cargo.toml
  src/redisearch_rs/redisearch_rs/build.rs
  src/redisearch_rs/redisearch_rs/cbindgen.toml
  src/redisearch_rs/redisearch_rs/src/lib.rs
  src/redisearch_rs/redisearch_rs/src/trie.rs
  src/redisearch_rs/redisearch_rs/src/trie/find_prefixes.rs
  src/redisearch_rs/redisearch_rs/src/trie/iter.rs
  src/redisearch_rs/redisearch_rs/src/trie/iter_types.rs
  src/redisearch_rs/redisearch_rs/src/trie/mod.rs
  src/redisearch_rs/redisearch_rs/src/trie/range.rs
  src/redisearch_rs/redisearch_rs/tests/trie.rs
  src/redisearch_rs/trie_bencher/src/lib.rs
  src/redisearch_rs/trie_rs/src/iter/mod.rs
Labels: size:XL

#6177 Optimize chunk comparisons in wildcard matching
  src/redisearch_rs/wildcard/Cargo.toml
  src/redisearch_rs/wildcard/src/lib.rs
Labels: size:S, action:run-micro-benchmark

#6212 Fixes for the "Release by tag" flow
  .github/workflows/event-release.yml
Labels: backport 8.0, size:S

#6218 Refactor Union Iterator - [MOD-8841]
  CMakeLists.txt
  src/index.c
  src/index_iterator.h
  src/iterators/iterator_api.h
  src/iterators/union_iterator.c
  src/iterators/union_iterator.h
  tests/cpptests/iterator_util.h
  tests/cpptests/micro-benchmarks/CMakeLists.txt
  tests/cpptests/micro-benchmarks/benchmark_union_iterator.cpp
  tests/cpptests/micro-benchmarks/deprecated_iterator_util.h
  tests/cpptests/test_cpp_iterator_union.cpp
Labels: size:XL

#6151 change config setters and getters - [MOD-9673]
  src/config.c
  src/config.h
  src/coord/config.c
  tests/pytests/test_config.py
  tests/pytests/test_resp3.py
Labels: backport 8.0, size:M

#6220 [MOD-9798] Refactor `inverted_index`
  src/forward_index.c
  src/forward_index.h
  src/inverted_index.c
  src/inverted_index.h
  src/rules.c
  tests/cpptests/test_cpp_index.cpp
Labels: size:S

#6221 add IDList iterator refactor - [MOD-8846]
  src/iterators/idlist_iterator.c
  src/iterators/idlist_iterator.h
  tests/cpptests/micro-benchmarks/benchmark_idlist_iterator.cpp
  tests/cpptests/redismock/util.cpp
  tests/cpptests/test_cpp_iterator_idlist.cpp
  tests/cpptests/test_distagg.cpp
Labels: size:M, action:run-micro-benchmark
